import fs from 'node:fs/promises';
import {ENGLISH_STORIES,ENGLISH_PEOPLE,ENGLISH_METHOD} from './src/english/content.js';
import {TRANSLATED_STORIES,TRANSLATED_PEOPLE,englishRoute,englishPaths,translatedEquivalent} from './src/english/routes.js';
const people=[];
for(const p of TRANSLATED_PEOPLE){const source=JSON.parse(await fs.readFile(`public/personas-meta/${p.es}.json`,'utf8')),translation=ENGLISH_PEOPLE[p.id];if(source.id!==p.id)throw Error(`Traducción enlazada a otra persona: ${p.id}`);people.push({...source,...translation,nombre:translation.name,path:`/en/person/${p.en}`,esPath:`/es/persona/${p.es}`,summary:translation.summary,translated:true});}
const stories=[];
for(const s of TRANSLATED_STORIES){const source=JSON.parse(await fs.readFile(`public/historias-meta/${s.es}.json`,'utf8')),translation=ENGLISH_STORIES[s.id];if(source.pasos.length!==translation.chapters.length)throw Error(`Traducción incompleta: ${s.id}`);stories.push({...source,...translation,nombre:translation.title,path:`/en/story/${s.en}`,esPath:`/es/historia/${s.es}`,pasos:source.pasos.map((p,i)=>({...p,titulo:translation.chapters[i][0],texto:translation.chapters[i][1]})),protagonists:source.protagonists.map(p=>({...p,nombre:ENGLISH_PEOPLE[p.id]?.name||p.nombre,summary:ENGLISH_PEOPLE[p.id]?.summary||null,enPath:people.find(x=>x.id===p.id)?.path||null})),translated:true});}
const catalogue={people:people.map(({id,nombre,path,summary})=>({id,nombre,path,summary})),stories:stories.map(({id,nombre,path,description,period})=>({id,nombre,path,description,period}))};
const pages=[{path:'/en/',nombre:'A family. A story. A year.',type:'home',description:'Explore European families, stories and historical connections.',...catalogue},{path:'/en/stories',nombre:'Stories in English',type:'stories',description:'Two complete stories translated chapter by chapter.',...catalogue},{path:'/en/people',nombre:'Selected profiles in English',type:'people',description:'Translated short profiles with access to the original records and sources.',...catalogue},{path:'/en/methodology',nombre:'Sources and methodology',type:'methodology',description:'How to read the dates, relationships and coverage of the Atlas.',sections:ENGLISH_METHOD},...people.map(p=>({...p,type:'person',description:p.summary})),...stories.flatMap(s=>[{...s,type:'story'},...s.pasos.map((p,i)=>({...s,type:'story',path:`${s.path}/chapter/${i+1}`,storyPath:s.path,chapter:i+1,nombre:p.titulo,description:p.texto.slice(0,155)}))])];
for(const data of pages){const route=englishRoute(data.path);const out={...data,slug:route.slug,chapter:route.chapter,esPath:translatedEquivalent(data.path,'es'),nombre:data.nombre};const file=`public/english-meta/${route.slug}${route.chapter?`/capitulo/${route.chapter}`:''}.json`;await fs.mkdir(file.slice(0,file.lastIndexOf('/')),{recursive:true});await fs.writeFile(file,JSON.stringify(out));}
if(pages.length!==englishPaths().length)throw Error('Las rutas inglesas no coinciden con la generación');
console.log(`Edición inglesa: ${pages.length} páginas, ${stories.length} historias completas y ${people.length} fichas breves.`);
