const FMG='https://fmg.ac/Projects/MedLands/index.htm';
const BRIT='https://www.britannica.com/';
const RAH='https://historia-hispanica.rah.es/';
const MILAN='https://www.lombardiabeniculturali.it/istituzioni/schede/8000356/';
const MILAN_HISTORY='https://www.lombardiabeniculturali.it/istituzioni/storia/?unita=03.05';
const PARES_CARLOS='https://pares.cultura.gob.es/ParesBusquedas20/catalogo/autoridad/46080';
const PARES_JUANA='https://pares.cultura.gob.es/ParesBusquedas20/catalogo/autoridad/46503';
const PARES_CARLOS_II='https://pares.cultura.gob.es/ParesBusquedas20/catalogo/autoridad/46849';
const HABSBURG_FERDINAND_IV='https://www.habsburger.net/en/persons/habsburg/ferdinand-iv';
const SENLIS='https://ccfr.bnf.fr/portailccfr/ark:/16871/004a80306914';
const RIJKSMUSEUM_NETHERLANDS='https://www.rijksmuseum.nl/en/collection/object/Allegory-on-the-Abdication-of-Emperor-Charles-v-in-Brussels--2cb744f2469fe62413bb6aab920d4e03';
const FRISIA_1524='https://www.dbnl.org/tekst/_gid001193001_01/_gid001193001_01_0055.php';
const UTRECHT_1528='https://www.archieven.nl/nl/zoeken?miadt=39&miaet=14&micode=BIBLIO_BOEK&minr=40665930&mivast=0&miview=ldt&mizig=307';
const OVERIJSSEL_1528='https://www.canonvannederland.nl/nl/overijssel/overijssel/oversticht';
const DRENTE_1536='https://www.canonvannederland.nl/nl/page/99041/kinkhorst';
const GRONINGA_1536='https://www.canonvannederland.nl/nl/groningen/groningen/habsburgs-gezag';
const GUELDRES_1543='https://www.rijksmuseum.nl/en/collection/node/Gelderse%2Boorlogen--e8ad752027a7c20d0e2cbf9568e18ca8';
const BNF_MARGARITA='https://catalogue.bnf.fr/ark:/12148/cb16161030k';
const BIBLISSIMA_LUIS='https://portail.biblissima.fr/ark:/43093/pdata72015d9dbbe4171cc1369eb56e627ee49a8ef9de';
const MET_BORGONA='https://www.metmuseum.org/fr/essays/burgundian-netherlands-court-life-and-patronage';
const BIBLISSIMA_FELIPE='https://portail.biblissima.fr/fr/ark:/43093/pdata71295e340f36a2c35285ffc09fff863e1dd66edb';
const CANON_JACOBA='https://www.canonvannederland.nl/nl/page/439262/jacoba-van-beieren';
const WALLONIE_NAMUR='https://connaitrelawallonie.wallonie.be/histoire/timeline/13-mars-1429-entree-de-philippe-de-bourgogne-namur';
const LUXEMBURGO_1443='https://luxembourg.public.lu/en/society-and-culture/history/helm-holy-roman-empire.html';
const CAMBRIDGE_PONTHIEU='https://www.cambridge.org/core/books/abs/war-and-government-in-the-french-provinces/return-to-allegiance-picardy-and-the-francoburgundian-wars-147093/C99410404ADED4EF0ABA86A39803BC3C';
const BNF_AUXERRE='https://gallica.bnf.fr/ark:/12148/bpt6k947101.pdf';
const BIBLISSIMA_NEVERS='https://portail.biblissima.fr/fr/ark:/43093/pdata8ddd5493a80916491d6eb6a23bd52ecc916100d4';
const SIGILLA_JUAN='https://sigilla.irht.cnrs.fr/A.php/41813';
const SIGILLA_FELIPE_NEVERS='https://sigilla.irht.cnrs.fr/44802';
const ULIEGE_RETHEL='https://orbi.uliege.be/bitstream/2268/247248/1/Trulla%20et%20Cartae.pdf';
const acceso=(persona,territorio,desde,motivos,explicacion,fuentes=[FMG,BRIT],clase='reinado')=>({persona,territorio,desde,clase,motivos,explicacion,fuentes});

// Cada explicación se ancla a un mandato real de la base, nunca al título resumen.
export const ACCESOS_CORONAS = [
 acceso('MARGFRAFLA','Condado de Borgoña',1361,['herencia'],'El condado imperial y Artois pasaron a Margarita de Francia antes de la generación de Luis de Male; no eran partes del ducado francés.',[BIBLISSIMA_LUIS],'condado'),
 acceso('LUIS2FLA','Condado de Borgoña',1382,['herencia'],'Luis de Male heredó de su madre el Franco Condado y Artois en 1382, dos años antes de su propia muerte.',[BIBLISSIMA_LUIS],'condado'),
 ...['Nevers','Rethel'].map(t=>acceso('LUIS2FLA',t,1346,['herencia'],'Luis de Male heredó este condado junto a Flandes; en 1384 pasó a su hija Margarita III.',[BIBLISSIMA_LUIS],'condado')),
 ...['Flandes','Artois','Condado de Borgoña','Nevers','Rethel'].map(t=>acceso('MARGFLAN',t,1384,['herencia'],'Margarita III heredó los cinco condados de Luis de Male. Nevers y Rethel fueron entregados a hijos menores como apanages; el título de Margarita no equivale al gobierno posterior de cada uno.',[BNF_MARGARITA,MET_BORGONA],'condado')),
 acceso('FEL2BORG','Borgoña',1363,['nombramiento'],'Juan II de Francia concedió el ducado a su hijo Felipe; la herencia flamenca llegaría por Margarita III en 1384.',[MET_BORGONA],'ducado'),
 acceso('FEL2BORG','Flandes',1384,['matrimonio','herencia'],'Felipe gobernó por los derechos hereditarios de Margarita III. Los condados seguían siendo títulos separados del ducado de Dijon.',[BNF_MARGARITA,MET_BORGONA],'condado'),
 ...['Flandes','Artois','Condado de Borgoña'].map(t=>acceso('JUAN1BORG',t,1404,['herencia'],'Juan sucedió a su padre en 1404 como conde; Margarita III conservó sus derechos propios hasta morir en 1405. Nevers y Rethel siguieron la rama de sus hermanos.',[SIGILLA_JUAN,BNF_MARGARITA],'condado')),
 acceso('JUAN1BORG','Nevers',1384,['herencia'],'Juan recibió Nevers como apanage siendo joven y lo cedió a su hermano Felipe al heredar el ducado en 1404.',[SIGILLA_JUAN],'condado'),
 acceso('ANTONBRAB','Rethel',1393,['acuerdo'],'Margarita III y Felipe el Atrevido cedieron Rethel a su hijo Antonio en 1393; pasó a Felipe de Nevers en 1406.',[ULIEGE_RETHEL],'condado'),
 acceso('PHIL2NEVERS','Nevers',1404,['herencia'],'Al acceder Juan sin Miedo al ducado en 1404, su hermano Felipe recibió Nevers; Rethel llegaría en 1406.',[SIGILLA_FELIPE_NEVERS],'condado'),
 acceso('JUAN3NAMUR','Namur',1418,['herencia'],'Juan III conservó Namur hasta su muerte. Vendió en 1421 el derecho a sucederle a Felipe el Bueno, que tomó posesión en 1429.',[WALLONIE_NAMUR],'condado'),
 acceso('FEL3BORG','Namur',1429,['acuerdo','herencia'],'La compra del derecho fue de 1421; Felipe tomó posesión del condado tras la muerte de Juan III en 1429.',[WALLONIE_NAMUR],'condado'),
 ...['Brabante','Limburgo'].map(t=>acceso('FEL3BORG',t,1430,['herencia'],'La muerte sin heredero de Felipe de Saint-Pol incorporó el ducado a la línea principal de los Valois de Borgoña.',[BIBLISSIMA_FELIPE],'ducado')),
 ...['Holanda','Henao','Zelanda'].map(t=>acceso('FEL3BORG',t,1433,['acuerdo'],'El acuerdo de Delft de 1428 precedió a la renuncia definitiva de Jacoba en 1433. El gobierno previo se registra como regencia.',[CANON_JACOBA,BIBLISSIMA_FELIPE],'condado')),
 acceso('FEL3BORG','Luxemburgo',1443,['acuerdo','conquista'],'Isabel de Görlitz vendió sus derechos en 1441; Felipe tomó la ciudad en 1443. La dignidad ducal se fecha a veces en 1444.',[LUXEMBURGO_1443,BIBLISSIMA_FELIPE],'ducado'),
 acceso('FEL3BORG','Auxerre',1435,['acuerdo'],'El tratado de Arrás cedió este condado a Felipe. Era distinto del ducado de Borgoña.',[BNF_AUXERRE],'condado'),
 acceso('FEL3BORG','Ponthieu',1435,['acuerdo'],'El tratado de Arrás cedió este condado a Felipe; el polígono regional no representa cada ciudad del Somme.',[CAMBRIDGE_PONTHIEU],'condado'),
 ...['Nevers','Rethel'].map(t=>acceso('CAR1NEVERS',t,1415,['herencia'],'Carlos heredó el condado de su padre Felipe de Nevers. Esta línea familiar era distinta de los duques que gobernaron Dijon y Flandes.',[BIBLISSIMA_NEVERS],'condado')),
 ...['Nevers','Rethel'].map(t=>acceso('JUAN2NEVERS',t,1464,['herencia'],'Juan sucedió a su hermano Carlos, sin que el condado se reuniera por ello con los territorios de Carlos el Temerario.',[BIBLISSIMA_NEVERS],'condado')),
 acceso('FERN3','Castilla',1217,['herencia','abdicación'],'Berenguela heredó tras la muerte de Enrique I y cedió la corona a su hijo Fernando. La herencia castellana procedía de su madre.',[RAH]),
 acceso('FERN3','León',1230,['herencia','acuerdo'],'A la muerte de Alfonso IX, Fernando hizo valer su derecho frente a sus medio hermanas Sancha y Dulce. El acuerdo con ellas permitió reunir las coronas de León y Castilla.',[RAH]),
 acceso('MAGNUS4SUE','Noruega',1319,['herencia'],'Heredó a su abuelo materno Haakon V a través de Ingeborg de Noruega. La minoría del rey exigió un gobierno de regencia.'),
 acceso('MAGNUS4SUE','Suecia',1319,['elección'],'La elección del hijo de Erik Magnusson dio una solución sueca a la crisis que siguió al derrocamiento de Birger. Coincidió con la herencia noruega, pero tuvo un fundamento distinto.'),
 acceso('OLAF2NORD','Dinamarca',1376,['elección'],'Los daneses eligieron al nieto de Valdemar IV, hijo de Margarita y de Haakon VI. Su madre dirigió la regencia durante la minoría.'),
 acceso('OLAF2NORD','Noruega',1380,['herencia'],'La muerte de Haakon VI transmitió a Olaf la corona noruega. Dinamarca y Noruega quedaron vinculadas por un rey menor de edad.'),
 acceso('MARGARITA1NORD','Dinamarca',1387,['elección'],'Tras la muerte de su hijo Olaf, los poderes del reino reconocieron a Margarita como señora y gobernante. Su autoridad no dependía ya de la regencia materna.'),
 acceso('MARGARITA1NORD','Noruega',1388,['elección'],'El reconocimiento noruego tras la muerte de Olaf sostuvo el gobierno de Margarita y la posterior elección de su pariente Erik de Pomerania.'),
 acceso('MARGARITA1NORD','Suecia',1389,['acuerdo','conquista'],'La oposición sueca a Alberto de Mecklemburgo aceptó a Margarita. La derrota y captura de Alberto en 1389 hicieron efectivo ese cambio de poder.'),
 acceso('ERICOPOMERANIA','Noruega',1389,['elección'],'Margarita promovió a su sobrino nieto como heredero y rey. La continuidad familiar pasaba por Ingeborg, hermana de Margarita, y María de Mecklemburgo.'),
 ...['Dinamarca','Suecia'].map(t=>acceso('ERICOPOMERANIA',t,1396,['elección'],'Fue reconocido rey antes de la coronación conjunta de Kalmar en 1397. Margarita conservó la dirección política hasta su muerte en 1412; coronación y comienzo del mandato no coinciden.')),
 ...[['Dinamarca',1440],['Suecia',1441],['Noruega',1442]].map(([t,a])=>acceso('CRISTOBALBAVSUE',t,a,['elección'],'La deposición de Erik abrió elecciones distintas en cada reino. Cristóbal, sobrino de Erik por Catalina de Pomerania, reunió las tres coronas de forma escalonada.')),
 acceso('CRISTIAN1NORD','Dinamarca',1448,['elección'],'La muerte sin descendencia de Cristóbal abrió una elección. Cristian de Oldemburgo fue aceptado y se casó después con la reina viuda Dorotea de Brandeburgo.'),
 acceso('CRISTIAN1NORD','Noruega',1450,['elección','acuerdo'],'La elección noruega y el acuerdo que apartó a Carlos Knutsson afianzaron la unión con Dinamarca. Suecia mantuvo entonces otro monarca.'),
 acceso('CRISTIAN1NORD','Suecia',1457,['elección','deposición'],'La expulsión de Carlos Knutsson permitió la elección de Cristian. La unión de los tres reinos volvió a romperse en 1464.'),
 acceso('JUAN2NORD','Suecia',1497,['conquista','acuerdo'],'La derrota de Sten Sture el Viejo permitió a Juan recibir la corona sueca. Su autoridad terminó con la nueva rebelión de 1501.'),
 acceso('CRISTIAN2DIN','Suecia',1520,['conquista'],'La campaña contra Sten Sture el Joven y la capitulación de Estocolmo permitieron su coronación. La represión posterior alimentó la rebelión que acabaría con la unión sueca.'),
 acceso('FERN2ARAG','Aragón',1479,['herencia'],'Sucedió a su padre Juan II. Su participación en el gobierno castellano procedía del matrimonio con Isabel y no convertía las dos coronas en un reino único.',[RAH]),
 acceso('FERN2ARAG','Castilla',1474,['matrimonio','acuerdo'],'Gobernó junto a Isabel como su esposo, con atribuciones delimitadas por acuerdos políticos. El derecho hereditario castellano pertenecía a Isabel.',[RAH]),
 acceso('CARLOS5','Castilla',1516,['herencia'],'Tras la muerte de Fernando, Carlos asumió el título regio junto a su madre Juana, que conservó la condición de reina. La proclamación de Carlos no fue una abdicación de Juana.',[RAH]),
 acceso('CARLOS5','Aragón',1516,['herencia'],'La muerte de Fernando abrió la sucesión aragonesa. El reconocimiento y los juramentos en los distintos territorios se desarrollaron posteriormente; 1516 identifica el acceso registrado.',[RAH]),
 acceso('CARLOS5','Cerdeña',1516,['herencia'],'El título de rey de Cerdeña acompañó la herencia aragonesa, junto a Juana I. El inicio anual se deriva de la sucesión general; no acredita una ceremonia local específica.',[PARES_CARLOS]),
 acceso('JUANA1CAST','Cerdeña',1516,['herencia'],'PARES enumera a Juana reina de Cerdeña junto a Carlos I entre 1516 y 1555. La titularidad no indica ejercicio personal del gobierno.',[PARES_JUANA]),
 acceso('CARLOS5','Milán',1535,['herencia'],'La muerte de Francesco II Sforza devolvió el feudo imperial a Carlos V, que lo mantuvo bajo control directo. La investidura del hijo Felipe y la posesión de 1556 fueron fases posteriores.',[MILAN],'ducado'),
 acceso('FEL2ESP','Milán',1546,['nombramiento'],'La ficha histórica lombarda fecha la investidura de Felipe en 1546; otra cronología institucional sitúa el título en 1540. El control directo imperial continuó hasta 1556: este acceso representa una dignidad disputada en su fecha, no posesión efectiva.',[MILAN],'ducado'),
 acceso('FEL2ESP','Milán',1556,['abdicación'],'La narración histórica lombarda sitúa la toma de posesión de Felipe tras la abdicación de Carlos V en 1556.',[MILAN_HISTORY],'ducado'),
 acceso('FERN4BOH','Bohemia',1646,['nombramiento'],'Coronado rey en vida de su padre Fernando III. El título no supone una sucesión imperial ni una autoridad exclusiva sobre todos los dominios paternos.',[HABSBURG_FERDINAND_IV]),
 acceso('FERN4BOH','Hungría',1647,['nombramiento'],'Coronado rey en vida de Fernando III. Su padre siguió reinando; se registra como corregencia, no como sucesión exclusiva.',[HABSBURG_FERDINAND_IV]),
 acceso('FERN4BOH','Alemania',1653,['elección'],'Elegido rey de Romanos y heredero designado del emperador Fernando III; murió antes que él y nunca llegó a emperador.',[HABSBURG_FERDINAND_IV]),
 acceso('CARLOS5','Sacro Imperio',1519,['elección'],'La elección de 1519 abrió su etapa imperial; fue coronado rey de Romanos en 1520 y emperador por el papa en 1530. El intervalo de la base parte de la elección, no de la coronación papal.',[RAH], 'imperio'),
 acceso('FEL2ESP','Portugal',1580,['herencia','conquista'],'La muerte del cardenal Enrique abrió una disputa. Felipe alegó su descendencia de Manuel I por Isabel de Portugal y se impuso militarmente; las Cortes de Tomar lo reconocieron en 1581.',[RAH]),
 acceso('JACOBO1ING','Inglaterra',1603,['herencia'],'Sucedió a Isabel I por su ascendencia Tudor. Ya reinaba en Escocia: compartieron soberano, pero conservaron parlamentos y ordenamientos separados.',[BRIT]),
 acceso('SEGIS3VASA','Suecia',1592,['herencia'],'Heredó a su padre Juan III cuando ya era rey electo de Polonia. El conflicto con su tío Carlos y la oposición sueca terminó con su deposición en 1599.',[BRIT]),
 ...[['Flandes','condado'],['Condado de Borgoña','condado'],['Brabante','ducado'],['Limburgo','ducado'],['Holanda','condado'],['Henao','condado'],['Zelanda','condado']].map(([t,c])=>acceso('CARLOS5',t,1506,['herencia'],'La muerte de Felipe el Hermoso transmitió a Carlos estos patrimonios de origen borgoñón. Durante su minoría hubo regencias: heredar un título no significa que el niño dirigiera personalmente el gobierno.',[RAH],c)),
 ...[['Namur','condado'],['Luxemburgo','ducado']].map(([t,c])=>acceso('CARLOS5',t,1506,['herencia'],'Carlos heredó este territorio del patrimonio borgoñón de Felipe I; el año de acceso sigue la sucesión paterna. Su representación cartográfica es aproximada.',[RIJKSMUSEUM_NETHERLANDS],c)),
 acceso('CARLOS5','Frisia',1524,['acuerdo'],'Carlos había adquirido derechos en 1515, pero el acuerdo general con los frisones quedó cerrado en 1524.',[FRISIA_1524],'señorío'),
 acceso('CARLOS5','Utrecht',1528,['acuerdo'],'El obispo transfirió a Carlos el poder temporal en 1528. Utrecht permanece sin color porque el SVG carece de un polígono propio.',[UTRECHT_1528],'señorío'),
 acceso('CARLOS5','Overijssel',1528,['acuerdo'],'Overijssel reconoció a Carlos como señor en 1528, dentro de la separación del antiguo poder temporal episcopal.',[OVERIJSSEL_1528],'señorío'),
 acceso('CARLOS5','Drente',1536,['acuerdo'],'Drente pasó a la autoridad de Carlos en 1536; la geometría es una aproximación regional.',[DRENTE_1536],'señorío'),
 acceso('CARLOS5','Groninga',1536,['acuerdo'],'La ciudad y los Ommelanden se sometieron a Carlos en 1536; el SVG solo permite aproximar los Ommelanden.',[GRONINGA_1536],'señorío'),
 acceso('CARLOS5','Güeldres',1543,['acuerdo','conquista'],'El tratado de Venlo de 1543 cerró las guerras de Güeldres y confirmó la autoridad de Carlos sobre el ducado.',[GUELDRES_1543],'ducado'),
 acceso('FEL1CAST','Condado de Borgoña',1493,['acuerdo','herencia'],'El tratado de Senlis restituyó el Franco Condado a la casa de Austria. Felipe heredó esos derechos; no se trata del ducado francés.',[SENLIS],'condado'),
 acceso('FEL1CAST','Artois',1493,['acuerdo','herencia'],'Artois fue otro de los condados restituidos por Senlis a la casa de Austria. El comienzo personal se infiere de esa sucesión.',[SENLIS],'condado'),
 acceso('CARLOS5','Artois',1506,['herencia'],'Carlos recibió Artois dentro de la herencia de Felipe I. Senlis documenta la restitución anterior a la casa de Austria; el año de acceso procede de la sucesión paterna.',[SENLIS],'condado'),
 acceso('FEL2ESP','Artois',1555,['herencia'],'Felipe recibió Artois en el relevo de los Países Bajos borgoñones. El tratado de Senlis documenta la restitución de 1493, no el día exacto del relevo de 1555.',[SENLIS],'condado'),
 acceso('CARLOS5','Borgoña',1506,['herencia'],'Carlos conservó el título ducal heredado de Felipe, pero el ducado estaba bajo control francés. Esta pretensión no se cuenta como gobierno efectivo; el Condado de Borgoña tenía una situación distinta.',[RAH],'ducado'),
 ...['León','Nápoles','Trinacria'].map(t=>acceso('CARLOS5',t,1516,['herencia'],'La muerte de Fernando abrió esta sucesión dentro del patrimonio dinástico hispánico. Cada territorio mantuvo su título y sus instituciones; los reconocimientos y juramentos no ocurrieron todos a la vez.',[RAH])),
 ...[['Milán','ducado'],['Nápoles','reinado'],['Trinacria','reinado'],['Cerdeña','reinado']].map(([t,c])=>acceso('CARLOS2ESP',t,1665,['herencia'],'Carlos II heredó este dominio siendo menor de edad. PARES enumera sus títulos italianos; Mariana de Austria ejerció la regencia durante su minoría.',[PARES_CARLOS_II],c)),
 acceso('CARLOS5','Navarra',1516,['herencia'],'Continuó la soberanía de los Austrias sobre la Alta Navarra conquistada por Fernando. Los Albret conservaron derechos y gobierno al norte de los Pirineos: el mandato no representa una sucesión aceptada sobre todo el reino histórico.',[RAH]),
 acceso('CARLOS5','Austria',1519,['herencia'],'La muerte de Maximiliano I transmitió los territorios hereditarios austríacos a Carlos. Los acuerdos con su hermano Fernando iniciaron su cesión a la rama austríaca; esta herencia era distinta de la elección imperial.',[RAH],'archiducado'),
 acceso('CARLOS5','Alemania',1519,['elección'],'Los electores eligieron a Carlos rey de Romanos en 1519. La coronación de Aquisgrán fue en 1520. Este título y el imperial forman parte de una misma estructura política y no describen dos Estados independientes.',[RAH]),
 ...[['Dinamarca',1481],['Noruega',1483]].map(([t,a])=>acceso('JUAN2NORD',t,a,['herencia','elección'],'Sucedió a su padre Cristian I mediante los reconocimientos y acuerdos propios de cada reino. La herencia dinástica no eliminó la intervención de los consejos.')),
 ...['Dinamarca','Noruega'].map(t=>acceso('CRISTIAN2DIN',t,1513,['herencia','elección'],'La muerte de su padre Juan abrió la sucesión. El reconocimiento en los reinos vinculados sostuvo su acceso; Suecia permaneció fuera de su gobierno hasta la conquista de 1520.')),
 acceso('MARGARITA1NORD','Dinamarca',1376,['regencia'],'Gobernó durante la minoría de su hijo Olaf. Esta regencia es una función distinta de la autoridad que recibió por derecho propio tras la muerte de él.',[FMG,BRIT],'regencia'),
 acceso('MARGARITA1NORD','Noruega',1380,['regencia'],'La muerte de Haakon VI dejó la corona a Olaf, todavía menor. Margarita dirigió la regencia noruega además de la danesa.',[FMG,BRIT],'regencia'),
 acceso('JACOBO1ING','Escocia',1567,['herencia','abdicación'],'La abdicación forzada de María Estuardo dejó la corona escocesa a Jacobo, aún niño. Distintos regentes ejercieron el gobierno durante su minoría.',[BRIT]),
 acceso('JACOBO1ING','Irlanda',1603,['herencia'],'El título irlandés acompañó a la sucesión de Isabel I. La incorporación a una misma monarquía no elimina la historia propia de Irlanda ni las desigualdades de poder entre sus territorios.',[BRIT]),
 acceso('SEGIS3VASA','Polonia',1587,['elección'],'Fue elegido en una sucesión disputada. Su ascendencia Jagellón por Catalina favoreció su candidatura, pero no convirtió la corona electiva en una herencia automática.',[BRIT]),
 acceso('SEGIS3VASA','Lituania',1587,['elección'],'Su elección dentro de la monarquía polaco-lituana llevó también el título de gran duque. Polonia y Lituania conservaban instituciones propias dentro del marco de la unión de Lublin.',[BRIT],'gran_ducado'),

];

// Un marco de unión puede contener rupturas. Sus límites no afirman un gobierno continuo.
export const UNIONES_CORONAS = [
 {id:'herencia-borgonona',titulo:'La herencia borgoñona, feudo a feudo',territorios:['Borgoña','Flandes','Artois','Condado de Borgoña','Nevers','Rethel','Auxerre','Ponthieu','Brabante','Limburgo','Holanda','Henao','Zelanda','Namur','Luxemburgo'],desde:1363,hasta:1555,
 resumen:'Matrimonio, sucesión, compra, renuncia y conquista reunieron feudos jurídicamente distintos. El mapa debe seguir cada gobierno efectivo, no pintar todos los dominios desde la investidura ducal.',
 instituciones:'El ducado de Dijon era un feudo francés; el Franco Condado, un feudo imperial. Nevers y Rethel siguieron una rama menor. Tras 1477, Francia tomó el ducado; las reclamaciones de María y sus herederos no equivalen a posesión.',
 etapas:[{anio:1363,titulo:'El ducado de Felipe el Atrevido',texto:'El ducado francés estaba centrado en Dijon. Los condados del norte y el Franco Condado llegarían por Margarita III.',personas:['FEL2BORG','MARGFRAFLA','LUIS2FLA']},{anio:1384,titulo:'La herencia de Margarita III',texto:'Flandes, Artois y el Franco Condado se sumaron por derecho hereditario de Margarita; sus hijos recibieron Nevers y Rethel como apanages antes de 1405.',personas:['LUIS2FLA','MARGFLAN','FEL2BORG','JUAN1BORG','ANTONBRAB','PHIL2NEVERS']},{anio:1429,titulo:'Namur y Brabante',texto:'Felipe el Bueno tomó Namur en 1429 y heredó Brabante y Limburgo en 1430.',personas:['JUAN3NAMUR','PHILSTPOL','FEL3BORG']},{anio:1433,titulo:'Los condados de Jacoba',texto:'Después de la regencia acordada en Delft, Jacoba renunció en 1433 a Holanda, Henao y Zelanda.',personas:['JACOBA','FEL3BORG']},{anio:1443,titulo:'Luxemburgo',texto:'La compra de derechos de 1441 y la toma de la ciudad en 1443 completaron otra incorporación gradual.',personas:['ISABELGORLITZ','FEL3BORG']},{anio:1477,titulo:'Ruptura de la herencia',texto:'Muerto Carlos el Temerario, María retuvo los Países Bajos; Francia tomó el ducado y disputó Artois y el Franco Condado.',personas:['CAR1BORG','MARIABORG','MAXIM1']},{anio:1493,titulo:'Senlis y los Habsburgo',texto:'Artois y el Franco Condado volvieron a la casa de Austria; Felipe I y Carlos V los transmitieron con los Países Bajos.',personas:['FEL1CAST','CARLOS5']}],fuentes:[BNF_MARGARITA,MET_BORGONA,BIBLISSIMA_FELIPE,CANON_JACOBA,LUXEMBURGO_1443,SIGILLA_JUAN,ULIEGE_RETHEL]},
 {id:'magnus-1319',titulo:'Dos herencias, un rey niño',territorios:['Noruega','Suecia'],desde:1319,hasta:1355,
 resumen:'Magnus Eriksson reunió Noruega por herencia y Suecia por elección. La conexión pasó por su madre Ingeborg y su padre Erik Magnusson.',
 instituciones:'Cada reino mantuvo su consejo y sus leyes. La unión personal no convirtió Noruega en una provincia sueca.',
 etapas:[{anio:1319,titulo:'Herencia y elección',texto:'La muerte de Haakon V y la elección sueca coincidieron en Magnus, todavía menor.',personas:['HAAKON5NOR','INGEBORGNORUEGA','MAGNUS4SUE']},{anio:1355,titulo:'Dos reyes',texto:'Haakon VI asumió el gobierno noruego mientras su padre siguió reinando en Suecia. Los vínculos familiares sobrevivieron a la separación.',personas:['MAGNUS4SUE','HAAKON6NOR']}],fuentes:[FMG,BRIT]},
 {id:'dinamarca-noruega',titulo:'Dinamarca y Noruega',territorios:['Dinamarca','Noruega'],desde:1380,hasta:1814,
 resumen:'La herencia de Olaf vinculó dos coronas que, con crisis y cambios dinásticos, permanecieron asociadas durante siglos.',
 instituciones:'Noruega conservó una identidad jurídica propia. Su posición se subordinó más a Dinamarca con la reorganización de 1536–1537; unión personal y monarquía compuesta no describen exactamente la misma fase.',
 etapas:[{anio:1380,titulo:'La herencia de Olaf',texto:'Olaf heredó Noruega de su padre. Su madre Margarita gobernó durante la minoría.',personas:['OLAF2NORD','HAAKON6NOR','MARGARITA1NORD']},{anio:1450,titulo:'La unión bajo Oldemburgo',texto:'Cristian I consolidó el vínculo tras la competencia con Carlos Knutsson.',personas:['CRISTIAN1NORD','CARLOS8SUE']},{anio:1537,titulo:'Reforma y reorganización',texto:'La imposición de la Reforma reforzó el control de la monarquía danesa sobre Noruega.',personas:['CHRISTIAN3DEN']},{anio:1814,titulo:'Separación',texto:'El tratado de Kiel quebró la unión. Noruega aprobó una constitución y, tras un conflicto con Suecia, entró en otra unión conservándola con modificaciones.',personas:['FRED6DEN','CARLOS13SUE']}],fuentes:[FMG,BRIT]},
 {id:'kalmar',titulo:'Kalmar: una unión disputada',territorios:['Dinamarca','Noruega','Suecia'],desde:1397,hasta:1523,
 resumen:'La coronación de Erik en Kalmar expresó el proyecto de un monarca común. Suecia pasó repetidamente entre reyes de la unión, reyes propios y regencias.',
 instituciones:'Los tres reinos conservaron leyes y consejos propios. Kalmar no fue un Estado unitario ni una sucesión ininterrumpida de reyes comunes.',
 etapas:[{anio:1397,titulo:'Coronación común',texto:'Erik fue coronado en Kalmar. Margarita continuó ejerciendo una autoridad decisiva.',personas:['ERICOPOMERANIA','MARGARITA1NORD']},{anio:1434,titulo:'Rebelión sueca',texto:'La revuelta contra Erik abrió una fase de regencias, restauraciones y deposiciones.',personas:['ERICOPOMERANIA','CARLOS8SUE']},{anio:1442,titulo:'Tres elecciones reunidas',texto:'Cristóbal de Baviera completó su acceso a los tres reinos.',personas:['CRISTOBALBAVSUE']},{anio:1471,titulo:'La autonomía bajo los Sture',texto:'La victoria de Sten Sture el Viejo en Brunkeberg afianzó el gobierno sueco frente a Cristian I.',personas:['ESTENSTUREVIEJO','CRISTIAN1NORD']},{anio:1520,titulo:'Conquista y represión',texto:'Cristian II tomó Estocolmo. Las ejecuciones agravaron la oposición a su autoridad.',personas:['CRISTIAN2DIN','CHRISTINAGYLLEN']},{anio:1523,titulo:'La elección de Gustavo',texto:'Gustavo Vasa fue elegido rey de Suecia. Dinamarca y Noruega siguieron vinculadas.',personas:['GUSTAV1VASA','FRED1DEN']}],fuentes:[FMG,BRIT]},
 {id:'castilla-leon',titulo:'Castilla y León desde 1230',territorios:['Castilla','León','Corona de Castilla'],desde:1230,hasta:null,
 resumen:'Fernando III reunió dos herencias. La continuidad de un monarca común no borró de inmediato las identidades y tradiciones jurídicas de los reinos.',
 instituciones:'La Corona de Castilla fue una estructura compuesta en evolución. Castilla, León y España no son tres reinos equivalentes ni intercambiables en los filtros.',
 etapas:[{anio:1217,titulo:'La corona castellana',texto:'Berenguela transmitió Castilla a Fernando.',personas:['FERN3']},{anio:1230,titulo:'El acuerdo leonés',texto:'La sucesión de Alfonso IX y el acuerdo con las medio hermanas de Fernando hicieron duradera la unión.',personas:['FERN3']}],fuentes:[RAH]},
 {id:'coronas-ibericas',titulo:'Castilla y Aragón: una monarquía compuesta',territorios:['Castilla','León','Aragón','Corona de Castilla','Corona de Aragón','España'],desde:1479,hasta:null,
 resumen:'Isabel y Fernando vincularon sus coronas mediante el matrimonio y el gobierno compartido. Sus herederos acumularon derechos de procedencias distintas.',
 instituciones:'Las coronas conservaron instituciones, fiscalidad y leyes propias. La muerte de Isabel en 1504 separó sus trayectorias sucesorias antes del acceso de Carlos; los decretos de Nueva Planta transformaron más tarde esa organización.',
 etapas:[{anio:1479,titulo:'Un matrimonio, dos coronas',texto:'Fernando heredó Aragón mientras gobernaba Castilla junto a Isabel.',personas:['FERN2ARAG','ISAB1CAST']},{anio:1504,titulo:'Muere Isabel',texto:'Juana heredó Castilla. Fernando conservó Aragón y volvió después a la regencia castellana.',personas:['JUANA1CAST','FERN2ARAG']},{anio:1516,titulo:'La acumulación de Carlos',texto:'Carlos asumió los títulos junto a Juana. Los reconocimientos en cada territorio no ocurrieron todos a la vez.',personas:['CARLOS5','JUANA1CAST']}],fuentes:[RAH]},
 {id:'portugal-1580',titulo:'Portugal en la monarquía de los Austrias',territorios:['Portugal','España'],desde:1580,hasta:1640,
 resumen:'Tres Felipes compartieron las coronas portuguesa e hispánicas tras la crisis sucesoria de 1580. La restauración portuguesa de 1640 rompió el gobierno común.',
 instituciones:'Portugal mantuvo leyes, moneda y administración propias. La separación efectiva de 1640 precedió al reconocimiento diplomático de 1668.',
 etapas:[{anio:1580,titulo:'Reclamación y conquista',texto:'Felipe II impuso su candidatura tras la muerte del cardenal Enrique.',personas:['FEL2ESP']},{anio:1581,titulo:'Cortes de Tomar',texto:'El reconocimiento portugués quedó acompañado de compromisos sobre las instituciones del reino.',personas:['FEL2ESP']},{anio:1640,titulo:'Restauración',texto:'La proclamación de Juan IV de Braganza abrió una guerra por la separación. Los títulos reclamados y el control del territorio dejaron de coincidir.',personas:[]}],fuentes:[RAH,BRIT]},
 {id:'coronas-britanicas',titulo:'Una corona compartida antes de Gran Bretaña',territorios:['Inglaterra','Escocia'],desde:1603,hasta:1707,
 resumen:'Jacobo VI de Escocia accedió a Inglaterra como Jacobo I. La unión dinástica precedió en más de un siglo a la unión parlamentaria.',
 instituciones:'Los dos reinos conservaron parlamentos y sistemas jurídicos. La crisis y el periodo republicano de 1649–1660 interrumpieron la monarquía; 1707 creó un marco político diferente.',
 etapas:[{anio:1603,titulo:'La sucesión Tudor',texto:'Jacobo sucedió a Isabel I sin fusionar las instituciones de ambos reinos.',personas:['JACOBO1ING']},{anio:1649,titulo:'Ruptura de la monarquía',texto:'La ejecución de Carlos I abrió el periodo republicano en Inglaterra; Escocia siguió inicialmente otra trayectoria hasta su sometimiento militar.',personas:[]},{anio:1660,titulo:'Restauración',texto:'La monarquía volvió a reunir ambos reinos bajo Carlos II.',personas:[]},{anio:1707,titulo:'Unión parlamentaria',texto:'Los actos de unión crearon el reino de Gran Bretaña; el sistema jurídico escocés mantuvo su identidad.',personas:[]}],fuentes:[BRIT]},
 {id:'suecia-noruega-1814',titulo:'Suecia y Noruega bajo una misma corona',territorios:['Suecia','Noruega'],desde:1814,hasta:1905,
 resumen:'La ruptura con Dinamarca dio paso, tras una guerra y un acuerdo constitucional, a la unión de Noruega con Suecia. Los dos reinos compartieron monarca, con una considerable autonomía noruega.',
 instituciones:'Noruega conservó su constitución, su parlamento y su administración. Las tensiones por la representación exterior y el equilibrio entre los reinos contribuyeron a la disolución de 1905.',
 etapas:[{anio:1814,titulo:'Guerra y acuerdo',texto:'Carlos XIII recibió la corona noruega después de la Convención de Moss y la revisión de la constitución de Noruega.',personas:['CARLOS13SUE','CARLOS14JUAN']},{anio:1818,titulo:'La casa de Bernadotte',texto:'Carlos Juan sucedió a Carlos XIII en los dos reinos. Su adopción y elección como heredero deben distinguirse de una filiación biológica.',personas:['CARLOS13SUE','CARLOS14JUAN']},{anio:1905,titulo:'Disolución de la unión',texto:'La separación pactada puso fin al monarca común. Noruega eligió una nueva casa reinante.',personas:[]}],fuentes:[BRIT]},

];
