import React,{useRef,useState} from 'react';
import {Download,X} from 'lucide-react';
import './connections.css';
export default function TreeExport({getSelection}){
 const dialog=useRef(null),[scope,setScope]=useState('selection'),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[count,setCount]=useState(0);
 function open(){setStatus('');setScope('selection');setCount(getSelection('selection').people.length);dialog.current.showModal();}
 async function save(format){setBusy(true);setStatus('');try{const {treeSvg,svgToPng,downloadBlob}=await import('./treeExport.js');const scene=treeSvg(getSelection(scope));const blob=format==='svg'?new Blob([scene.svg],{type:'image/svg+xml;charset=utf-8'}):await svgToPng(scene);downloadBlob(blob,`el-arbol-de-europa.${format}`);setStatus(`Archivo ${format.toUpperCase()} preparado.`);}catch(error){setStatus(error.message);}finally{setBusy(false);}}
 return <><button className="nav-btn" type="button" onClick={open}><Download size={13}/> Exportar</button><dialog className="tree-export-dialog" ref={dialog} aria-labelledby="tree-export-title"><button className="tree-export-close" aria-label="Cerrar exportación" onClick={()=>dialog.current.close()}><X size={18}/></button><h2 id="tree-export-title">Exportar el árbol</h2><p>Conserva los nombres completos, las fechas y los vínculos de tu selección.</p><label>Contenido<select value={scope} onChange={e=>{setScope(e.target.value);setCount(getSelection(e.target.value).people.length);setStatus('');}}><option value="selection">Comparación, foco o familia de la persona seleccionada</option><option value="visible">Todas las personas de la vista actual</option></select></label><p>{count} personas · Los archivos incluyen una leyenda y la referencia al proyecto.</p><div className="tree-export-actions"><button className="nav-btn" disabled={busy||!count} onClick={()=>save('svg')}>Descargar SVG</button><button className="nav-btn" disabled={busy||!count} onClick={()=>save('png')}>Descargar PNG</button></div><p role="status">{busy?'Preparando archivo…':status}</p></dialog></>;
}
