import {ADRIATICO_REFS as R} from '../sources-adriatico-v214.js';
const cambio=(territorio,anterior,a,siguiente,b,motivos,explicacion,fuentes,extra={})=>({id:`${territorio}-${siguiente}-${b}`,territorio,predecesor:{persona:anterior,desde:a},sucesor:{persona:siguiente,desde:b},motivos,explicacion,fuentes,...extra});
export const RELEVOS_ADRIATICO = [
 cambio('Bosnia','STEPHEN2BOS',1322,'TVRTKO1BOS',1353,['herencia'],'Tvrtko era hijo de Vladislav, hermano del ban fallecido. La sucesión pasó al sobrino; la hija de Esteban II, Isabel, se había vinculado a la monarquía húngara.',[R.step2,R.tvrtko]),
 cambio('Bosnia','DABISABOS',1391,'JELENAGRUBABOS',1395,['elección','acuerdo'],'Los magnates reconocieron a Jelena, viuda de Dabiša. El acceso fue una decisión política, no una herencia de padre a hijo.',[R.gruba]),
 cambio('Bosnia','STEPHENTHOMASBOS',1443,'STEPHENTOMASEVICBOS',1461,['herencia'],'El hijo de Esteban Tomás y Vojača sucedió a su padre. Catalina Kosača fue su madrastra. El nuevo rey había gobernado brevemente Serbia por su enlace con Jelena Branković.',[R.lastbos]),
 cambio('Serbia','DJURADJBRANKOVIC',1444,'LAZARBRANKOVIC',1456,['herencia'],'Lazar, hijo de Đurađ e Irene Cantacuzena, sucedió a su padre después del último gobierno restaurado de este. La interrupción de 1439–1444 se registra por separado.',[R.djuradj]),
 cambio('Croacia','NIKOLA7ZRIN',1647,'PETAR4ZRIN',1665,['nombramiento'],'Petar recibió el nombramiento de ban después de la muerte de su hermano. El cargo no era una corona heredada ni sustituyó al rey; la instalación solemne se retrasó hasta 1668.',[R.petar,R.ban1647],{fechas:[{tipo:'acceso',anio:1665,nota:'Nombramiento como ban.'},{tipo:'inauguración',anio:1668,nota:'Instalación solemne; no se identifica con el nombramiento previo.'}]}),
 cambio('Valaquia','VLAD4CALUGAR',1482,'RADU4MARE',1495,['herencia'],'Radu sucedió a su padre Vlad Călugărul. Esta continuidad sigue una línea distinta de la de Vlad III, medio hermano del príncipe fallecido.',[R.radu,R.valacos]),
 cambio('Valaquia','MIRCEACIOBAN',1558,'PETRUTANAR',1559,['herencia'],'Petru sucedió a su padre a los doce años. La titularidad del hijo y la dirección política de su madre Chiajna se muestran en registros separados.',[R.petru,R.chiajna]),
 cambio('Moldavia','ALEXANDRULAPU',1564,'BOGDAN4LAPU',1568,['herencia','abdicación'],'La retirada de Alejandro precedió a su muerte. Su hijo Bogdan accedió durante la minoría, bajo la regencia de Ruxandra; el gobierno de la madre no se confunde con la titularidad del hijo.',[R.ruxandra,R.lapu]),
 cambio('Transilvania','GEORGE1RAKOCZI',1630,'GEORGE2RAKOCZI',1648,['herencia','elección'],'Jorge II continuó el principado de su padre. La continuidad familiar coexistía con el reconocimiento de los estamentos y con la superioridad otomana.',[R.rakgenea]),
 cambio('Trebisonda','ALEXIOS3TREB',1349,'MANUEL3TREB',1390,['herencia'],'Manuel sucedió a Alejo III. Su enlace georgiano ya era anterior a este acceso.',[R.komnenoi,R.manuel]),
 cambio('Trebisonda','MANUEL3TREB',1390,'ALEXIOS4TREB',1417,['herencia'],'Alejo continuó la línea de Manuel. Se mantiene la datación probable de 1417 y la nota sobre la incertidumbre del fallecimiento.',[R.komnenoi]),
 cambio('Trebisonda','ALEXIOS4TREB',1417,'JOHN4TREB',1429,['deposición'],'La rebelión de Juan terminó con la muerte de su padre. El parentesco explica quiénes eran los contendientes, pero no convierte el acceso en una transmisión pacífica.',[R.komnenoi]),
 cambio('Trebisonda','JOHN4TREB',1429,'DAVIDTREB',1460,['herencia'],'David sucedió a su hermano. La fecha de 1460 sigue la revisión de la documentación contemporánea frente a dataciones anteriores.',[R.komnenoi]),
];
