const fuentes=['https://www.treccani.it/'];
const change=(territorio,anterior,desdeAnterior,siguiente,desde,motivos,explicacion,extra={})=>({id:`${territorio}-${siguiente}-${desde}`,territorio,predecesor:{persona:anterior,desde:desdeAnterior},sucesor:{persona:siguiente,desde},motivos,explicacion,fuentes,...extra});
export const RELEVOS_ALPES=[
 change('Saboya','BONIFACIOSAB',1253,'PEDRO2SAB',1263,['herencia'],'Bonifacio murió sin descendencia. El condado pasó a su tío abuelo Pedro II; los descendientes de Tomás II no accedieron entonces al título.'),
 change('Saboya','FELIPE1SAB',1268,'AMEDEO5SAB',1285,['herencia','acuerdo'],'Amadeo V sucedió a su tío Felipe. Los acuerdos con los otros descendientes de Tomás II distribuyeron patrimonios en Vaud y Piamonte, manteniendo la primacía condal.'),
 change('Saboya','AMEDEO8SAB',1416,'LUISSAB',1440,['abdicación'],'Luis ya intervenía en el gobierno antes de recibir el ducado. La elección de su padre como Félix V precedió a la renuncia ducal; Amadeo VIII seguía vivo.',{fechas:[{tipo:'gobierno',anio:1434,nota:'Luis asume funciones de gobierno durante el retiro de su padre.'},{tipo:'acceso',anio:1440,nota:'Renuncia de Amadeo VIII al ducado.'}]}),
 change('Saboya','CARLOS1SAB',1482,'CARLOSGIOAMEDSAB',1490,['herencia'],'El hijo de Carlos I heredó antes de cumplir un año. Su madre Blanca de Monferrato ejerció la regencia: titularidad del niño y gobierno de la madre se registran por separado.'),
 change('Saboya','CARLOSGIOAMEDSAB',1490,'FELIPE2SAB',1496,['herencia'],'La muerte del niño sin descendencia extinguió esta línea masculina. Felipe II era hermano de Amadeo IX, abuelo del joven duque.'),
 change('Saboya','FILIBERTO2SAB',1497,'CARLOS3SAB',1504,['herencia'],'Filiberto II murió sin descendencia. Lo sucedió su medio hermano Carlos, hijo del segundo matrimonio de Felipe II.'),
 change('Saboya','CARLOS3SAB',1504,'EMANUELFILIBERTOSAB',1559,['herencia','acuerdo'],'Manuel Filiberto heredó el título en 1553, pero la recuperación territorial llegó con Cateau-Cambrésis. La fecha de este gobierno efectivo no es la fecha de la herencia.',{fechas:[{tipo:'acceso',anio:1553,nota:'Muerte de Carlos III y herencia del título.'},{tipo:'gobierno',anio:1559,nota:'Restitución acordada de los dominios; algunas plazas se entregaron después.'}]}),
 change('Monferrato','TEODORO1MON',1306,'JUAN2MONFERRATO',1338,['herencia'],'Juan II heredó de Teodoro I, consolidando la continuidad italiana de los Paleólogos.'),
 change('Monferrato','GUGL8MON',1464,'BONIF3MON',1483,['herencia'],'El marquesado pasó al hermano de Guillermo VIII. Las hijas de Guillermo y sus matrimonios mantuvieron expectativas patrimoniales, pero no sustituyeron ese acceso de Bonifacio.'),
 change('Monferrato','BONIF3MON',1483,'GUGL9MON',1494,['herencia'],'Guillermo IX sucedió a su padre siendo niño. La existencia de sus hijos retrasó las expectativas sucesorias de las casas vecinas.'),
 change('Monferrato','GUGL9MON',1494,'BONIF4MON',1518,['herencia'],'Bonifacio heredó a los seis años, bajo la tutela de su madre Ana de Alençon y de su tío Juan Jorge.'),
 change('Monferrato','BONIF4MON',1518,'GIANGIORGIOMON',1530,['herencia'],'Bonifacio murió sin descendencia y lo sucedió su tío. Las expectativas sobre los derechos de sus hermanas cobraron entonces nueva importancia.'),
 change('Monferrato','GIANGIORGIOMON',1530,'FED2GONZAGA',1536,['herencia','matrimonio','acuerdo'],'La extinción masculina de los Paleólogos abrió una disputa. La resolución imperial reconoció la transmisión a los Gonzaga por Margarita Paleólogo; la boda de 1531 no había transferido por sí sola el gobierno.'),
 change('Saluzzo','MANF3SAL',1215,'TOMAS1SAL',1244,['herencia'],'Tomás heredó durante su minoría. La tutela de la familia sostuvo el marquesado hasta que pudo gobernarlo personalmente.'),
 change('Saluzzo','LUDOVICO1SAL',1416,'LUDOVICO2SAL',1475,['herencia'],'Ludovico II heredó de su padre. Su madre Isabel de Monferrato lo conectaba con los marqueses vecinos y con la casa de Saboya.'),
 change('Saluzzo','LUDOVICO2SAL',1475,'MICHELEANTONIOSAL',1504,['herencia'],'El heredero era todavía niño. Su madre Margarita de Foix-Candale ejerció la tutela y mantuvo después funciones de gobierno durante las ausencias de su hijo.'),
 change('Saluzzo','JUANLUDSAL',1528,'FRANCESCOSAL',1529,['deposición','acuerdo'],'Juan Ludovico había sido aclamado marqués pese al testamento de su hermano. Su encarcelamiento en Francia permitió el reconocimiento de Francisco, favorecido por su madre y por Francisco I.'),
];
