// Translations of the existing editorial content; IDs, dates and relationships come from the Spanish records.
export const ENGLISH_STORIES = {
 borgona:{title:'Burgundy: the kingdom that never was',subtitle:'From a French appanage to a Habsburg inheritance',description:'Four generations of Valois dukes, a divided inheritance and the marriage that carried much of Burgundy into the Habsburg dynasty.',chapters:[
 ['A new Valois Burgundy','John II of France grants the Duchy of Burgundy to his son Philip the Bold. A younger branch of the Valois dynasty is born. Within a few generations, it will rival the power of the French monarchy itself.'],
 ['Expansion begins with a marriage','Philip marries Margaret of Flanders. Their marriage opens the way to Flanders, Artois and the County of Burgundy: wealthy, strategically placed territories that make the Burgundian dukes much more than lords of Dijon.'],
 ['John the Fearless inherits the project','When Philip the Bold dies, John the Fearless inherits an already powerful collection of territories. His policies become entangled with the crisis within France and the rivalry between Burgundians and Armagnacs.'],
 ['Montereau changes the balance','John the Fearless is murdered during negotiations at Montereau. His son Philip the Good inherits the duchy and moves towards the English side. Hostility towards the French Valois becomes one of the central forces in the Hundred Years’ War.'],
 ['A court with royal ambitions','Philip the Good founds the Order of the Golden Fleece. The Burgundian court develops an exceptionally ambitious political and ceremonial culture, reflecting a state that links scattered territories from Burgundy to the Low Countries.'],
 ['Burgundy changes sides','The Treaty of Arras reconciles Philip the Good with Charles VII. Burgundy abandons its English alliance and gains important concessions, while the French monarchy gains room to bring the Hundred Years’ War to an end.'],
 ['Charles the Bold and a divided territory','Charles the Bold inherits one of Europe’s richest states. His great difficulty is geographical: his lands form two large, separate blocks. His policy aims to join them and raise their status, creating an independent Burgundian kingdom in practice or in law.'],
 ['Nancy: the project breaks apart','Charles dies at the Battle of Nancy without a male heir. Louis XI occupies the Duchy of Burgundy and other French territories. Mary, Charles’s only daughter, must defend the rest of her father’s inheritance.'],
 ['The inheritance changes dynasty','Mary of Burgundy marries Maximilian of Habsburg. Their marriage preserves much of the Burgundian Netherlands and turns a succession crisis into the starting point of the great rivalry between France and the Habsburgs.'],
 ['What remains of Burgundy','The Treaty of Senlis returns Artois and the County of Burgundy to the Habsburgs’ Burgundian inheritance. The old Duchy of Burgundy, however, remains in France. Charles’s territorial ambition can no longer be rebuilt in its original form.'],
 ['From Burgundy to Charles V','Philip the Handsome passes the Burgundian inheritance to his son Charles. For Charles V, the Low Countries and Burgundian court traditions will be essential parts of his political identity. The kingdom Charles the Bold failed to establish becomes one of the foundations of Habsburg power.'],
 ]},
 gioconda:{title:'In search of the Mona Lisa',subtitle:'Leonardo’s life and the women behind the mystery',description:'Follow Leonardo from the Sforza court to France, through documented portraits and proposed identities, to the identification accepted by the Louvre.',chapters:[
 ['Milan: Leonardo enters a court of images and power','Leonardo leaves Florence and enters the orbit of Ludovico Sforza. In Milan, he is much more than a painter: he designs machines, festivities, fortifications and monumental projects. He also learns to make court portraiture remarkably lifelike. Here begins the trail that will lead us to the Mona Lisa.'],
 ['The Lady with an Ermine: a mystery we can solve','Cecilia Gallerani, an educated young woman at court and Ludovico Sforza’s mistress, sits for Leonardo around 1490. Her identification as the Lady with an Ermine is firmly established. Years before the Mona Lisa, Leonardo already makes a woman seem caught in the middle of a gesture and an unseen conversation.'],
 ['Mantua: Isabella d’Este wants a Leonardo','When the French overthrow Ludovico, Leonardo leaves Milan. In Mantua, he draws Isabella d’Este. The surviving drawing demonstrates a direct artistic relationship. That connection and her prestige have placed Isabella in some theories about the Mona Lisa, although the Louvre portrait points elsewhere.'],
 ['The Italy of Caterina Sforza','Leonardo travels through a turbulent Italy where the same families appear repeatedly around art and warfare. Caterina Sforza, ruler of Forlì and daughter of Galeazzo Maria, has also been proposed as the sitter. The historical setting makes the suggestion intriguing, but it lacks the documentary trail that we will find in Florence.'],
 ['With Cesare Borgia: Leonardo maps territories, not faces','For several months, Leonardo works for Cesare Borgia as a military engineer. He visits fortresses and towns, studies rivers, roads and defences, and produces some of his most remarkable maps. The episode reminds us that the painter of Europe’s most famous face studies a face, a machine and a landscape with the same intensity.'],
 ['Florence: the decisive clue','Back in Florence, we meet Lisa Gherardini, wife of the merchant Francesco del Giocondo. The family name explains “Gioconda”; written accounts and surviving documentation fit the beginning of the portrait around 1503. This is the identification supported by the Louvre and the prevailing scholarly consensus: the woman in the painting is Lisa Gherardini.'],
 ['Why are there so many proposed sitters?','Leonardo spent decades among courts full of powerful women and left paintings, drawings and accounts that are difficult to reconcile. Isabella of Aragon, Costanza d’Avalos, Bianca Giovanna Sforza, Caterina Sforza and Isabella d’Este have all featured in proposals. Some fit a period in his life, but none brings together the evidence that favours Lisa Gherardini.'],
 ['Leonardo returns to Milan, and the portrait travels with him','Leonardo returns to Milan, now under French control, and finds a new patron in Charles II d’Amboise. The Mona Lisa is not left behind as a completed, delivered commission. Leonardo keeps the painting and continues to work on it for years. It becomes an increasingly personal work.'],
 ['Rome: a final Italian clue','Leonardo settles in Rome under the protection of Giuliano de’ Medici, brother of Leo X. A later account mentions a portrait of a Florentine woman made at Giuliano’s request. This has fuelled debate, but the Louvre considers it compatible with confusion about which works the witness saw, rather than sufficient reason to replace Lisa as the sitter.'],
 ['France: the painting leaves Italy with Leonardo','Francis I invites Leonardo to France. The artist crosses the Alps with Francesco Melzi and takes several paintings on which he is still working, including the Mona Lisa. His last patron does not commission the portrait: he receives the artist’s presence and, later, the work Leonardo had kept with him.'],
 ['The end of the search: one woman and Leonardo’s life','Leonardo dies in France in 1519. Our journey has brought us documented portraits such as Cecilia Gallerani, women he certainly drew such as Isabella d’Este, and candidates proposed from the courts he knew. Taken together, the evidence leads to the Louvre’s identification: Lisa Gherardini, wife of Francesco del Giocondo. The remaining mystery is less who she is than why Leonardo kept transforming her portrait for so many years.'],
 ]},
};
export const ENGLISH_PEOPLE = {
 ISAB1CAST:{name:'Isabella I of Castile',role:'Queen of Castile',summary:'Queen of Castile whose marriage to Ferdinand of Aragon linked the two major Iberian crowns without immediately merging their institutions. Her reign shaped the dynastic inheritance later received by the Habsburgs.'},
 CARLOS5:{name:'Charles V',role:'Holy Roman Emperor',summary:'Holy Roman Emperor and ruler of a composite monarchy spanning the Iberian Peninsula, Italy, the Low Countries and the Americas. His reign was shaped by the Reformation, rivalry with France and Ottoman expansion.'},
 LEONARDODAVINCI:{name:'Leonardo da Vinci',role:'Artist and engineer',summary:'Painter, engineer and investigator of nature who worked in Florence, Milan, Rome and France. His service to the Sforza, Cesare Borgia, the Medici and Francis I connects his artistic work with the courts and political networks of his time.'},
 MARIABORG:{name:'Mary of Burgundy',role:'Duchess of Burgundy',summary:'Only daughter and heir of Charles the Bold. After her father’s death in 1477, she defended a disputed inheritance. Her marriage to Maximilian of Habsburg linked much of the Burgundian Netherlands to the Habsburg dynasty.'},
 MAXIM1:{name:'Maximilian I',role:'Holy Roman Emperor',summary:'Habsburg ruler whose marriage to Mary of Burgundy brought a major Burgundian inheritance into his family’s political network. His descendants connected that inheritance with the Iberian crowns and the wider monarchy of Charles V.'},
};
export const ENGLISH_METHOD = [
 ['Bibliography','The general bibliography brings together the works, databases and institutions consulted. References to individual articles and biographies appear in the corresponding profiles.'],
 ['Context and evidence','This database is a developing synthesis: a contextual reference does not by itself verify every detail in a profile.'],
 ['Approximate dates','Dates are usually expressed by year; “c.” marks dates recorded as approximate.'],
 ['Uncertain ranges','Where a date is known only as a range or bound, the profile displays it as such and adds a documentary explanation. The year filter includes years compatible with those bounds. Approximate dates retain their conventional year without inventing a margin of error.'],
 ['Dynastic lines','Dynasty profiles distinguish cadet branches from transfers by marriage or inheritance. A shared family name does not by itself establish a line of descent among all its bearers.'],
 ['Auxiliary references','Wikipedia is used as an auxiliary bibliographic guide. Disputed family relationships and chronologies require corroboration with specialist references.'],
 ['Government','Government records distinguish territory, title, class and condition. A claim or nominal title is not equivalent to effective rule.'],
 ['Successions','Explained successions are an editorial selection: a later entry does not by itself prove direct succession. Crises show historical claims; kinship is limited to recorded parentage. Accession to a title, coronation and effective rule are distinguished when specific information exists.'],
 ['Crowns and years','Title stages group offices by year and distinguish effective rule, regency and nominal titles. Overlap within one year does not prove that two rulers held power on the same day. Unions may include breaks and do not imply uniform institutions. Europe in this year summarises only loaded data compatible with the selection; it does not extend lives beyond sufficiently documented bounds.'],
 ['Cartography and coverage','The map is a simplified historical representation. An absent relationship means that it is not recorded in this database.'],
];
export const ENGLISH_ABOUT = [
 ['What the project does','The Tree of Europe is an interactive historical genealogy project. It places family relationships, dynasties, reigns and political connections in medieval and early modern Europe within one navigable network.','The Atlas combines genealogy, chronology and maps so that a person can be explored through their family, their lifetime and the territories connected to them.'],
 ['How to read the records','A missing person or relationship does not mean that it did not exist historically. The record may simply not have been added yet.','The project prioritises people who connect branches, held power, founded significant lines or make a historical connection easier to understand. Documented corrections take priority over visual consistency.'],
 ['Scope and author','The main period covered is 1200–1800. The database is still being expanded, corrected and documented.','The project is maintained by Manuel Muriel Cagigal, a European Studies student specialising in International Relations.'],
];
