"""Explicit regional selections for the frontier review, 8 October 2026.

Inputs are immutable anchors and the preceding continuity review. The user's
HTML is a visual checklist, never a source of authority or an automatic import.
Every selected ID denotes an area, not a point. See docs/atlas-frontier-review.md.
"""
import json
from pathlib import Path
import xml.etree.ElementTree as ET
H = Path(__file__).resolve().parent
D = json.loads((H/'corridor-locations.json').read_text())
CW = D['locationCrosswalk']['newIdsByOldId']
A = json.loads((H/'frontier-anchors.json').read_text())
C = json.loads((H/'continuity-review.json').read_text())
R = {'reviewedAt':'2026-10-08','replacements':[],'territories':[],'overrides':[],
     'limitations':['Contornos regionales aproximados, contrastados visualmente. No reconstruyen todas las guarniciones ni cada frontera diaria.', 'No se importa automáticamente la cartografía del HTML de referencia: algunas atribuciones abarcan estados vecinos.']}
def ss(title,url,locator):return {'title':title,'url':url,'locator':locator}
def union(*groups):return sorted(set().union(*map(set,groups)))
def reg(*names):return union(*(CW[n]['ids'] for n in names))
def ids(text):return text.split()
def v(year,cells,event):return {'from':year,'ids':sorted(set(cells)),'oldIds':[],'borderline':[],'event':event}
def at(e,year):return next(x['ids'] for x in reversed(e['versions']) if x['from']<=year)
def replacement(name,start,end,versions,sources,note):
 R['replacements'].append({'name':name,'coverage':{'from':start,'through':end},'versions':versions,'sources':sources,'note':note,'precision':'regional_approximation','limitedCore':False})
def layer(name,start,end,versions,sources,note,supersedes=(),condition=None):
 e={'name':name,'corridor':'Fronteras y dominios europeos','coverage':{'from':start,'through':end},'active':{'from':start,'through':end},'versions':versions,'sources':sources,'note':note,'precision':'regional_approximation','limitedCore':False,'supersedes':list(supersedes),'color':'#86715d'}
 if condition:e['authorityCondition']=condition
 R['territories'].append(e)
BUL = ss('Universidad de Atenas · G. Arvaniti, relaciones bizantino-búlgaras (2018)','https://pergamos.lib.uoa.gr/uoa/dl/object/2819196/file.pdf','pp.27–45 y mapa p.106 (PDF p.111): expansión y contracción bajo los Asen; separar las áreas rayadas de vasallaje. No se adopta sin reserva su gran ámbito al norte del Danubio.')
TARN = ss('Museo Histórico de Veliko Tarnovo · Iglesia de los Cuarenta Mártires','https://tickets.museumvt.com/en/sites-tickets/holy-forty-martyr-s-church-and-the-great-laurel-monastic-complex?ulo=true','Inscripción original de Iván Asen II y victoria de 1230; Kaloyan muerto en 1207. Acredita autoridad y acontecimientos, no todos los contornos.')
VID = ss('Museo de Knjaževac · Vidin y la región del Timok','https://pojmovnik.muzejknjazevac.org.rs/pojam/vidin/','Región entre Iskar y Timok; conquista otomana de Vidin en 1396. La celda de Koželj se verifica en Serbia, no por mera coincidencia del nombre.')
VIDH = ss('Municipio de Vidin · Historia de Vidin','https://old.vidin.bg/pages/Istoriq-na-Vidin-140','Estado de Iván Sratsimir y caída de 1396; no extender Vidin sobre toda Bulgaria.')
DOB = ss('Kemal Karpat · TDV · Dobruca','https://islamansiklopedisi.org.tr/dobruca','Principado de Balik, Dobrotitsa e Ivanko; expansión de 1359 y transición disputada de fines del XIV. No todo el territorio moderno ni una soberanía búlgara uniforme.')
DRAG = ss('Instituto Lexicográfico Miroslav Krleža · Stefan Dragutin','https://www.enciklopedija.hr/clanak/dragutin-stefan','1284: Mačva con Belgrado y Usora; señoríos serbios retenidos desde 1282. No identifica este reino con toda la Sirmia geográfica al norte del Sava.')
HUNG = ss('C. A. Macartney · Hungary: A Short History, Biblioteca Nacional de Hungría','https://mek.oszk.hu/02000/02086/02086.htm','Caps.1–5: reino medieval y partición; Karlowitz conserva el Banato otomano. Diferenciar el reino de Croacia y la administración separada del Banato.')
TRANS = ss('Academia de Ciencias de Hungría · History of Transylvania','https://mek.oszk.hu/03400/03407/html/','Vol.II: principado y Partium, frontera cambiante, Várad perdida en 1660; ocupación de 1551–1556 y dominación imperial posterior.')
BUDA = ss('Géza Dávid · TDV · Budin','https://islamansiklopedisi.org.tr/budin','Gobiernos rivales de 1526–1529; eyalato desde 1541; registro territorial de los sancados, conquista habsbúrgica de 1686. La incursión de 1526 no es anexión permanente de toda Hungría.')
TEMES = ss('Géza Dávid · TDV · Tımışvar','https://islamansiklopedisi.org.tr/timisvar','Eyalato 1552–1716. El Banato no se cede con el resto de Hungría en 1699; su reincorporación administrativa a Hungría (1778–1779) se contrasta con Macartney.')
# Moesia and adjoining contours: actual shapes include the Balkan mountains.
moesia = ids('Vidin Archar Lom Kutlovitsa Oryahovo Vratsa Dobrolak Gigen Pleven Nikopol Ruse Cherven Razgrad Tarnovo Lyaskovets Tryavna Hotalich Lovech Bozhenitsa Targoviste_Bul Shumen Veliki_Preslav Ovech Tutrakan Drastar Balkan_Mountains1 Balkan_Mountains2 Balkan_Mountains3 Balkan_Mountains4 Balkan_Mountains5 Balkan_Mountains6')
coast = ids('Varna Karvuna Kaliakra Kladentsi Pangalia Cernavoda Harsova Babadag Enisala Tulcea Isaccea')
south = ids('Sredets Svoge Stipon Kostenets Strelcha Kran Sliven Boruy Lardeja Ktenia Aytos Anhialo Burgas Rusokastro Plovdiv Stanimaka Samokov Dupnitsa Velbuzd Bansko Krupnik Tsepina Beden Smolyan Nevrokop Melnik Rhodope_Mountains1 Rhodope_Mountains2 Rhodope_Mountains3 Rhodope_Mountains4 Rhodope_Mountains5 Rhodope_Mountains6')
# Controlled southern acquisitions after Klokotnitsa, not Thessaloniki/Epirus
# vassals or the Latin capital. Western Macedonia is not permanent Bulgaria.
expansion = ids('Haskovo Perperek Ustra Ormenio Komotini Xanthia Serres Kavala Drama Shtip Strumica Prosek Veles Kocani Skopje Kumanovo Kratovo Prilep Bitola Ohrid Kicevo Tetovo Debar')
vidin = ids('Vidin Archar Lom Kutlovitsa Vratsa Dobrolak Kozelj Balkan_Mountains1 Balkan_Mountains2')
bul1200=union(moesia,[x for x in coast if x!='Varna'])
bul1205=union(moesia,coast,south)
bul1246=union(moesia,coast,[x for x in south if x not in ids('Plovdiv Stanimaka Melnik Nevrokop Beden Smolyan Rhodope_Mountains1 Rhodope_Mountains2 Rhodope_Mountains3 Rhodope_Mountains4 Rhodope_Mountains5 Rhodope_Mountains6')])
bul1304=union(bul1246,ids('Burgas Anhialo Sozopol Rusokastro'))
bul1344=union(bul1304,ids('Plovdiv Stanimaka Tsepina Beden Smolyan Rhodope_Mountains2 Rhodope_Mountains3'))
layer('Bulgaria',1200,1370,[v(1200,bul1200,'Marco conservador de Moesia; no anticipar Varna.'),v(1201,union(bul1200,['Varna']),'Conquista de Varna.'),v(1205,bul1205,'Expansión hacia Sredets y Tracia; cortes regionales, no un frente diario.'),v(1230,union(bul1205,expansion),'Klokotnitsa: expansión meridional. Tesalónica y Epiro no se convierten en dominio directo.'),v(1246,bul1246,'Contracción frente a Nicea después de la muerte de Kalimán.'),v(1304,bul1304,'Recuperaciones de Teodoro Svetoslav.'),v(1344,bul1344,'Cesiones tracias a Iván Alejandro.'),v(1346,[x for x in bul1344 if x not in ids('Karvuna Kaliakra Kladentsi Pangalia')],'Principado costero diferenciado.'),v(1359,[x for x in bul1344 if x not in [c for c in coast if c!='Varna']],'Expansión septentrional del despotado de Dobruja.'),v(1360,[x for x in bul1344 if x not in vidin+[c for c in coast if c!='Varna']],'Vidin y Dobruja tienen gobiernos separados.'),v(1369,[x for x in bul1344 if x not in vidin+coast],'Varna pasa al despotado costero.')],[BUL,TARN,VID,DOB],'Segundo Imperio búlgaro. La tributación mongola no extingue automáticamente el zarato. No se atribuyen Valaquia y Moldavia completas por una reivindicación imperial; quedan pendientes sus fronteras tempranas.')
layer('Zarato de Tarnovo',1371,1395,[v(1371,[x for x in bul1344 if x not in vidin+coast],'Zarato oriental de Iván Shishman.'),v(1382,[x for x in bul1344 if x not in vidin+coast+ids('Sredets Svoge Stipon Samokov Kostenets Dupnitsa Velbuzd')],'Pérdida del área de Sofía.'),v(1388,ids('Tarnovo Lyaskovets Tryavna Lovech Hotalich Bozhenitsa Pleven Nikopol Balkan_Mountains4 Balkan_Mountains5'),'Contracción tras la campaña otomana de 1388.'),v(1393,['Nikopol'],'Tarnovo cae; Shishman conserva Nikopol hasta 1395.')],[BUL,VID,DOB],'Zarato de Tarnovo, tributario de los otomanos desde la década de 1370. El vasallaje no equivale a administración directa. Desde 1393 solo se representa Nikopol; los frentes menores continúan pendientes.')
layer('Zarato de Vidin',1360,1396,[v(1360,vidin,'Gobierno regional de Iván Sratsimir.'),v(1365,[],'Ocupación húngara; el zar permanece cautivo.'),v(1369,vidin,'Restauración de Iván Sratsimir.'),v(1396,[],'Conquista otomana de Vidin; termina la superficie regia.')],[VID,VIDH,BUL],'Zarato separado, con ocupación húngara de 1365–1369. Su dependencia otomana no convierte a Sratsimir en gobernador provincial del sultán.')
layer('Vidin · ocupación húngara',1365,1368,[v(1365,vidin,'Gobierno militar húngaro de Vidin.')],[BUL,VID],'Ocupación temporal durante el cautiverio de Sratsimir; no se extiende a Tarnovo.',condition='ocupación')
layer('Despotado de Dobruja',1346,1388,[v(1346,ids('Karvuna Kaliakra Kladentsi Pangalia'),'Dominio costero de Balik y Dobrotitsa.'),v(1359,ids('Karvuna Kaliakra Kladentsi Pangalia Cernavoda Harsova Babadag Enisala Tulcea Isaccea'),'Expansión septentrional documentada por Karpat.'),v(1369,ids('Karvuna Kaliakra Kladentsi Pangalia Varna Cernavoda Harsova Babadag Enisala Tulcea Isaccea'),'Varna bajo Dobrotitsa.')],[DOB],'Despotado costero de Karvuna/Dobruja. El límite septentrional y el relevo de 1388–1389 son inciertos: no se colorea toda Dobruja moderna ni se fuerza una frontera precisa.')
layer('Bulgaria · gobierno rival en Tarnovo',1279,1280,[v(1279,['Tarnovo','Lyaskovets'],'Gobierno de Iván Asen III en la capital, enfrentado a Ivaylo.')],[ss('Instituto Lexicográfico Miroslav Krleža · Ivan Asen III','https://www.enciklopedija.hr/clanak/ivan-asen-iii','Reinado rival 1279–1280.')],'Ámbito acreditado en la capital; no se atribuye todo el zarato por el título.',condition='control disputado')
layer('Sirmia',1284,1316,[v(1284,ids('Sabac Debrc Belgrad Krupanj Valjevo Srebrenik Teocak Soli Doboj Rudnik Arilje Gradac'),'Mačva, Belgrado, Usora/Soli y señoríos retenidos de Dragutin.')],[DRAG],'Reino de Sirmia de Stefan Dragutin. Superficie regional aproximada al sur del Sava; Sremska Mitrovica, Ilok y Petrovaradin no se adjudican por el nombre moderno de Sirmia.')
# Hungary: province contours across the entire period, without importing
# Croatian coastal cells or returning Ottoman Buda to Ferdinand in 1541.
croatian=ids('Zagreb Varazdin Koprivnica Bjelovar Sisak Kutina Virovitica Pakrac Petrinja Dubica Gradiski_Brod Kozara Bihac Karlovac Slunj Otocac Senj Knin Kaseg Srb Crikvenica Rijeka Krk Pag Novigrad Zadar Sibenik Sinj Dinaric_Alps1 Dinaric_Alps9')
SLAV=ss('Instituto Lexicográfico Miroslav Krleža · Slavonija','https://www.enciklopedija.hr/clanak/slavonija','Condados medievales de Zagreb y Križevci; incorporación posterior de Varaždin y Virovitica; Požega, Vukovo y Sirmia pertenecen a Hungría, no a la Eslavonia medieval. Desde 1552 la frontera otomana separa el ámbito oriental.')
KNIN=ss('Instituto Lexicográfico Miroslav Krleža · Knin','https://www.enciklopedija.hr/clanak/knin','Centro del reino croata; conquista otomana en mayo de 1522; no todas las ciudades de la costa pertenecen a Croacia.')
SINJ=ss('Instituto Lexicográfico Miroslav Krleža · Cetinska krajina','https://www.enciklopedija.hr/clanak/cetinska-krajina','Pérdida de la región de Sinj desde 1513; el artículo de la ciudad ofrece 1524. El corte regional es aproximado y no resuelve cada fortaleza.')
croatInterior=ids('Bihac Slunj Otocac Senj Knin Kaseg Srb Sinj Dinaric_Alps1')
slavInterior=ids('Zagreb Varazdin Koprivnica Bjelovar Sisak Kutina Virovitica Pakrac Petrinja Dubica Gradiski_Brod Kozara')
layer('Croacia medieval',1200,1526,[v(1200,croatInterior,'Ámbito interior de la Corona croata.'),v(1388,[x for x in croatInterior if x!='Knin'],'Knin bajo autoridad bosnia.'),v(1393,croatInterior,'Restauración en Knin.'),v(1513,[x for x in croatInterior if x!='Sinj'],'Retirar Sinj desde la pérdida regional, sin fijar cada fortaleza.'),v(1522,[x for x in croatInterior if x not in ['Knin','Sinj']],'Conquista otomana de Knin.')],[KNIN,SLAV,HUNG,SINJ],'Marco regional interior bajo la Corona croata: señoríos, bans y ciudades no equivalen a propiedad directa del rey. No se incluyen Rijeka, Krk ni las ciudades venecianas de Dalmacia. Las pérdidas de Lika y Krbava necesitan una revisión más fina.',supersedes=['Croacia anterior a 1527 (Knin)','Croacia anterior a 1527 (Bihać)','Croacia anterior a 1527 (Senj)'])
layer('Eslavonia medieval',1200,1526,[v(1200,slavInterior,'Jurisdicción regional medieval, no sólo ciudades con carta real.')],[SLAV,HUNG],'Ámbito aproximado de la jurisdicción provincial; la evolución institucional del siglo XIII se distingue de la fecha de una carta urbana. La selección no incorpora las provincias orientales de Požega, Vukovo y Sirmia como Eslavonia medieval.',supersedes=['Eslavonia anterior a 1527 (núcleos)'])
medieval=[x for x in at(A['Hungría'],1400) if x not in croatian]
replacement('Hungría',1200,1526,[v(1200,medieval,'Reino medieval; Croacia conserva jurisdicción propia.'),v(1412,[x for x in medieval if x!='Lubica'],'Prenda de ciudades del Spiš a Polonia; celda aproximada.'),v(1526,[x for x in medieval if x not in ids('Petrovaradin Sremska_Mitrovica Ilok Osijek Vukovar')],'Mohács y gobiernos rivales: el corte anual no supone control uniforme.')],[HUNG,BUDA],'Reino de Hungría estricto, incluidos el interior y los relieves cárpatos. Croacia y los banatos fronterizos se documentan aparte. La invasión mongola de 1241–1242 y el conflicto de 1526 no se presentan como anexiones permanentes.')
royal=reg('Sopron','Vas','Zala','Hont','Nograd','Szepes','Zemplen','Szabolcs')
royal=union(royal,ids('Bratislava Samorin Trnava Nitra Holic Hlohovec Trencin Povazska_Bystrica Prievidza Zilina Turciansky_Svaty_Martin Oravsky_Podzamok Liptovsky_Mikulas Western_Carpathians1 Western_Carpathians2 Papa Veszprem Csurgo Kaposvar Segesd Somogyvar Komarom Tata Borsod Miskolc Khust Mezhorje Rakhiv Eastern_Carpathians1 Eastern_Carpathians2'))
central1541=ids('Buda Pest Abrahamtelke Kecskemet Felegyhaza Halas Kalocsa Solt Adony Mohacs Baja_Hungary Bodrog Bacs Zenta Titel Osijek Vukovar Ilok Sremska_Mitrovica Petrovaradin')
central1543=union(central1541,ids('Pozega Esztergom Fehervar Pecs Siklos Tolna Simontornya Szeged Mako'))
central1552=union(central1543,ids('Pakrac Virovitica Kutina Vaska Szolnok Karcag Csanad Nograd Balassagyarmat Salgotarjan Heves Jaszbereny'))
central1566=union(central1552,ids('Somogyvar Kaposvar Segesd Csurgo Bekes Szarvas'))
banat=ids('Timisoara Lipova Arad Kikinda Veliky_Beckerek Modos Pancevo Kovin Recas Lugoj Caransebes Carasova Semlacu_Mare Southern_Carpathians4 Mihalt')
trans=reg('Transylvania','Maramaros') if 'Transylvania' in CW else union(*(reg(n) for n in ['Kolozs','Torda'] if n in CW))
trans=union(ids('Aiud Alba_Iulia Baia_Crisului Baia_de_Aries Baita Bistrita Brasov Cetatea_Balta Chezdi_Osorheiu Cincu Cluj Covasna Cristuru_Secuiesc Crasna Cuhea Dabaca Dej Deva Fagaras Felvint Gheorgheni Gurghiu Hateg Hodod Huedin Hunedoara Inner_Carpathians Medias Miercurea_Cluc Odorhei Reghin Sebes Sfantu_Gheorghe Sibiu Sic Sighet Sighisoara Targu_Mures Turda Zalau'),ids('Eastern_Carpathians3 Eastern_Carpathians4 Eastern_Carpathians5 Eastern_Carpathians5b Eastern_Carpathians6 Eastern_Carpathians6c Eastern_Carpathians7 Eastern_Carpathians8 Southern_Carpathians2'))
partium=reg('Bihar','Szatmar','Zarand_Hun')
trans1541=union(trans,partium)
east1527=[x for x in union(trans1541,reg('Heves'),central1566,banat) if x not in croatian+ids('Ilok Vukovar Petrovaradin Sremska_Mitrovica Osijek')]

replacement('Núcleo oriental de Zápolya',1526,1540,[v(1526,east1527,'Gobierno rival de Juan I, no una frontera estable.'),v(1527,[x for x in east1527 if x not in ids('Buda Pest')],'Fernando ocupa Buda; Juan mantiene la base oriental.'),v(1529,east1527,'Buda restituida a Juan bajo protección otomana.'),v(1537,[x for x in east1527 if x!='Pozega'],'Požega pasa a administración otomana.')],[HUNG,TRANS,BUDA],'Ámbito aproximado del reino oriental de Juan I: una misma Hungría con autoridades rivales. Las comarcas de frontera requieren lectura de las disputas; la protección otomana no es todavía un eyalato.')
VARAD=ss('Mihai Maxim · TDV · Varad','https://islamansiklopedisi.org.tr/varad','Eyalato de Várad desde 1660; conquista imperial y fin de la administración otomana regional en 1692.')
GYULA=ss('Municipio de Gyula · Historia','https://gyula.hu/gyula/elet-gyulan/varosinformacio/varostortenet/','Ciudad y castillo de Fernando en la década de 1550; conquista otomana de 1566 y recuperación de 1695. La tributación rural anterior no implica la caída del castillo.')
recovered1686=union(central1543,ids('Nograd Balassagyarmat Salgotarjan Csurgo Kaposvar Segesd Somogyvar'))
layer('Transilvania medieval',1200,1540,[v(1200,trans,'Voivodato de la Corona húngara, anterior al principado.')],[TRANS,HUNG],'Provincia bajo el rey húngaro y un voivoda delegado; el título principesco posterior no se anticipa al gobierno medieval. El Partium pertenece a otra configuración posterior.')
replacement('Hungría real',1527,1800,[v(1527,union(royal,[x for x in central1543 if x not in central1541+ids('Mako Szeged')],['Buda','Pest','Eger']),'Hungría occidental y septentrional; control rival.'),v(1529,union(royal,[x for x in central1543 if x not in central1541+ids('Mako Szeged')],['Esztergom','Eger']),'Buda vuelve a Juan I.'),v(1537,union(royal,[x for x in central1543 if x not in central1541+ids('Pozega Mako Szeged')],['Eger']),'Pérdida de Požega; Buda sigue fuera del gobierno de Fernando.'),v(1543,union([x for x in royal if x not in central1543],['Eger']),'Pérdida de Esztergom.'),v(1552,union([x for x in royal if x not in central1552+ids('Nograd Balassagyarmat Salgotarjan')],['Eger','Bekes','Szarvas']),'Conquista de Nógrád y las comarcas centrales.'),v(1566,union([x for x in royal if x not in central1566],['Eger']),'Pérdidas en Somogy y Gyula.'),v(1596,[x for x in royal if x not in central1566+ids('Eger Nograd Balassagyarmat Salgotarjan')],'Pérdida de Eger.'),v(1600,[x for x in royal if x not in central1566+ids('Eger Nagykanizsa Nograd Balassagyarmat Salgotarjan')],'Conquista de Kanizsa.'),v(1686,union([x for x in royal if x not in ids('Nagykanizsa Nograd Balassagyarmat Salgotarjan')],recovered1686),'Recuperación de Buda; Eger y Kanizsa todavía no se restituyen.'),v(1687,union([x for x in royal if x!='Nagykanizsa'],recovered1686,['Eger']),'Restitución de Eger.'),v(1690,union(royal,[x for x in central1566 if x not in ids('Bekes Szarvas')],['Eger','Nagykanizsa']),'Restitución de Kanizsa, sin anticipar Gyula.'),v(1692,union(royal,[x for x in central1566 if x not in ids('Bekes Szarvas')],reg('Bihar'),['Eger','Nagykanizsa']),'Recuperación de Várad/Bihar, sin Gyula.'),v(1695,union(royal,central1566,reg('Bihar'),['Eger','Nagykanizsa']),'Recuperación de Gyula y su ámbito.'),v(1699,[x for x in medieval if x not in trans+banat],'Karlowitz: Hungría bajo los Habsburgo; Transilvania y Banato mantienen administración separada.'),v(1779,[x for x in medieval if x not in trans],'Reincorporación administrativa del Banato de Temes.')],[HUNG,BUDA,TEMES,TRANS,GYULA,VARAD],'Reino de Hungría bajo los Habsburgo; no todo el reino medieval durante la partición. Se conservan los relieves y provincias septentrionales. La cronología de las pequeñas fortalezas y la insurrección de Rákóczi siguen siendo aproximadas.')
replacement('Hungría otomana',1526,1716,[v(1526,ids('Ilok Vukovar Petrovaradin Sremska_Mitrovica'),'Frontera conquistada; Buda no queda anexada.'),v(1529,ids('Ilok Vukovar Petrovaradin Sremska_Mitrovica Osijek'),'Expansión fronteriza.'),v(1541,central1541,'Creación del eyalato de Budin.'),v(1543,central1543,'Expansión a Pécs y Esztergom.'),v(1537,ids('Ilok Vukovar Petrovaradin Sremska_Mitrovica Osijek Pozega'),'Požega bajo administración otomana.'),v(1552,union(central1552,banat,ids('Pozega Pakrac Virovitica Kutina Vaska')),'Nuevo eyalato de Temesvár; no se anticipa la conquista de Gyula en 1566.'),v(1566,union(central1566,banat,ids('Ineu Zarand')),'Expansión meridional.'),v(1596,union(central1566,banat,ids('Ineu Zarand Eger')),'Eyalato de Eğri.'),v(1600,union(central1566,banat,ids('Ineu Zarand Eger Nagykanizsa')),'Kanizsa otomana.'),v(1660,union(central1566,banat,reg('Bihar'),ids('Ineu Zarand Eger Nagykanizsa')),'Eyalato de Várad; Debrecen conserva jurisdicción municipal bajo dependencia tributaria.'),v(1686,union([x for x in central1566 if x not in recovered1686],banat,reg('Bihar'),ids('Ineu Zarand Eger Nagykanizsa')),'Pérdida de Budin; otros ámbitos siguen otomanos.'),v(1687,union([x for x in central1566 if x not in recovered1686],banat,reg('Bihar'),ids('Ineu Zarand Nagykanizsa')),'Eger deja de ser otomana.'),v(1690,union(banat,reg('Bihar'),ids('Ineu Zarand Bekes Szarvas')),'Kanizsa cae; Gyula aún otomana.'),v(1692,union(banat,ids('Ineu Zarand Bekes Szarvas')),'Pérdida del eyalato de Várad.'),v(1695,union(banat,ids('Ineu Zarand')),'Pérdida de Gyula.'),v(1699,banat,'Karlowitz conserva el Banato de Temesvár.'),v(1716,[],'Conquista de Temesvár.')],[BUDA,TEMES,HUNG,GYULA,VARAD],'Administración otomana de Budin, Temesvár y sus eyalatos asociados, dentro de la región histórica húngara. No se confunde con vasallaje transilvano. Los cortes de 1686–1699 no reconstruyen todos los asedios.',)
replacement('Transilvania',1541,1698,[v(1541,union(trans1541,banat,ids('Bekes Csanad Heves Jaszbereny Karcag Mako Szarvas Szolnok Szeged Vaska')),'Reino oriental y Partium, antes del título principesco de 1570.'),v(1543,[x for x in union(trans1541,banat,ids('Bekes Csanad Heves Jaszbereny Karcag Mako Szarvas Szolnok Szeged Vaska')) if x not in ids('Mako Szeged')],'Conquistas otomanas en la llanura meridional.'),v(1551,[],'Administración imperial temporal.'),v(1556,[x for x in trans1541 if x not in banat],'Restauración del gobierno oriental, sin Temesvár y Lipova.'),v(1566,[x for x in trans1541 if x not in banat+ids('Ineu Zarand')],'Pérdidas occidentales frente a los otomanos.'),v(1660,[x for x in trans1541 if x not in reg('Bihar')+banat+ids('Ineu Zarand')],'Várad y su ámbito bajo administración otomana.')],[TRANS,HUNG],'Transilvania y Partium; relieves y provincias interiores completos. El título de príncipe comienza en 1570; antes gobierna el rey electo de Hungría. La pérdida de Várad no extingue el principado.')
replacement('Ocupación habsbúrgica de Transilvania',1551,1555,[v(1551,union(trans1541,banat),'Gobierno temporal imperial.'),v(1552,[x for x in trans1541 if x not in banat],'Pérdida de Temesvár; continúa la administración imperial de Transilvania.')],[TRANS],'Ocupación y administración temporal; no dominio habsbúrgico ininterrumpido desde 1541.')
replacement('Transilvania habsbúrgica',1699,1800,[v(1699,trans,'Provincia separada bajo los Habsburgo.')],[TRANS,HUNG],'Transilvania mantiene administración diferenciada de Hungría, también después de Karlowitz.')
layer('Banato de Temes',1716,1778,[v(1716,banat,'Conquista y administración imperial del Banato; ratificación en 1718.')],[TEMES,HUNG],'Provincia imperial de Temes, separada de la administración del reino húngaro hasta 1778–1779. No se anticipa la reincorporación de sus condados.')

def exclude(name,cells,start,end,source,reason):
 for cell in cells:R['overrides'].append({'territory':name,'id':cell,'action':'remove','from':start,'through':end,'source':source['url'],'reason':reason})
exclude('Hungría real',ids('Nograd Balassagyarmat Salgotarjan'),1552,1685,BUDA,'Provincia otomana: una antigua adición urbana no restaura soberanía real.')
exclude('Hungría real',['Nagykanizsa'],1600,1689,BUDA,'Kanizsa no se devuelve con la caída de Buda: se recupera en 1690.')
exclude('Ocupación habsbúrgica de Transilvania',banat,1552,1555,TEMES,'La conquista de Temesvár en 1552 retira el Banato de la ocupación imperial.')
exclude('Transilvania',union(banat,ids('Ineu Zarand')),1566,1698,TRANS,'Pérdida de ámbitos occidentales: separar administración provincial otomana de vasallaje principesco.')
exclude('Transilvania',reg('Bihar'),1660,1698,TRANS,'Várad y Bihar dejan de pertenecer al ámbito del principado desde 1660.')

# The English crown administered separate French fiefs. Do not call all of
# Aquitaine an English kingdom or repaint Gascony after its fall in 1453.
EN = ss('The National Archives · French lands of the English kings','https://www.nationalarchives.gov.uk/help-with-your-research/research-guides/french-lands-english-kings/','Normandía, Ponthieu, Calais y Aquitania; registros administrativos separados. Calais 1347–1558; último dominio continental desde 1453.')
GAS = ss('The Gascon Rolls Project · edición de los registros originales C61','https://www.gasconrolls.org/en/edition/calendars/C61_86/chronological.html','Introducción y registros 1373–1374: pérdida de Poitou/Saintonge, dimisión de Eduardo de Woodstock en octubre de 1372 y contracción de Aquitania.')
PARIS = ss('The Gascon Rolls Project · Introducción histórica','https://www.gasconrolls.org/fr/the-project/historical-introduction/index.html','Tratados de París y Brétigny; autoridad ducal y soberanía superior francesa no equivalen a propiedad del reino inglés.')
FRA1429 = ss('BnF · Longnon, Francia 1429–1430','https://gallica.bnf.fr/ark:/12148/btv1b8446192m','Mapa de autoridades rivales: Normandía, Maine y París ocupados, dominios borgoñones separados. No colorear toda Francia por el tratado de Troyes.')
gascon=union(reg('Bordelais','Bazadais','Tursan'),['Bayonne','Mauleon'])
aquit1200=union(gascon,reg('Upper_Poitou','Lower_Poitou','Saintonge','Limousin','Perigord','Angouleme'))
aquit1360=union(aquit1200,reg('Agenais','Quercy','Rouergue'),['Tarbes'])
layer('Ducado de Aquitania',1200,1452,[v(1200,aquit1200,'Ducado angevino; señoríos interiores y homenaje francés diferenciados.'),v(1224,gascon,'Pérdida de Poitou; marco conservador de Guyena.'),v(1360,aquit1360,'Brétigny: ampliación regional de Aquitania.'),v(1373,gascon,'Reconquista francesa y contracción al ámbito gascón.'),v(1451,[],'Primera conquista francesa de Burdeos.'),v(1452,['Bordeaux'],'Retorno inglés local, antes de Castillon.')],[EN,GAS,PARIS],'Ducado de Aquitania/Guyena. Soberanía y control divergen durante confiscaciones y campañas: cortes regionales, no una frontera diaria. No atribuye todo Bearne ni Navarra a Inglaterra.',supersedes=['Plazas inglesas de Guyena'])
layer('Condado de Anjou',1200,1480,[v(1200,reg('Anjou'),'Condado angevino de Juan I.'),v(1204,reg('Anjou'),'Incorporación a la Corona francesa; identidad del feudo conservada.')],[EN,FRA1429],'Condado y, desde 1360, ducado de Anjou. Conserva identidad como apanage hasta su reunión a la Corona en 1480; un feudo no equivale a un Estado independiente.')
layer('Condado de Maine',1200,1203,[v(1200,reg('Lower_Maine','Upper_Maine'),'Dominio angevino continental.')],[EN],'Condado bajo el monarca inglés antes de las conquistas francesas.')
layer('Touraine angevina',1200,1203,[v(1200,reg('Touraine'),'Dominio angevino continental.')],[EN],'Touraine bajo Juan I; no se prolonga automáticamente después de 1204.')
calais=['Calais']
replacement('Plaza inglesa de Calais',1347,1557,[v(1347,calais,'Calais inglesa y marcha inmediata.')],[EN],'Celda de Calais: no se apropia de Boulogne ni de todo Artois. Guînes no tiene una celda separable en esta edición.')
layer('Francia · ocupación inglesa',1420,1435,[v(1420,ids('Paris Mantes Montmorency Brie_Comte_Robert Corbeil Melun Meaux Etampes Auneau Chartres Dreux Monfort_Lamaury'),'Administración anglofrancesa en París y su entorno.')],[FRA1429,EN],'Control anglofrancés local después de Troyes; no toda la Corona francesa ni los estados aliados de Borgoña.',condition='ocupación')
layer('Maine · ocupación inglesa',1425,1447,[v(1425,reg('Lower_Maine','Upper_Maine'),'Conquista y administración inglesa del Maine.')],[FRA1429,EN],'Ámbito regional ocupado; Anjou al sur mantiene gobierno distinto.',condition='ocupación')
GIB = ss('The National Archives · Royal Marines and Utrecht','https://blog.nationalarchives.gov.uk/happy-350th-anniversary-royal-marines/','Captura de Gibraltar en 1704; cesión a la Corona británica por Utrecht en 1713. La celda excede la ciudad y fortificaciones: aproximación regional.')
MIN = ss('Consorcio Militar de Menorca · Ocupación francesa','https://www.consorciomilitarmenorca.com/es/la-ocupacion-francesa-de-menorca-1756-1763/','Dominio francés 1756–1763, intercalado entre los dominios británicos. Conquista española de 1782 y nuevo dominio británico desde 1798.')
HAN = ss('Gobierno de Baja Sajonia · Ascenso de Hannover','https://www.niedersachsen.de/startseite/land_leute/die_geschichte/geschichte_des_landes_niedersachsen/entstehung_des_absolutismus_und_aufstieg_kurhannovers/entstehung-des-absolutismus-und-aufstieg-kurhannovers-19813.html','Unión personal de 1714, no incorporación a Gran Bretaña; Bremen-Verden adquirido en 1715, título ratificado en 1719; Bentheim prendado desde 1752.')
CELLE = ss('Municipio de Celle · Historia','https://www.celle.de/Stadt/%C3%9Cber-Celle/Stadtgeschichte/?La=1','Extinción de la rama de Celle y herencia en 1705; no adjudicar Lüneburg a Hannover desde 1692.')
layer('Gibraltar · ocupación anglo-neerlandesa',1704,1712,[v(1704,['Gibraltar'],'Ocupación de la plaza en nombre del pretendiente Carlos.')],[GIB],'Ocupación anglo-neerlandesa anterior a Utrecht. No se retroproyecta la cesión británica de 1713.',condition='ocupación')
layer('Gibraltar',1713,1800,[v(1713,['Gibraltar'],'Cesión de la ciudad, castillo, puerto y fortificaciones a Gran Bretaña.')],[GIB],'Gibraltar británica. La celda del SVG es más amplia que el territorio cedido por Utrecht; no acredita todo el Campo de Gibraltar.')
layer('Menorca británica',1713,1800,[v(1713,['Ciudadela_de_Menorca'],'Menorca cedida a Gran Bretaña.'),v(1756,[],'Conquista francesa.'),v(1763,['Ciudadela_de_Menorca'],'Restitución británica.'),v(1782,[],'Recuperación española.'),v(1798,['Ciudadela_de_Menorca'],'Nueva ocupación británica.')],[MIN,GIB],'Superficie insular de Menorca, no sólo Ciudadela. Gobierno británico interrumpido en 1756–1763 y 1782–1798.')
layer('Menorca · ocupación británica',1708,1712,[v(1708,['Ciudadela_de_Menorca'],'Ocupación aliada anterior a Utrecht.')],[MIN],'Ocupación aliada de la isla antes de la cesión de 1713.',condition='ocupación')
layer('Menorca francesa',1756,1762,[v(1756,['Ciudadela_de_Menorca'],'Ocupación y administración francesa.')],[MIN],'Ocupación francesa hasta la restitución de 1763.',condition='ocupación')
han1692=ids('Hanover Hamelin Neustadt_am_Rubenberge Burgdorf Gottingen Einbeck Hoya Nienburg Diepholz')
han1705=union(han1692,ids('Celle Luneburg Soltau Fallingbostel Winsen_Aller Isenhagen Gifhorn Meinersen Ebstorf Uelzen Luchow Dannenberg Harburg Winsen Lauenburg'))
han1715=union(han1705,ids('Stade Bremervorde Osterholz Zeven Verden Achim'))
layer('Electorado de Hannover',1692,1800,[v(1692,han1692,'Dignidad electoral: Calenberg y dominios asociados, sin Celle.'),v(1705,han1705,'Herencia de Lüneburg-Celle y dominios asociados.'),v(1715,han1715,'Adquisición de Bremen-Verden; ratificación sueca en 1719.')],[HAN,CELLE],'Electorado de Brunswick-Lüneburg, llamado Hannover. La unión personal británica no absorbe este Estado del Sacro Imperio. Se excluyen Bremen ciudad libre, Brunswick, Wolfenbüttel, Hildesheim y Osnabrück; Bentheim permanece pendiente por falta de celda separable.')
# France: preserve preceding dated review but repair entire feudal regions,
# documentary annexations and erroneous anticipations of the Pyrenees/Jersey.
french=next(e for e in C['replacements'] if e['name']=='Francia')
Ain=ss('Departamento de Ain · Chronologie','https://patrimoines.ain.fr/chronologie/liste/l-ain-en-dates-2/n%3A134','Tratado de Lyon de 1601: Bresse, Bugey, Valromey y Gex; Saluces permanece fuera de Francia.')
Avignon=ss('Archives municipales d’Avignon · Réunion à la France','https://www.expositions-archives.avignon.fr/du-mont-de-pi%C3%A9t%C3%A9-au-cr%C3%A9dit-municipal','Decreto de 14 de septiembre de 1791: Avignon y Comtat Venaissin.')
Lyon=ss('Académie de Lyon · Charte sapaudine, contexte historique','https://daac.ac-lyon.fr/docs/docs_charte_sapaudine/CONTEXTE%20HISTORIQUE%202.pdf','10 de abril de 1312: cesión del poder político y judicial del arzobispo al rey; no anticipar Lyon antes de esta fecha.')
FOIX=ss('IRHT · Carta de Roger IV para Lézat, 1244','https://telma-chartes.irht.cnrs.fr/chartae-galliae.php/112340','Título de conde de Foix y homenaje al abad: las jurisdicciones señoriales y eclesiásticas pueden coexistir dentro de una celda; el título no acredita toda propiedad local.')
FOIXEND=ss('Larousse · Comté de Foix','https://www.larousse.fr/encyclopedie/autre-region/Foix/119785','Reunión del condado a la Corona por Enrique IV en 1607, distinta de la unión de Bearne de 1620.')
BEARN=ss('Archives communales de Pau · Série EE, Occitanica','https://www.occitanica.eu/items/show/3279','Instituciones bearnesas y reunión a Francia en 1620; se separa el vizcondado de la Bigorra y de la Baja Navarra.')
CHAMP=ss('FranceArchives · La Champagne au temps des comtes','https://francearchives.gouv.fr/fr/actualite/1166490060','Principado de Champaña y Brie: matrimonio de 1284 e integración progresiva; culminación de los derechos en 1361. No se confunde con todas las diócesis de Champagne.')
ARM=ss('Treccani · Armagnac','https://www.treccani.it/enciclopedia/armagnac_(Enciclopedia-Italiana)/','Condado gascón, extinción de la casa en 1497 y reunión de los dominios a Francia en 1607; el título no implica todas las tierras del partido político armagnac.')
layer('Condado de Foix',1200,1606,[v(1200,['Foix','Pamiers','Mirepoix'],'Condado antes de la cruzada albigense.'),v(1209,['Foix','Pamiers'],'Mirepoix fuera del gobierno condal.')],[FOIX,FOIXEND],'Condado y jurisdicciones compartidas de Pamiers; no incluye todo el Pirineo oriental ni el vizcondado de Castellbó. La superficie sigue siendo regional aproximada.')
layer('Vizcondado de Bearne',1200,1619,[v(1200,['Pau','Orthez','Oloron'],'Superficie regional bearnesa.')],[BEARN],'Vizcondado de Bearne y sus instituciones; no incluye Tarbes/Bigorra, la Baja Navarra ni toda la cordillera por compartir nombre dinástico. Su reunión de 1620 es distinta de la incorporación de los feudos de 1607.')
layer('Condado de Champaña',1200,1360,[v(1200,union(reg('Champagne','Brie_Champenois'),ids('Chaumont Bar_Sur_Aube Joinville Epernay Vitry_En_Pertois')),'Champaña y Brie: ámbito condal aproximado, excluido Reims arzobispal.')],[CHAMP],'Condado feudal bajo soberanía superior francesa. El matrimonio de Juana y Felipe en 1284 no borra su mandato condal ni equivale por sí solo a extinguir todas las instituciones.')
layer('Condado de Armagnac',1200,1606,[v(1200,reg('Armagnac'),'Ámbito regional gascón del condado.')],[ARM],'Condado y señoríos gascones, separados del partido armagnac y del condado de Rodez. La superficie no reconstruye cada confiscación de los siglos XV y XVI.')

# Explicit area corrections. Grenoble, the Vercors and the eastern Pyrenees
# must be inspected geographically; we do not take every name in the HTML.
fra=[]
for item in french['versions']:
 year=item['from'];cells=set(item['ids']);cells.discard('Jersey')
 if year<1312:cells.discard('Lyon')
 if year<1349:cells.difference_update(ids('Grenoble Vienne Romans Valence Die Saint_Marceilin Vercors_Massif La_Mure Briancon Gap Dauphine_Alps2'))
 if year<1607:cells.difference_update(reg('Foix'));cells.discard('North_Eastern_Pyrenees1')
 if year<1659:cells.discard('North_Eastern_Pyrenees2')
 if year<1620:cells.difference_update(['Pau','Orthez','Oloron'])
 if year<1360:cells.difference_update(reg('Limousin'))
 if year<1607:cells.difference_update(reg('Armagnac'))
 if year>=1607:cells.update(['Foix','Pamiers','North_Eastern_Pyrenees1']);cells.update(reg('Armagnac'))
 if year>=1620:cells.update(['Pau','Orthez','Oloron'])
 if 1360<=year<1373:cells.difference_update(aquit1360)
 if year>=1312:cells.add('Lyon')
 if year>=1601:cells.update(reg('Bresse'))
 if year>=1674:cells.update(['Besancon','Saint_Claude'])
 if year>=1791:cells.update(['Avignon'])
 fra.append(v(year,cells,item.get('event','Continuidad de la superficie regional revisada.')))
# Add dated events inside intervals, preserving all later changes.
for year,add,event in [(1312,['Lyon'],'Lyon rejoint la Couronne.'),(1373,reg('Upper_Poitou','Lower_Poitou','Saintonge','Limousin','Perigord','Angouleme','Quercy','Rouergue'),'Reconquistas tras la contracción inglesa.'),(1601,reg('Bresse'),'Lyon: Bresse, Bugey y Gex.'),(1607,union(['Foix','Pamiers','North_Eastern_Pyrenees1'],reg('Armagnac')),'Reunión de los dominios patrimoniales franceses de Enrique IV.'),(1620,['Pau','Orthez','Oloron'],'Unión de Bearne, distinta de los feudos de 1607.'),(1791,['Avignon'],'Reunión de Avignon y Comtat.')]:
 previous=next(x for x in reversed(sorted(fra,key=lambda x:x['from'])) if x['from']<=year)
 fra.append(v(year,union(previous['ids'],add),event))
fra.sort(key=lambda x:x['from'])
replacement('Francia',1200,1800,fra,[*french['sources'],EN,GAS,Ain,Avignon,Lyon,FOIXEND,BEARN,ARM],french['note']+' Se retiran Jersey, Foix (hasta 1607), Bearne (hasta 1620) y Lyon anticipados; Brétigny pierde también Poitou y Rouergue. Bresse/Bugey/Gex se integran desde 1601, Besançon y el contorno comtois desde 1674, la celda regional de Avignon desde 1791 (no separa todo el Comtat). Bélgica y el Rin revolucionarios se mantienen en capas fechadas aparte; no se importan estados suizos o alemanes del HTML.')
R['limitations'].append('Las atribuciones feudales francesas anteriores a 1453 siguen distinguiendo el dominio del rey de los feudos. No se presenta una frontera única e inmóvil durante la Guerra de los Cien Años.')
east=next(e for e in R['replacements'] if e['name']=='Núcleo oriental de Zápolya')
east['supersedes']=['Transilvania medieval']
east['authorityCondition']='control disputado'
for e in R['replacements']+R['territories']:
 e['versions']=sorted({x['from']:x for x in e['versions']}.values(),key=lambda x:x['from'])
exclude('Castilla',['Gibraltar'],1704,1800,GIB,'Ocupación aliada desde 1704 y cesión británica desde 1713.')
exclude('Mallorca',['Ciudadela_de_Menorca'],1708,1781,MIN,'Interrumpir la autoridad española durante los dominios británico y francés de Menorca.')
exclude('Mallorca',['Ciudadela_de_Menorca'],1798,1800,MIN,'Nueva ocupación británica de Menorca desde 1798.')
svg_ids={e.attrib.get('id') for e in ET.parse(H/'euv-locations-crop.svg').getroot().iter()}
missing=sorted({x for e in R['replacements']+R['territories'] for z in e['versions'] for x in z['ids']} - svg_ids)
if missing:raise ValueError('Unknown geometry: '+', '.join(missing))
(H/'frontier-review.json').write_text(json.dumps(R,ensure_ascii=False,indent=2)+'\n')
print('Frontier review:',len(R['replacements']),'replacements,',len(R['territories']),'new layers')
