const fuentes=['https://www.treccani.it/'];
export const CASAS_ALPINAS={
 'Saboya':{resumen:'Una casa alpina cuyas ramas enlazan los condados medievales, el ducado y las coronas mediterráneas.',origen:'La casa se formó alrededor de dominios alpinos que crecieron mediante herencias, concesiones y matrimonios. Su identidad dinástica sobrevivió a cambios de rango y a repartos patrimoniales.',trayectoria:'Los descendientes de Tomás I permiten distinguir la línea condal y los patrimonios de sus hermanos. Más tarde, las bodas con Borgoña, Chipre, Francia y los Habsburgo ampliaron su red. La elevación ducal de 1416 y el traslado de la capital a Turín cambiaron su posición política.',legado:'La rama ducal alcanzó las coronas de Sicilia y Cerdeña. En 1831 la sucesión sarda pasó a Carlos Alberto, de Saboya-Carignano: una rama colateral de la misma familia.',territorios:['Saboya','Piamonte','Sicilia','Cerdeña'],protagonistas:['TOMAS1SAB','AMEDEO5SAB','AMEDEO8SAB','ANACIPROSAB','EMANUELFILIBERTOSAB','VICTORAMADEO2SAB'],fuentes},
 'Saboya-Carignano':{resumen:'La rama de Tomás Francisco conservó una identidad propia durante generaciones antes de llegar al trono sardo.',origen:'Tomás Francisco, hijo menor de Carlos Manuel I y Catalina Micaela, dio origen a los príncipes de Carignano. Su matrimonio con María de Borbón-Soissons añadió una conexión francesa.',trayectoria:'La rivalidad de Tomás con la regencia de Cristina de Francia situó a la rama dentro de una guerra dinástica e internacional. Manuel Filiberto Amadeo continuó la línea, que mantuvo sus propios matrimonios y patrimonio.',legado:'Carlos Alberto heredó la corona sarda en 1831 al terminar la línea reinante. La distancia entre el fundador y ese acceso se comprende siguiendo varias generaciones, sin convertir a todos los príncipes de Carignano en duques de Saboya.',territorios:['Saboya','Piamonte','Cerdeña'],protagonistas:['TOMASFRANCISCOSAB','EMANUELFILIBERTOCAR','VICTORAMADEO1CAR','CARLOSALBERTOSAB'],fuentes},
 'Paleólogo-Monferrato':{resumen:'Una herencia transmitida desde una emperatriz bizantina creó una rama italiana de los Paleólogos.',origen:'Teodoro I era hijo de Andrónico II y de Irene de Monferrato. Los derechos de su madre lo llevaron al marquesado tras la extinción masculina de los Aleramici.',trayectoria:'Las generaciones de Juan II y Teodoro II enlazaron con Mallorca; las de Juan Jacobo, Guillermo VIII y Bonifacio III se entrelazaron con Saboya y Saluzzo. El parentesco convivió con enfrentamientos por territorios y derechos feudales.',legado:'La muerte de Juan Jorge en 1533 abrió la herencia. La resolución favorable a los Gonzaga en 1536 se apoyó en Margarita Paleólogo, esposa de Federico II. Fue una transmisión patrimonial, no una rama masculina de los Gonzaga surgida de los Paleólogos.',territorios:['Monferrato','Saluzzo','Saboya','Mantua'],protagonistas:['TEODORO1MON','JUAN2MONFERRATO','TEODORO2MON','BIANCAMONSAB','MARGPALEO'],fuentes},
 'Saluzzo':{resumen:'Un linaje alerámico que defendió su marquesado entre las presiones de Saboya y la protección francesa.',origen:'Los marqueses descendían de Manfredo, hijo de Bonifacio del Vasto. El reparto del patrimonio familiar y el desarrollo de Saluzzo como centro político dieron forma a una casa territorial propia.',trayectoria:'Beatriz de Saboya conecta a Manfredo III y Tomás I con Sicilia. En el siglo XV, el matrimonio de Ludovico I con Isabel de Monferrato vinculó de nuevo a las casas alpinas. Ludovico II y Margarita de Foix-Candale reforzaron la orientación francesa.',legado:'Las disputas entre los hijos de Ludovico II debilitaron el marquesado. Francia impuso su dominio en 1548; el territorio pasó a Saboya mediante el tratado de Lyon de 1601. Esta selección no presenta como completa la serie medieval de marqueses.',territorios:['Saluzzo','Monferrato'],protagonistas:['MANF3SAL','TOMAS1SAL','LUDOVICO1SAL','LUDOVICO2SAL','MARGFOIXSAL','MICHELEANTONIOSAL'],fuentes},
};
export const RAMAS_ALPINAS=[
 {id:'saboya-carignano',origen:'Saboya',destino:'Saboya-Carignano',tipo:'rama_cadete',periodo:'Siglo XVII',fundador:'TOMASFRANCISCOSAB',personas:['CARLOSEMANUEL1SAB','CATALINAMICAELAESP','TOMASFRANCISCOSAB','EMANUELFILIBERTOCAR'],texto:'Tomás Francisco, hijo menor de Carlos Manuel I, inicia la rama de Carignano. Su hijo Manuel Filiberto Amadeo continúa una línea distinta de la ducal, aunque ambas mantienen la misma ascendencia.'},
 {id:'paleologos-monferrato',origen:'Paleólogo',destino:'Paleólogo-Monferrato',tipo:'establecimiento',periodo:'1306–1310',fundador:'TEODORO1MON',personas:['ANDRO2','VIOLANTEMONBYZ','TEODORO1MON','JUAN2MONFERRATO','YOLANDAMONFERRATOSAB'],texto:'Teodoro establece una rama italiana de la familia imperial. Sus derechos a Monferrato proceden de su madre alerámica, Irene, y requieren reconocimiento y defensa política.'},
 {id:'monferrato-gonzaga',origen:'Paleólogo-Monferrato',destino:'Gonzaga',tipo:'continuidad_patrimonial',periodo:'1531–1536',fundador:'MARGPALEO',personas:['GUGL9MON','ANNAALENCONMON','MARGPALEO','FED2GONZAGA','GUILLERMOGONZAGA'],texto:'Margarita Paleólogo enlaza la herencia de Monferrato con Federico II Gonzaga. La boda de 1531 y la resolución imperial de 1536 son dos momentos diferentes de esa transmisión.'},
 {id:'saluzzo-saboya-sicilia',origen:'Saboya',destino:'Saluzzo',tipo:'continuidad_patrimonial',periodo:'Siglo XIII',fundador:'TOMAS1SAL',personas:['AMEDEO4SAB','BEATSAB','MANF3SAL','TOMAS1SAL'],texto:'Tomás I es hijo de Manfredo III de Saluzzo y Beatriz de Saboya. El segundo matrimonio de Beatriz con Manfredo de Sicilia crea una conexión familiar adicional; no convierte Saluzzo en una rama masculina de los Saboya.'},
].map(r=>({...r,fuentes}));
