const fuentes=['https://fmg.ac/Projects/MedLands/index.htm','https://www.britannica.com/'];
export const CASAS_ESCANDINAVAS = {
 Estridsen:{resumen:'La última generación de la antigua casa danesa llevó sus derechos a Noruega, Mecklemburgo y la unión de Kalmar.',
 origen:'La casa toma su denominación de Estrid y de la descendencia de Svend II. Esta ficha se concentra en las conexiones tardomedievales presentes en el Atlas, sin presentar como completa toda la sucesión danesa anterior.',
 trayectoria:'Ingeborg, hija de Erik IV, fue madre de los reyes noruegos Erik II y Haakon V. Más tarde, las hijas de Valdemar IV abrieron dos vías distintas: Margarita tuvo a Olaf con Haakon VI; su hermana Ingeborg se casó con Enrique de Mecklemburgo y fue abuela de Erik de Pomerania.',
 legado:'La muerte de Olaf no extinguió los vínculos familiares. Margarita promovió a Erik, descendiente de su hermana, y preservó su propia autoridad. El cambio de casa del monarca no convierte a Grifo en una rama masculina de Estridsen.',territorios:['Dinamarca','Noruega','Suecia'],protagonistas:['ERIK4DEN','INGEBORGERIKNOR','VALDEMAR4DIN','INGEBORGVALDEMAR','MARGARITA1NORD','OLAF2NORD'],fuentes},
 'Bjälbo':{resumen:'La familia de Birger jarl enlazó la monarquía sueca con Noruega y, por sus hijas y matrimonios, con Mecklemburgo y Dinamarca.',
 origen:'La casa de Bjälbo, llamada tradicionalmente Folkung en parte de la bibliografía, accedió a la realeza sueca con los hijos de Birger jarl. La denominación familiar no debe confundirse con todos los grupos políticos que recibieron el nombre Folkung.',
 trayectoria:'Los conflictos entre los hijos de Magnus III llevaron a la caída de Birger. Magnus, hijo de Erik Magnusson e Ingeborg de Noruega, heredó Noruega y fue elegido en Suecia. Su hermana Eufemia enlazó la familia con Mecklemburgo; su hijo Haakon VI se casó con Margarita de Dinamarca.',
 legado:'Olaf, hijo de Haakon y Margarita, murió sin descendencia. La continuidad de las uniones pasó a otras casas, aunque los vínculos de Bjälbo siguieron presentes en sus genealogías. Los distintos accesos por elección, herencia y matrimonio se muestran por separado.',territorios:['Suecia','Noruega','Dinamarca','Mecklemburgo'],protagonistas:['BIRGERJARL','MAGNUS3SUE','ERICMAGNUSSONSUE','MAGNUS4SUE','EUPHEMIASUE','HAAKON6NOR','OLAF2NORD'],fuentes},
 Oldemburgo:{resumen:'Una casa condal alemana que reunió Dinamarca y Noruega, disputó Suecia y se dividió en numerosas ramas ducales.',
 origen:'Cristian I procedía de los condes de Oldemburgo. Su elección danesa en 1448 abrió una nueva etapa dinástica tras la muerte de Cristóbal de Baviera. El matrimonio con la reina viuda Dorotea de Brandeburgo conectó ambas cortes, pero no fue por sí solo la causa jurídica de todas sus coronas.',
 trayectoria:'Cristian reunió Noruega y reinó durante unos años en Suecia. Sus hijos Juan y Federico mantuvieron posiciones diferentes dentro del conjunto familiar. La deposición de Cristian II llevó al trono a su tío Federico I, mientras Suecia eligió a Gustavo Vasa. Bajo Cristian III, la Reforma transformó las instituciones de Dinamarca y Noruega.',
 legado:'Las ramas de Schleswig-Holstein y sus derivaciones prolongaron la presencia de la familia en distintas monarquías europeas. En 1814 se separó Noruega del gobierno danés. Ese final de una unión no significó la extinción de la casa ni de sus ramas.',territorios:['Dinamarca','Noruega','Suecia','Oldemburgo'],protagonistas:['DIETRICHOLD','HELVIGSCHAU','CRISTIAN1NORD','JUAN2NORD','CRISTIAN2DIN','FRED1DEN','CHRISTIAN3DEN','FRED6DEN'],fuentes},
 Vasa:{resumen:'De la nobleza sueca a dos monarquías: la casa enlaza la ruptura de Kalmar con la unión y separación de Suecia y Polonia.',
 origen:'Gustavo Vasa procedía de una familia de la nobleza sueca. La ejecución de su padre Erik Johansson en 1520 y la rebelión contra Cristian II forman parte del contexto de su ascenso. Su elección como rey en 1523 no fue una herencia regia paterna.',
 trayectoria:'Los hijos de Gustavo gobernaron con conflictos entre sí. Juan III se casó con Catalina Jagellón: su hijo Segismundo fue elegido rey de Polonia y heredó Suecia. La oposición dirigida por Carlos, hermano de Juan, acabó apartándolo del trono sueco. Las dos ramas conservaron reclamaciones e intereses enfrentados.',
 legado:'La abdicación de Cristina en 1654 abrió paso a Carlos X Gustavo, hijo de Catalina Vasa y Juan Casimiro del Palatinado. El cambio a Wittelsbach mantuvo una conexión familiar por línea femenina. La rama polaca continuó hasta la abdicación de Juan Casimiro en 1668.',territorios:['Suecia','Polonia','Lituania'],protagonistas:['ERIKJOHVASA','CECILIAMANSDOTTER','GUSTAV1VASA','JUAN3SUECIA','CATALINAJAG','SEGIS3VASA','CARLOS9SUE','CATALINASUEVASA'],fuentes},
};
export const CONEXIONES_ESCANDINAVAS = [
 {id:'bjalbo-noruega',origen:'Sverre',destino:'Bjälbo',tipo:'continuidad_patrimonial',periodo:'1319',fundador:'MAGNUS4SUE',personas:['HAAKON5NOR','INGEBORGNORUEGA','ERICMAGNUSSONSUE','MAGNUS4SUE'],texto:'Magnus heredó Noruega a través de Ingeborg, hija de Haakon V. La casa del padre, Bjälbo, recibió una herencia procedente de la madre.'},
 {id:'estridsen-grifo',origen:'Estridsen',destino:'Grifo',tipo:'continuidad_patrimonial',periodo:'1389–1397',fundador:'ERICOPOMERANIA',personas:['INGEBORGVALDEMAR','MARIAMECKPOM','ERICOPOMERANIA','MARGARITA1NORD'],texto:'Erik descendía de Ingeborg, hermana de Margarita. La promoción y las elecciones de Erik hicieron efectiva esa conexión; Grifo no era una rama masculina de Estridsen.'},
 {id:'oldemburgo-coronas',origen:'Oldemburgo',destino:'Oldemburgo',tipo:'acceso_corona',periodo:'1448–1457',fundador:'CRISTIAN1NORD',personas:['CRISTIAN1NORD','DOROTHEABRAND','JUAN2NORD','FRED1DEN'],texto:'Cristian accedió sucesivamente a Dinamarca, Noruega y Suecia. La casa condal mantuvo su identidad y cada reino conservó su propia elección y cronología.'},
 {id:'vasa-polonia',origen:'Jagellón',destino:'Vasa',tipo:'acceso_corona',periodo:'1587–1592',fundador:'SEGIS3VASA',personas:['CATALINAJAG','JUAN3SUECIA','SEGIS3VASA'],texto:'La ascendencia Jagellón por Catalina apoyó la candidatura de Segismundo en Polonia; su acceso dependió de una elección. La corona sueca le llegó después por Juan III.'},
 {id:'vasa-wittelsbach',origen:'Vasa',destino:'Wittelsbach',tipo:'continuidad_patrimonial',periodo:'1654',fundador:'CARLOS10GUSTAVO',personas:['CARLOS9SUE','CATALINASUEVASA','JUANCASIMIROPALZWEI','CARLOS10GUSTAVO'],texto:'Carlos X Gustavo era nieto de Carlos IX por Catalina Vasa. Sucedió a Cristina tras su designación como heredero y la abdicación de ella; la rama paterna pertenecía a Wittelsbach.'},
].map(r=>({...r,fuentes}));
