import React from 'react';
import {ShieldCheck} from 'lucide-react';
import SiteHeader from '../components/SiteHeader.jsx';
import SiteFooter from '../components/SiteFooter.jsx';
import {usePublicMeta} from './PublicSite.jsx';
import {SITE} from '../i18n.jsx';
import {SUPPORT_URL} from '../siteConfig.js';
import './public.css';

export default function PrivacyPage({locale='es'}) {
 const en=locale==='en',path=en?'/en/privacy':'/es/privacidad';
 const title=en?'Privacy':'Privacidad';
 usePublicMeta({title:`${title} — ${en?'The Tree of Europe':'El Árbol de Europa'}`,description:en?'How this site handles browser data, performance metrics and correction emails.':'Cómo trata este sitio los datos del navegador, las métricas de rendimiento y los correos de corrección.',path});
 const contact=<a href={`mailto:${SITE.contactEmail}`}>{SITE.contactEmail}</a>;
 return <div className="public-site"><SiteHeader locale={locale} pathname={path}/><main className="public-main public-info-page privacy-page">
  <nav className="public-breadcrumbs" aria-label={en?'Breadcrumb':'Migas de pan'}><a href={en?'/en/':'/es/'}>{en?'Home':'Inicio'}</a><span aria-hidden="true">›</span><span aria-current="page">{title}</span></nav>
  <header className="public-page-title"><div className="public-page-icon"><ShieldCheck size={22}/></div><span>{en?'Your data':'Tus datos'}</span><h1>{en?'Privacy and local data':'Privacidad y datos locales'}</h1><p>{en?'What happens when you browse the atlas, save progress or contact the project.':'Qué ocurre al navegar por el atlas, guardar progreso o contactar con el proyecto.'}</p></header>
  <div className="privacy-content">
   <section><h2>{en?'Who is responsible?':'¿Quién es responsable?'}</h2><p>{en?'The Tree of Europe is maintained by Manuel Muriel Cagigal. For privacy requests, write to ':'El Árbol de Europa lo mantiene Manuel Muriel Cagigal. Para cuestiones de privacidad, escribe a '}{contact}.</p></section>
   <section><h2>{en?'Data stored in your browser':'Datos guardados en tu navegador'}</h2><p>{en?'Favourites, reading and challenge progress, atlas layout and display settings are stored in your browser’s local storage. The small-screen recommendation is remembered for this browsing session. These entries are not sent to the project. You can clear favourites and progress in Settings, and clear all site data in your browser.':'Favoritos, progreso de lectura y del desafío, disposición del Atlas y ajustes de visualización se guardan en el almacenamiento local de tu navegador. La recomendación para pantallas pequeñas se recuerda durante esta sesión. Estos datos no se envían al proyecto. Puedes borrar favoritos y progreso en Configuración, o todos los datos del sitio desde el navegador.'}</p></section>
   <section><h2>{en?'Performance and hosting':'Rendimiento y alojamiento'}</h2><p>{en?'The site runs on Vercel. Its Speed Insights service receives anonymous performance measurements such as page path, browser, device type and load time. The site removes URL query parameters before sending a measurement. Vercel also processes technical requests and security logs needed to serve the site.':'El sitio se aloja en Vercel. Speed Insights recibe mediciones anónimas de rendimiento, como la ruta de la página, el navegador, el tipo de dispositivo y el tiempo de carga. El sitio elimina los parámetros de la URL antes de enviar cada medición. Vercel también trata solicitudes técnicas y registros de seguridad necesarios para servir la web.'} <a href="https://vercel.com/docs/speed-insights/privacy-policy" target="_blank" rel="noreferrer">{en?'Speed Insights privacy details':'Privacidad de Speed Insights'}</a>.</p></section>
   <section><h2>{en?'Correction messages':'Mensajes de corrección'}</h2><p>{en?'The correction link opens your own email app; the site does not send a form or message automatically. If you choose to write, the project receives the address and content you send and uses them to answer and review your correction. The legal basis is the legitimate interest in answering requests and improving historical accuracy. Messages are kept only while needed for that purpose and any applicable legal obligations.':'El enlace para corregir datos abre tu propia aplicación de correo; la web no envía formularios ni mensajes automáticamente. Si decides escribir, el proyecto recibe la dirección y el contenido que envíes y los utiliza para responder y revisar tu corrección. La base jurídica es el interés legítimo en atender solicitudes y mejorar la exactitud histórica. Los mensajes se conservan solo mientras sean necesarios para ese fin y para las obligaciones legales aplicables.'}</p></section>
   <section><h2>{en?'Your choices and rights':'Tus opciones y derechos'}</h2><p>{en?'You can use the site without creating an account. Browser storage can be deleted locally. To ask about access, correction or deletion of personal data in a message you sent, contact ':'Puedes usar el sitio sin crear una cuenta. Puedes eliminar los datos locales desde tu navegador. Para solicitar acceso, rectificación o supresión de datos personales incluidos en un mensaje que enviaste, contacta mediante '}{contact}. {en?'You may also complain to your data protection authority.':'También puedes presentar una reclamación ante la autoridad de protección de datos.'} <a href="https://www.aepd.es/" target="_blank" rel="noreferrer">AEPD</a>.</p></section>
   <section><h2>{en?'Optional support through Ko-fi':'Apoyo voluntario mediante Ko-fi'}</h2><p>{en?'The support link opens Ko-fi in a new tab. This website does not embed Ko-fi widgets, load its scripts or collect payment details. Simply browsing the atlas does not connect you to Ko-fi. If you choose to contribute, Ko-fi and the payment provider process your information under their own policies.':'El enlace de apoyo abre Ko-fi en otra pestaña. Esta web no incorpora widgets de Ko-fi, no carga sus scripts ni recoge datos de pago. Navegar por el atlas no te conecta con Ko-fi. Si decides aportar, Ko-fi y el proveedor de pago tratan tu información conforme a sus propias políticas.'}</p><p>{en?'The project may receive your name, email, message and transaction details through those services, but not your full card details. These records are used to manage contributions, answer related requests and meet applicable legal obligations, and are retained only as needed for those purposes. Contributing is optional and does not unlock exclusive access. For privacy requests about these records, contact ':'El proyecto puede recibir tu nombre, correo, mensaje y detalles de la operación a través de esos servicios, pero no los datos completos de tu tarjeta. Esos registros se utilizan para gestionar las aportaciones, atender consultas relacionadas y cumplir las obligaciones legales aplicables, y se conservan solo mientras sean necesarios para esos fines. Aportar es opcional y no desbloquea acceso exclusivo. Para cuestiones de privacidad sobre estos registros, escribe a '}{contact}.</p><p><a href={SUPPORT_URL} target="_blank" rel="noopener noreferrer">{en?'Project on Ko-fi':'El proyecto en Ko-fi'}</a> · <a href="https://more.ko-fi.com/privacy" target="_blank" rel="noopener noreferrer">{en?'Ko-fi privacy policy':'Privacidad de Ko-fi'}</a> · <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer">{en?'Stripe privacy policy':'Privacidad de Stripe'}</a></p></section>
   <section><h2>{en?'External links':'Enlaces externos'}</h2><p>{en?'External sources, MapChart and GitHub have their own privacy practices when you visit them.':'Las fuentes externas, MapChart y GitHub aplican sus propias políticas de privacidad cuando visitas sus páginas.'}</p></section>
  </div>
 </main><SiteFooter locale={locale}/></div>;
}
