export const EVENTOS_HISTORICOS = [
  { id: "MAGNA_CARTA", anio: 1215, titulo: "Magna Carta", categoria: "politica", descripcion: "Juan de Inglaterra acepta la Magna Carta, un hito en la limitación pactada del poder regio." },
  { id: "CONSTANTINOPLA_1261", anio: 1261, titulo: "Restauración bizantina de Constantinopla", categoria: "politica", descripcion: "Miguel VIII Paleólogo recupera Constantinopla y restaura el Imperio bizantino bajo la dinastía Paleólogo." },
  { id: "VISPERAS_SICILIANAS", anio: 1282, titulo: "Vísperas Sicilianas", categoria: "guerra", descripcion: "La rebelión siciliana rompe el dominio angevino de la isla y abre una larga disputa mediterránea con la Corona de Aragón." },
  { id: "AVINON", desde: 1309, hasta: 1377, titulo: "Papado de Aviñón", categoria: "religion", descripcion: "La residencia pontificia se establece en Aviñón durante gran parte del siglo XIV." },
  { id: "CIEN_ANOS", desde: 1337, hasta: 1453, titulo: "Guerra de los Cien Años", categoria: "guerra", descripcion: "Conflicto dinástico y territorial prolongado entre las coronas de Inglaterra y Francia." },
  { id: "PESTE_NEGRA", desde: 1347, hasta: 1351, titulo: "Peste Negra en Europa", categoria: "sociedad", descripcion: "La gran epidemia de peste transforma profundamente la demografía, la economía y la sociedad europeas." },
  { id: "BULA_ORO", anio: 1356, titulo: "Bula de Oro", categoria: "politica", descripcion: "Carlos IV fija principios duraderos para la elección del rey de Romanos dentro del Sacro Imperio." },
  { id: "BORGO_1363", anio: 1363, titulo: "Felipe el Atrevido recibe Borgoña", categoria: "dinastia", personas: ["FEL2BORG", "JUAN2FRA"], descripcion: "Juan II de Francia entrega el ducado de Borgoña a su hijo Felipe, origen de la rama Valois-Borgoña." },
  { id: "BORGO_1369", anio: 1369, titulo: "Matrimonio de Felipe y Margarita de Flandes", categoria: "dinastia", personas: ["FEL2BORG", "MARGFLAN"], descripcion: "El matrimonio con Margarita de Flandes prepara la unión de Borgoña con ricos territorios flamencos y borgoñones." },
  { id: "CISMA_OCCIDENTE", desde: 1378, hasta: 1417, titulo: "Cisma de Occidente", categoria: "religion", descripcion: "Distintos obediencias papales compiten por la legitimidad de la Iglesia latina." },
  { id: "ALJUBARROTA", anio: 1385, titulo: "Batalla de Aljubarrota", categoria: "guerra", descripcion: "La victoria portuguesa consolida la dinastía de Avís y la independencia del reino frente a Castilla." },
  { id: "NICOPOLIS", anio: 1396, titulo: "Batalla de Nicópolis", categoria: "guerra", descripcion: "Una gran cruzada europea es derrotada por el Imperio otomano en los Balcanes." },
  { id: "AGINCOURT", anio: 1415, titulo: "Batalla de Agincourt", categoria: "guerra", descripcion: "Enrique V de Inglaterra obtiene una gran victoria sobre el ejército francés durante la Guerra de los Cien Años." },
  { id: "MONTEREAU", anio: 1419, titulo: "Asesinato de Juan Sin Miedo", categoria: "dinastia", personas: ["JUAN1BORG", "FEL3BORG"], descripcion: "Juan Sin Miedo es asesinado en Montereau. Felipe el Bueno hereda Borgoña y se acerca al bando inglés." },
  { id: "TROYES", anio: 1420, titulo: "Tratado de Troyes", categoria: "politica", descripcion: "El tratado reconoce a Enrique V y a sus herederos como sucesores de Carlos VI de Francia." },
  { id: "ORLEANS", anio: 1429, titulo: "Liberación de Orleans", categoria: "guerra", descripcion: "La intervención de Juana de Arco contribuye al giro de la guerra a favor de Carlos VII de Francia." },
  { id: "TOISON_ORO", anio: 1430, titulo: "Fundación de la Orden del Toisón de Oro", categoria: "dinastia", personas: ["FEL3BORG", "ISABPORTBORG"], descripcion: "Felipe el Bueno funda la Orden del Toisón de Oro en el contexto de su matrimonio con Isabel de Portugal." },
  { id: "ARRAS_1435", anio: 1435, titulo: "Tratado de Arras", categoria: "politica", personas: ["FEL3BORG", "CARLOS7FRA"], descripcion: "Felipe el Bueno se reconcilia con Carlos VII y rompe su alianza con Inglaterra." },
  { id: "VARNA", anio: 1444, titulo: "Batalla de Varna", categoria: "guerra", descripcion: "La cruzada de Varna termina con una victoria otomana y la muerte del rey Vladislao III." },
  { id: "CONSTANTINOPLA_1453", anio: 1453, titulo: "Caída de Constantinopla", categoria: "guerra", descripcion: "Mehmed II conquista Constantinopla y pone fin al Imperio bizantino." },
  { id: "ROSAS", desde: 1455, hasta: 1487, titulo: "Guerra de las Dos Rosas", categoria: "guerra", descripcion: "Las ramas de Lancaster y York disputan la corona inglesa en una larga sucesión de conflictos dinásticos." },
  { id: "BORGO_1467", anio: 1467, titulo: "Carlos el Temerario hereda Borgoña", categoria: "dinastia", personas: ["CAR1BORG", "FEL3BORG"], descripcion: "Carlos el Temerario sucede a Felipe el Bueno e intenta consolidar un bloque territorial borgoñón entre Francia y el Imperio." },
  { id: "REYES_CATOLICOS", anio: 1469, titulo: "Matrimonio de Isabel de Castilla y Fernando de Aragón", categoria: "dinastia", descripcion: "La unión matrimonial enlaza las dos principales coronas de la península ibérica sin fusionarlas jurídicamente en un único reino." },
  { id: "NANCY_1477", anio: 1477, titulo: "Batalla de Nancy y muerte de Carlos el Temerario", categoria: "guerra", personas: ["CAR1BORG", "MARIABORG"], descripcion: "Carlos muere sin heredero varón. Su hija María recibe una herencia disputada inmediatamente por Luis XI de Francia." },
  { id: "BODA_MARIA_MAX", anio: 1477, titulo: "María de Borgoña se casa con Maximiliano", categoria: "dinastia", personas: ["MARIABORG", "MAXIM1"], descripcion: "El matrimonio vincula la herencia borgoñona con los Habsburgo y cambia el equilibrio político de Europa occidental." },
  { id: "BOSWORTH", anio: 1485, titulo: "Batalla de Bosworth", categoria: "guerra", descripcion: "La derrota y muerte de Ricardo III abre el camino al reinado de Enrique VII Tudor." },
  { id: "GRANADA_1492", anio: 1492, titulo: "Conquista de Granada", categoria: "guerra", descripcion: "La toma de Granada pone fin al último reino islámico peninsular de la Edad Media." },
  { id: "SENLIS_1493", anio: 1493, titulo: "Tratado de Senlis", categoria: "politica", personas: ["MAXIM1", "FEL1CAST"], descripcion: "El acuerdo devuelve Artois y el Franco Condado a la herencia de María de Borgoña, mientras el ducado de Borgoña permanece en manos francesas." },
  { id: "GUERRAS_ITALIA", desde: 1494, hasta: 1559, titulo: "Guerras Italianas", categoria: "guerra", descripcion: "Francia, España, el Imperio y numerosos estados italianos compiten por el control político de la península." },
  { id: "LUTERO_1517", anio: 1517, titulo: "Inicio simbólico de la Reforma luterana", categoria: "religion", descripcion: "La controversia iniciada por Martín Lutero desencadena una transformación religiosa y política de alcance europeo." },
  { id: "WORMS_1521", anio: 1521, titulo: "Dieta de Worms", categoria: "religion", descripcion: "Carlos V convoca la Dieta en la que Lutero es requerido para retractarse de sus escritos." },
  { id: "PAVIA_1525", anio: 1525, titulo: "Batalla de Pavía", categoria: "guerra", personas: ["CARLOS5"], descripcion: "Las fuerzas imperiales derrotan al ejército francés y capturan al rey Francisco I." },
  { id: "SACO_ROMA_1527", anio: 1527, titulo: "Saco de Roma", categoria: "guerra", personas: ["CARLOS5"], descripcion: "Tropas imperiales amotinadas saquean Roma durante las Guerras Italianas." },
  { id: "AUGSBURGO_1555", anio: 1555, titulo: "Paz de Augsburgo", categoria: "religion", personas: ["CARLOS5"], descripcion: "El acuerdo establece una solución política provisional a la división confesional dentro del Sacro Imperio." },
  { id: "ABDICACION_CARLOS", desde: 1555, hasta: 1556, titulo: "Abdicaciones de Carlos V", categoria: "dinastia", personas: ["CARLOS5", "FEL2ESP"], descripcion: "Carlos V reparte progresivamente sus dominios entre la rama española y la rama austríaca de los Habsburgo." },
  { id: "LEPANTO", anio: 1571, titulo: "Batalla de Lepanto", categoria: "guerra", descripcion: "La Liga Santa derrota a la flota otomana en una de las grandes batallas navales del Mediterráneo." },
  { id: "ARMADA_1588", anio: 1588, titulo: "Armada de 1588", categoria: "guerra", personas: ["FEL2ESP"], descripcion: "La expedición naval de Felipe II contra Inglaterra fracasa tras combates, problemas logísticos y temporales adversos." },
  { id: "TREINTA_ANOS", desde: 1618, hasta: 1648, titulo: "Guerra de los Treinta Años", categoria: "guerra", descripcion: "Una guerra inicialmente imperial y confesional se convierte en un conflicto europeo de gran escala." },
  { id: "WESTFALIA", anio: 1648, titulo: "Paz de Westfalia", categoria: "politica", descripcion: "Los tratados de 1648 ponen fin a la Guerra de los Treinta Años y reordenan múltiples relaciones políticas europeas." },

  { id: "COMPANIA_BLANCA_1363", anio: 1363, titulo: "La Compañía Blanca entra en la política italiana", categoria: "guerra", personas: ["HAWKWOOD"], descripcion: "Compañías de veteranos de la Guerra de los Cien Años, entre ellas la asociada a John Hawkwood, convierten la condotta mercenaria en una fuerza decisiva de la política italiana." },
  { id: "BARBIANO_1379", anio: 1379, titulo: "Alberico da Barbiano y la Compañía de San Jorge", categoria: "guerra", personas: ["ALBERICOBARB"], descripcion: "Alberico da Barbiano simboliza la consolidación de compañías de armas dirigidas por capitanes italianos, capaces de competir con las grandes compañías extranjeras." },
  { id: "LAQUILA_1424", anio: 1424, titulo: "L'Aquila: caída de Braccio da Montone", categoria: "guerra", personas: ["BRACCIOMONT", "FRAN1SFOR", "NICCPICC", "MUZIOSFOR"], descripcion: "La guerra de L'Aquila destruye el poder de Braccio da Montone y acelera el ascenso de una nueva generación de capitanes, entre ellos Francesco Sforza y Niccolò Piccinino." },
  { id: "CARMAGNOLA_1432", anio: 1432, titulo: "Venecia ejecuta a Carmagnola", categoria: "politica", personas: ["CARMAGNOLA"], descripcion: "La ejecución de Carmagnola muestra la tensión esencial del sistema: los estados necesitaban grandes capitanes, pero temían que sus intereses privados acabasen imponiéndose a los del empleador." },
  { id: "BODA_SFORZA_VISCONTI_1441", anio: 1441, titulo: "Francesco Sforza se casa con Bianca Maria Visconti", categoria: "dinastia", personas: ["FRAN1SFOR", "BLANMARVISC", "FELMARVISC"], descripcion: "El matrimonio introduce a un condotiero en la sucesión del ducado de Milán y demuestra hasta qué punto la fuerza militar podía transformarse en legitimidad dinástica." },
  { id: "SFORZA_DUQUE_1450", anio: 1450, titulo: "Francesco Sforza, duque de Milán", categoria: "dinastia", personas: ["FRAN1SFOR", "BLANMARVISC"], descripcion: "Francesco Sforza culmina la trayectoria más extraordinaria de un condotiero: de capitán mercenario a fundador de una dinastía ducal." },
  { id: "LODI_1454", anio: 1454, titulo: "Paz de Lodi", categoria: "politica", personas: ["FRAN1SFOR"], descripcion: "La paz entre Milán y Venecia inaugura un equilibrio italiano que reduce el espacio político para los grandes capitanes independientes y favorece ejércitos más controlados por los estados." },
  { id: "SENIGALLIA_1502", anio: 1502, titulo: "La trampa de Senigallia", categoria: "politica", personas: ["CESARBORJA", "VITELLOZZO"], descripcion: "César Borja elimina en Senigallia a varios capitanes que se habían rebelado contra él. El episodio, observado por Maquiavelo, resume el conflicto entre el príncipe territorial y los condotieros autónomos." },
  { id: "AGNADELLO_1509", anio: 1509, titulo: "Batalla de Agnadello", categoria: "guerra", personas: ["BARTALVIANO", "TRIVULZIO"], descripcion: "La derrota veneciana de Agnadello muestra a los condotieros dentro de guerras ya dominadas por grandes coaliciones internacionales y ejércitos de escala mucho mayor." },
  { id: "BANDENERE_1526", anio: 1526, titulo: "Muere Giovanni dalle Bande Nere", categoria: "guerra", personas: ["GIOVBANDENERE"], descripcion: "La muerte de Giovanni de' Medici tras ser herido por artillería se convirtió en un símbolo tardío del mundo de los grandes capitanes de ventura frente a una guerra cada vez más transformada por las armas de fuego." },

  { id: "LEONARDO_MILAN_1482", anio: 1482, titulo: "Leonardo entra al servicio de los Sforza", categoria: "cultura", personas: ["LEONARDODAVINCI", "LUDOVSFOR"], descripcion: "Leonardo se instala en Milán y desarrolla durante años una carrera al servicio de la corte de Ludovico Sforza." },
  { id: "DAMA_ARMINO_1490", anio: 1490, titulo: "La Dama del armiño", categoria: "cultura", personas: ["LEONARDODAVINCI", "CECIGALL", "LUDOVSFOR"], descripcion: "Leonardo retrata a Cecilia Gallerani, amante de Ludovico Sforza. En 1491 Cecilia dará a Ludovico un hijo, Cesare." },
  { id: "BIANCA_SFORZA_1496", anio: 1496, titulo: "Bianca Giovanna Sforza", categoria: "dinastia", personas: ["BIANSFOR", "LUDOVSFOR", "BERNACORR"], descripcion: "Bianca Giovanna, hija de Ludovico Sforza y Bernardina de Corradis, se casa con Galeazzo Sanseverino y muere ese mismo año. Una hipótesis minoritaria moderna la ha propuesto como modelo de la Gioconda." },
  { id: "LEONARDO_BORJA_1502", anio: 1502, titulo: "Leonardo al servicio de César Borja", categoria: "politica", personas: ["LEONARDODAVINCI", "CESARBORJA"], descripcion: "Leonardo trabaja como ingeniero militar para César Borja durante sus campañas en Italia central." },
  { id: "GIOCONDA_1503", anio: 1503, titulo: "Comienza la historia de la Gioconda", categoria: "cultura", personas: ["LEONARDODAVINCI", "LISAGHERARDINI", "FRANCESCOGIOCONDO"], descripcion: "La identificación tradicional y hoy dominante relaciona el retrato con Lisa Gherardini, esposa del mercader florentino Francesco del Giocondo." },
  { id: "LEONARDO_MILAN_1506", anio: 1506, titulo: "Leonardo regresa a Milán", categoria: "cultura", personas: ["LEONARDODAVINCI", "CHARLES2AMBOISE"], descripcion: "Leonardo vuelve a Milán bajo la protección del gobernador francés Charles II d'Amboise." },
  { id: "LEONARDO_ROMA_1513", anio: 1513, titulo: "Leonardo en la Roma de los Médici", categoria: "cultura", personas: ["LEONARDODAVINCI", "GIULIANOMEDICI", "PAPA_LEON10"], descripcion: "Leonardo se instala en Roma bajo la protección de Giuliano de' Medici durante el pontificado de León X." },
  { id: "LEONARDO_FRANCIA_1516", anio: 1516, titulo: "Francisco I llama a Leonardo a Francia", categoria: "cultura", personas: ["LEONARDODAVINCI", "FRAN1FRA", "FRANCESCOMELZI"], descripcion: "Leonardo se traslada a Francia acompañado por Francesco Melzi y entra en la órbita de Francisco I." },
  { id: "LEONARDO_MUERTE_1519", anio: 1519, titulo: "Muere Leonardo", categoria: "cultura", personas: ["LEONARDODAVINCI", "FRAN1FRA", "FRANCESCOMELZI"], descripcion: "Leonardo muere en Francia. La Gioconda permaneció con él hasta sus últimos años y acabó incorporándose a la colección real francesa." },
];

export const HISTORIAS = [
  {
    id: "borgona",
    titulo: "Borgoña: el reino que no fue",
    disponible: true,
    subtitulo: "De apanage francés a herencia Habsburgo",
    descripcion: "Un recorrido por cuatro generaciones Valois-Borgoña y el matrimonio que trasladó gran parte de su herencia a los Habsburgo.",
    pasos: [
      {
        anio: 1363,
        persona: "FEL2BORG",
        personas: ["FEL2BORG", "JUAN2FRA"],
        eventoId: "BORGO_1363",
        titulo: "Una nueva Borgoña Valois",
        texto: "Juan II de Francia confía el ducado de Borgoña a su hijo Felipe el Atrevido. Nace así una rama menor de los Valois que, en pocas generaciones, llegará a competir en poder con la propia monarquía francesa.",
      },
      {
        anio: 1369,
        persona: "MARGFLAN",
        personas: ["FEL2BORG", "MARGFLAN"],
        eventoId: "BORGO_1369",
        titulo: "La expansión empieza con un matrimonio",
        texto: "Felipe se casa con Margarita de Flandes. La alianza matrimonial abre la vía hacia Flandes, Artois y el Franco Condado: territorios ricos y estratégicos que convierten a los duques borgoñones en mucho más que señores de Dijon.",
      },
      {
        anio: 1404,
        persona: "JUAN1BORG",
        personas: ["JUAN1BORG", "FEL2BORG", "MARGFLAN"],
        titulo: "Juan Sin Miedo hereda el proyecto",
        texto: "A la muerte de Felipe el Atrevido, Juan Sin Miedo recibe un conglomerado territorial ya poderoso. Su política se entrelaza con la crisis interna francesa y con la rivalidad entre borgoñones y armagnacs.",
      },
      {
        anio: 1419,
        persona: "FEL3BORG",
        personas: ["JUAN1BORG", "FEL3BORG"],
        eventoId: "MONTEREAU",
        titulo: "Montereau cambia el equilibrio",
        texto: "Juan Sin Miedo es asesinado durante una negociación en Montereau. Su hijo Felipe el Bueno hereda el ducado y se aproxima al bando inglés, convirtiendo la enemistad con los Valois franceses en uno de los ejes de la Guerra de los Cien Años.",
      },
      {
        anio: 1430,
        persona: "FEL3BORG",
        personas: ["FEL3BORG", "ISABPORTBORG"],
        eventoId: "TOISON_ORO",
        titulo: "Una corte que quiere parecer una monarquía",
        texto: "Felipe el Bueno funda la Orden del Toisón de Oro. La corte borgoñona desarrolla una cultura política y ceremonial extraordinariamente ambiciosa, acorde con un estado que une territorios dispersos desde Borgoña hasta los Países Bajos.",
      },
      {
        anio: 1435,
        persona: "FEL3BORG",
        personas: ["FEL3BORG", "CARLOS7FRA"],
        eventoId: "ARRAS_1435",
        titulo: "Borgoña cambia de aliado",
        texto: "El Tratado de Arras reconcilia a Felipe el Bueno con Carlos VII. Borgoña abandona la alianza inglesa y obtiene importantes concesiones, mientras la monarquía francesa recupera margen para terminar la Guerra de los Cien Años.",
      },
      {
        anio: 1467,
        persona: "CAR1BORG",
        personas: ["CAR1BORG", "FEL3BORG"],
        eventoId: "BORGO_1467",
        titulo: "Carlos el Temerario y la obsesión territorial",
        texto: "Carlos el Temerario hereda uno de los estados más ricos de Europa. Su gran problema es geográfico: sus posesiones forman dos grandes bloques separados. Su política intenta unirlos y elevar su rango hasta crear, de hecho o de derecho, un reino borgoñón independiente.",
      },
      {
        anio: 1477,
        persona: "CAR1BORG",
        personas: ["CAR1BORG", "MARIABORG", "LUIS11FRA"],
        eventoId: "NANCY_1477",
        titulo: "Nancy: el proyecto se rompe",
        texto: "Carlos muere en la batalla de Nancy sin heredero varón. Luis XI ocupa el ducado de Borgoña y otros territorios franceses, mientras María, hija única de Carlos, debe defender el resto de la herencia de su padre.",
      },
      {
        anio: 1477,
        persona: "MARIABORG",
        personas: ["MARIABORG", "MAXIM1"],
        eventoId: "BODA_MARIA_MAX",
        titulo: "La herencia cambia de dinastía",
        texto: "María de Borgoña se casa con Maximiliano de Habsburgo. El matrimonio salva buena parte de los Países Bajos borgoñones y convierte una crisis sucesoria en el punto de partida de la gran rivalidad entre Francia y los Habsburgo.",
      },
      {
        anio: 1493,
        persona: "MAXIM1",
        personas: ["MAXIM1", "FEL1CAST"],
        eventoId: "SENLIS_1493",
        titulo: "Lo que queda de Borgoña",
        texto: "El Tratado de Senlis devuelve Artois y el Franco Condado a la herencia borgoñona de los Habsburgo. El antiguo ducado de Borgoña, sin embargo, permanece en Francia. El sueño territorial de Carlos ya no puede reconstruirse en su forma original.",
      },
      {
        anio: 1506,
        persona: "CARLOS5",
        personas: ["FEL1CAST", "CARLOS5"],
        titulo: "De Borgoña a Carlos V",
        texto: "Felipe el Hermoso transmite la herencia borgoñona a su hijo Carlos. Para Carlos V, los Países Bajos y la tradición cortesana borgoñona serán una parte esencial de su identidad política. El reino que Carlos el Temerario no consiguió fundar termina convertido en una de las bases del poder Habsburgo.",
      },
    ],
  },
  { id: "emperadores", titulo: "Emperadores", subtitulo: "Del interregno a la hegemonía Habsburgo", disponible: false },
  { id: "habsburgo-capetos", titulo: "Habsburgo y Capetos", subtitulo: "Dos redes dinásticas que moldearon Europa", disponible: false },
  { id: "iberia", titulo: "España y Portugal", subtitulo: "Castilla, Aragón, Portugal y sus uniones", disponible: false },
  { id: "papales", titulo: "Las familias papales", subtitulo: "Roma, nepotismo y estrategia dinástica", disponible: false },
  {
    id: "condotieros",
    titulo: "Los condotieros",
    subtitulo: "De las compañías de ventura al ducado de Milán",
    disponible: true,
    descripcion: "Un recorrido por los capitanes de fortuna que convirtieron la guerra en una profesión, negociaron con repúblicas y príncipes y, en el caso de los Sforza, transformaron el mando militar en poder dinástico.",
    pasos: [
      {
        anio: 1363,
        persona: "HAWKWOOD",
        personas: ["HAWKWOOD"],
        eventoId: "COMPANIA_BLANCA_1363",
        titulo: "La guerra se convierte en un mercado",
        texto: "Tras las grandes campañas de la Guerra de los Cien Años, compañías de veteranos cruzan los Alpes y venden su experiencia a ciudades y príncipes italianos. John Hawkwood, conocido en Italia como Giovanni Acuto, se convierte en uno de los capitanes extranjeros más célebres y en un modelo de condotiero político además de militar.",
      },
      {
        anio: 1379,
        persona: "ALBERICOBARB",
        personas: ["ALBERICOBARB", "HAWKWOOD"],
        eventoId: "BARBIANO_1379",
        titulo: "Los italianos aprenden el oficio",
        texto: "Alberico da Barbiano representa una nueva generación de capitanes italianos. La condotta ya no es solo la contratación de una compañía extranjera: empieza a surgir un sistema de escuelas militares, clientelas y lealtades personales alrededor de grandes jefes de armas.",
      },
      {
        anio: 1416,
        persona: "BRACCIOMONT",
        personas: ["BRACCIOMONT", "MUZIOSFOR"],
        titulo: "Bracceschi contra Sforzeschi",
        texto: "Braccio da Montone y Muzio Attendolo Sforza encarnan dos redes rivales de capitanes. Sus hombres no son simples soldados: aprenden tácticas, heredan contactos y forman auténticas genealogías profesionales que seguirán enfrentándose bajo sus discípulos.",
      },
      {
        anio: 1424,
        persona: "BRACCIOMONT",
        personas: ["BRACCIOMONT", "MUZIOSFOR", "FRAN1SFOR", "NICCPICC"],
        eventoId: "LAQUILA_1424",
        titulo: "1424: cambia una generación",
        texto: "Muzio Attendolo muere ahogado durante la campaña y Braccio cae en la guerra de L'Aquila. El relevo pasa a hombres como Francesco Sforza y Niccolò Piccinino. El sistema sobrevive a sus fundadores porque sus compañías, discípulos y alianzas ya forman parte estable de la política italiana.",
      },
      {
        anio: 1432,
        persona: "CARMAGNOLA",
        personas: ["CARMAGNOLA", "FELMARVISC"],
        eventoId: "CARMAGNOLA_1432",
        titulo: "El empleador también teme a su general",
        texto: "Carmagnola sirve primero a Milán y después a Venecia. Su carrera muestra la gran contradicción de la condotta: un capitán debía ser lo bastante poderoso para ganar guerras, pero cuanto más poderoso era, más peligroso resultaba para quien lo contrataba. Venecia acabó acusándolo de traición y lo ejecutó.",
      },
      {
        anio: 1438,
        persona: "NICCPICC",
        personas: ["NICCPICC", "FRAN1SFOR"],
        titulo: "Piccinino y Sforza: la guerra como carrera",
        texto: "Niccolò Piccinino, heredero militar de Braccio, y Francesco Sforza compiten al servicio de potencias que cambian de aliados con rapidez. La guerra lombarda convierte sus reputaciones, tropas y contratos en recursos políticos tan importantes como un título nobiliario.",
      },
      {
        anio: 1441,
        persona: "FRAN1SFOR",
        personas: ["FRAN1SFOR", "BLANMARVISC", "FELMARVISC"],
        eventoId: "BODA_SFORZA_VISCONTI_1441",
        titulo: "Una boda vale más que una victoria",
        texto: "Francesco Sforza se casa con Bianca Maria Visconti, hija de Filippo Maria. De pronto el capitán de fortuna posee algo que los contratos militares no podían darle por sí solos: una vía dinástica hacia Milán.",
      },
      {
        anio: 1450,
        persona: "FRAN1SFOR",
        personas: ["FRAN1SFOR", "BLANMARVISC"],
        eventoId: "SFORZA_DUQUE_1450",
        titulo: "El condotiero que se convierte en príncipe",
        texto: "En 1450 Francesco Sforza entra en Milán como duque. Es el triunfo máximo de la lógica condotiera: fuerza militar, negociación y matrimonio se combinan para fundar una dinastía que gobernará una de las principales potencias italianas.",
      },
      {
        anio: 1454,
        persona: "FRAN1SFOR",
        personas: ["FRAN1SFOR", "BARTCOLLEONI", "GATTAMELATA"],
        eventoId: "LODI_1454",
        titulo: "El éxito de Sforza cambia las reglas",
        texto: "La Paz de Lodi estabiliza el equilibrio entre los grandes estados italianos. Paradójicamente, el triunfo de Sforza sirve de advertencia: repúblicas y príncipes tienen ahora más razones para impedir que otro general mercenario acumule suficiente poder como para convertirse en soberano.",
      },
      {
        anio: 1474,
        persona: "FEDMONTE",
        personas: ["FEDMONTE", "SIGISMALAT", "BATTISTASFORZA"],
        titulo: "El condotiero renacentista",
        texto: "Federico da Montefeltro combina la profesión militar con el gobierno de Urbino y un mecenazgo cultural extraordinario. Su rivalidad con Sigismondo Pandolfo Malatesta recuerda que el condotiero podía ser simultáneamente general, príncipe, diplomático y constructor de una imagen pública cuidadosamente elaborada.",
      },
      {
        anio: 1502,
        persona: "CESARBORJA",
        personas: ["CESARBORJA", "VITELLOZZO"],
        eventoId: "SENIGALLIA_1502",
        titulo: "Senigallia: el príncipe contra sus capitanes",
        texto: "Vitellozzo Vitelli y otros condotieros temen que César Borja los absorba uno a uno y se rebelan. Borja aparenta reconciliarse con ellos, los atrae a Senigallia y elimina a sus dirigentes. El episodio muestra hasta qué punto el estado territorial busca ya domesticar o destruir la autonomía de los capitanes.",
      },
      {
        anio: 1509,
        persona: "BARTALVIANO",
        personas: ["BARTALVIANO", "TRIVULZIO"],
        eventoId: "AGNADELLO_1509",
        titulo: "Las Guerras Italianas cambian la escala",
        texto: "En Agnadello, Bartolomeo d'Alviano combate al servicio de Venecia frente a un ejército francés en el que también actúan capitanes italianos como Gian Giacomo Trivulzio. Desde 1494 la península es escenario de monarquías extranjeras, grandes contingentes de infantería y artillería: el viejo mercado militar italiano ya no domina por sí solo la guerra.",
      },
      {
        anio: 1526,
        persona: "GIOVBANDENERE",
        personas: ["GIOVBANDENERE", "CATASFOR", "GIOVPOPOLANO"],
        eventoId: "BANDENERE_1526",
        titulo: "Giovanni dalle Bande Nere: un final simbólico",
        texto: "Giovanni de' Medici, hijo de Caterina Sforza y Giovanni il Popolano, conserva el prestigio personal del gran capitán de ventura. Muere en 1526 después de ser herido por artillería. Su figura sirve como cierre simbólico de una época en la que el nombre de un capitán podía pesar casi tanto como el del estado que lo contrataba.",
      },
      {
        anio: 1535,
        persona: "FERRANTEGONZAGA",
        personas: ["FERRANTEGONZAGA", "FRAN2GONZAGA", "GIOVBANDENERE"],
        titulo: "Del capitán de ventura al servidor de una monarquía",
        texto: "Ferrante Gonzaga pertenece todavía al mundo de los grandes comandantes italianos, pero su carrera dentro de la estructura imperial de Carlos V señala otra dirección: el prestigio militar continúa, aunque cada vez más integrado en estados dinásticos, gobernaciones y ejércitos permanentes. El condotiero clásico deja paso al general de una potencia europea.",
      },
    ],
  },
  { id: "cien-anos", titulo: "La Guerra de los 100 Años", subtitulo: "Una disputa de coronas convertida en guerra secular", disponible: false },
  { id: "dos-rosas", titulo: "La Guerra de las Dos Rosas", subtitulo: "Lancaster, York y el ascenso Tudor", disponible: false },
  {
    id: "gioconda",
    titulo: "En busca de la Gioconda",
    subtitulo: "Leonardo, sus mecenas y las identidades propuestas para el retrato",
    disponible: true,
    descripcion: "Una investigación guiada por las cortes de Milán, Florencia, Roma y Francia para seguir a Leonardo y separar la identificación mejor documentada de las muchas candidatas propuestas para su retrato más famoso.",
    pasos: [
      {
        anio: 1482,
        persona: "LEONARDODAVINCI",
        personas: ["LEONARDODAVINCI", "LUDOVSFOR"],
        eventoId: "LEONARDO_MILAN_1482",
        titulo: "Antes de Lisa: Leonardo y la corte de Milán",
        texto: "Mucho antes de la Gioconda, Leonardo construye su carrera en la corte milanesa de Ludovico Sforza. Aquí trabaja como pintor, ingeniero, diseñador de fiestas y consejero técnico. Esta red de mecenas y retratadas será importante porque varias mujeres de la corte acabarán entrando, siglos después, en el catálogo de identidades propuestas para la Gioconda.",
      },
      {
        anio: 1490,
        persona: "CECIGALL",
        personas: ["CECIGALL", "LEONARDODAVINCI", "LUDOVSFOR"],
        eventoId: "DAMA_ARMINO_1490",
        titulo: "La Dama del armiño sí tiene nombre",
        texto: "Cecilia Gallerani, joven culta de la corte y amante de Ludovico Sforza, es identificada con enorme solidez como la modelo de la Dama del armiño. El animal funciona además como un juego de alusiones cortesanas relacionado con Ludovico. Este retrato demuestra que Leonardo ya dominaba el retrato psicológico femenino antes de la Gioconda.",
      },
      {
        anio: 1491,
        persona: "CESARESFORZAGALLERANI",
        personas: ["CECIGALL", "LUDOVSFOR", "CESARESFORZAGALLERANI"],
        titulo: "Una corrección importante: Cecilia tuvo un hijo",
        texto: "Cecilia Gallerani tuvo con Ludovico Sforza un hijo llamado Cesare en 1491. No fue la madre de Bianca Giovanna Sforza. La confusión es fácil porque Ludovico tuvo hijos con distintas amantes y varias mujeres de su entorno han sido asociadas posteriormente con Leonardo.",
      },
      {
        anio: 1496,
        persona: "BIANSFOR",
        personas: ["BIANSFOR", "LUDOVSFOR", "BERNACORR", "GALSANSEV"],
        eventoId: "BIANCA_SFORZA_1496",
        titulo: "La hija que sí entra en una teoría sobre la Gioconda",
        texto: "Bianca Giovanna Sforza era hija de Ludovico y de Bernardina de Corradis, no de Cecilia Gallerani. Murió muy joven en 1496. Una hipótesis moderna y minoritaria ha intentado identificarla con la mujer de la Gioconda. La incluimos porque forma parte de la historia del enigma, pero no tiene el peso documental de Lisa Gherardini.",
      },
      {
        anio: 1499,
        persona: "LEONARDODAVINCI",
        personas: ["LEONARDODAVINCI", "LUDOVSFOR"],
        titulo: "La caída de Milán rompe el mundo de Leonardo",
        texto: "La invasión francesa de Milán derrumba el poder de Ludovico Sforza. Leonardo abandona una corte en la que había pasado cerca de dos décadas. A partir de aquí su vida se vuelve mucho más itinerante y conecta con algunos de los personajes políticos más poderosos de Italia y Francia.",
      },
      {
        anio: 1502,
        persona: "CESARBORJA",
        personas: ["LEONARDODAVINCI", "CESARBORJA"],
        eventoId: "LEONARDO_BORJA_1502",
        titulo: "Leonardo, ingeniero del Valentino",
        texto: "Durante las campañas de César Borja, Leonardo trabaja como ingeniero e inspector de fortificaciones. Es una etapa breve pero reveladora: el pintor de retratos se mueve también en el corazón de la guerra y de la política de los Borgia.",
      },
      {
        anio: 1503,
        persona: "LISAGHERARDINI",
        personas: ["LISAGHERARDINI", "FRANCESCOGIOCONDO", "LEONARDODAVINCI"],
        eventoId: "GIOCONDA_1503",
        titulo: "La candidata principal: Lisa Gherardini",
        texto: "Lisa Gherardini era una florentina casada con el mercader Francesco del Giocondo. De ahí proceden los nombres Monna Lisa y Gioconda. La identificación aceptada por el Louvre y respaldada por la tradición documental vincula el retrato con Lisa; la obra habría comenzado hacia 1503, aunque Leonardo siguió trabajando en ella durante años.",
      },
      {
        anio: 1504,
        persona: "ISABELLAESTE",
        personas: ["ISABELLAESTE", "ISABNAP", "CATASFOR", "COSTANZADAVALOS", "BIANSFOR", "LEONARDODAVINCI"],
        titulo: "El desfile de candidatas",
        texto: "El misterio de la pintura ha producido numerosas identificaciones alternativas: Isabella d'Este, Isabella de Aragón, Caterina Sforza, Costanza d'Avalos y Bianca Giovanna Sforza, entre otras. Algunas tienen vínculos reales con Leonardo o con sus mecenas; eso no significa que todas las hipótesis tengan la misma fuerza. El recorrido las conserva como propuestas, no como equivalentes a la identificación de Lisa Gherardini.",
      },
      {
        anio: 1506,
        persona: "CHARLES2AMBOISE",
        personas: ["CHARLES2AMBOISE", "LEONARDODAVINCI"],
        eventoId: "LEONARDO_MILAN_1506",
        titulo: "Otra vez Milán, ahora bajo Francia",
        texto: "Leonardo vuelve a Milán, pero el tablero político ha cambiado. Charles II d'Amboise, gobernador francés, se convierte en uno de sus principales protectores. El artista continúa moviéndose entre arte, ingeniería y patronazgo cortesano mientras la Gioconda sigue en sus manos.",
      },
      {
        anio: 1513,
        persona: "GIULIANOMEDICI",
        personas: ["GIULIANOMEDICI", "PAPA_LEON10", "LEONARDODAVINCI"],
        eventoId: "LEONARDO_ROMA_1513",
        titulo: "Roma y los Médici",
        texto: "Leonardo pasa a Roma bajo la protección de Giuliano de' Medici, hermano del papa León X. Una noticia posterior llegó a vincular la ejecución de un retrato femenino con Giuliano; precisamente por eso el propio Louvre discute la tensión entre ese testimonio y la identificación tradicional con Lisa del Giocondo.",
      },
      {
        anio: 1516,
        persona: "FRAN1FRA",
        personas: ["FRAN1FRA", "LEONARDODAVINCI", "FRANCESCOMELZI"],
        eventoId: "LEONARDO_FRANCIA_1516",
        titulo: "El último mecenas: Francisco I",
        texto: "Francisco I invita a Leonardo a Francia. El maestro viaja acompañado por su discípulo Francesco Melzi y lleva consigo varias obras, entre ellas la Gioconda. El cuadro que quizá había empezado como un encargo privado florentino se convierte así en una pieza ligada a la corte francesa.",
      },
      {
        anio: 1519,
        persona: "LEONARDODAVINCI",
        personas: ["LEONARDODAVINCI", "FRAN1FRA", "LISAGHERARDINI", "CECIGALL", "BIANSFOR"],
        eventoId: "LEONARDO_MUERTE_1519",
        titulo: "Un retrato, muchas historias",
        texto: "Leonardo muere en 1519. La pintura termina en la colección real francesa y, con los siglos, su fama genera un enorme laberinto de interpretaciones. El resultado de nuestra búsqueda es desigual a propósito: Cecilia Gallerani es la Dama del armiño; Bianca Giovanna es hija de Ludovico y Bernardina y solo una candidata minoritaria para la Gioconda; la identificación mejor documentada del gran retrato sigue siendo Lisa Gherardini, esposa de Francesco del Giocondo.",
      },
    ],
  },
  { id: "revolucion-protestante", titulo: "La Revolución Protestante", subtitulo: "Erasmo, Lutero, Calvino, Enrique VIII, Carlos V y la respuesta de Trento", disponible: false },
];
