export const EVENTOS_HISTORICOS = [
  { id: "MAGNA_CARTA", anio: 1215, titulo: "Magna Carta", categoria: "politica", descripcion: "Juan de Inglaterra acepta la Magna Carta, un hito en la limitación pactada del poder regio." },
  { id: "CONSTANTINOPLA_1261", anio: 1261, titulo: "Restauración bizantina de Constantinopla", categoria: "politica", descripcion: "Miguel VIII Paleólogo recupera Constantinopla y restaura el Imperio bizantino bajo la dinastía Paleólogo." },
  { id: "VISPERAS_SICILIANAS", anio: 1282, titulo: "Vísperas Sicilianas", categoria: "guerra", descripcion: "La rebelión siciliana rompe el dominio angevino de la isla y abre una larga disputa mediterránea con la Corona de Aragón." },
  { id: "AVINON", desde: 1309, hasta: 1377, titulo: "Papado de Aviñón", categoria: "religion", descripcion: "La residencia pontificia se establece en Aviñón durante gran parte del siglo XIV." },
  { id: "CIEN_ANOS", desde: 1337, hasta: 1453, titulo: "Guerra de los Cien Años", categoria: "guerra", descripcion: "Conflicto dinástico y territorial prolongado entre las coronas de Inglaterra y Francia." },
  { id: "PESTE_NEGRA", desde: 1347, hasta: 1351, titulo: "Peste Negra en Europa", categoria: "sociedad", descripcion: "La gran epidemia de peste transforma profundamente la demografía, la economía y la sociedad europeas." },
  { id: "BULA_ORO", anio: 1356, titulo: "Bula de Oro", categoria: "politica", descripcion: "Carlos IV fija principios duraderos para la elección del rey de Romanos dentro del Sacro Imperio." },
  { id: "BORGO_1363", anio: 1363, titulo: "Felipe el Atrevido recibe Borgoña", categoria: "dinastia", personas: ["FEL2BORG", "JUAN2FRA"], descripcion: "Juan II de Francia entrega el ducado de Borgoña a su hijo Felipe, origen de la rama Valois-Borgoña." },
  { id: "BORGO_1369", anio: 1369, titulo: "Matrimonio de Felipe y Margarita de Flandes", categoria: "dinastia", personas: ["FEL2BORG", "MARGFLAN"], descripcion: "El matrimonio con Margarita de Flandes prepara la unión de Borgoña con ricos territorios flamencos y borgoñones." },
  { id: "CISMA_OCCIDENTE", desde: 1378, hasta: 1417, titulo: "Cisma de Occidente", categoria: "religion", descripcion: "Distintos obediencias papales compiten por la legitimidad de la Iglesia latina." },
  { id: "ALJUBARROTA", anio: 1385, titulo: "Batalla de Aljubarrota", categoria: "guerra", descripcion: "La victoria portuguesa consolida la dinastía de Avís y la independencia del reino frente a Castilla." },
  { id: "NICOPOLIS", anio: 1396, titulo: "Batalla de Nicópolis", categoria: "guerra", descripcion: "Una gran cruzada europea es derrotada por el Imperio otomano en los Balcanes." },
  { id: "AGINCOURT", anio: 1415, titulo: "Batalla de Agincourt", categoria: "guerra", descripcion: "Enrique V de Inglaterra obtiene una gran victoria sobre el ejército francés durante la Guerra de los Cien Años." },
  { id: "MONTEREAU", anio: 1419, titulo: "Asesinato de Juan Sin Miedo", categoria: "dinastia", personas: ["JUAN1BORG", "FEL3BORG"], descripcion: "Juan Sin Miedo es asesinado en Montereau. Felipe el Bueno hereda Borgoña y se acerca al bando inglés." },
  { id: "TROYES", anio: 1420, titulo: "Tratado de Troyes", categoria: "politica", descripcion: "El tratado reconoce a Enrique V y a sus herederos como sucesores de Carlos VI de Francia." },
  { id: "ORLEANS", anio: 1429, titulo: "Liberación de Orleans", categoria: "guerra", descripcion: "La intervención de Juana de Arco contribuye al giro de la guerra a favor de Carlos VII de Francia." },
  { id: "TOISON_ORO", anio: 1430, titulo: "Fundación de la Orden del Toisón de Oro", categoria: "dinastia", personas: ["FEL3BORG", "ISABPORTBORG"], descripcion: "Felipe el Bueno funda la Orden del Toisón de Oro en el contexto de su matrimonio con Isabel de Portugal." },
  { id: "ARRAS_1435", anio: 1435, titulo: "Tratado de Arras", categoria: "politica", personas: ["FEL3BORG", "CARLOS7FRA"], descripcion: "Felipe el Bueno se reconcilia con Carlos VII y rompe su alianza con Inglaterra." },
  { id: "VARNA", anio: 1444, titulo: "Batalla de Varna", categoria: "guerra", descripcion: "La cruzada de Varna termina con una victoria otomana y la muerte del rey Vladislao III." },
  { id: "CONSTANTINOPLA_1453", anio: 1453, titulo: "Caída de Constantinopla", categoria: "guerra", descripcion: "Mehmed II conquista Constantinopla y pone fin al Imperio bizantino." },
  { id: "ROSAS", desde: 1455, hasta: 1487, titulo: "Guerra de las Dos Rosas", categoria: "guerra", descripcion: "Las ramas de Lancaster y York disputan la corona inglesa en una larga sucesión de conflictos dinásticos." },
  { id: "BORGO_1467", anio: 1467, titulo: "Carlos el Temerario hereda Borgoña", categoria: "dinastia", personas: ["CAR1BORG", "FEL3BORG"], descripcion: "Carlos el Temerario sucede a Felipe el Bueno e intenta consolidar un bloque territorial borgoñón entre Francia y el Imperio." },
  { id: "REYES_CATOLICOS", anio: 1469, titulo: "Matrimonio de Isabel de Castilla y Fernando de Aragón", categoria: "dinastia", descripcion: "La unión matrimonial enlaza las dos principales coronas de la península ibérica sin fusionarlas jurídicamente en un único reino." },
  { id: "NANCY_1477", anio: 1477, titulo: "Batalla de Nancy y muerte de Carlos el Temerario", categoria: "guerra", personas: ["CAR1BORG", "MARIABORG"], descripcion: "Carlos muere sin heredero varón. Su hija María recibe una herencia disputada inmediatamente por Luis XI de Francia." },
  { id: "BODA_MARIA_MAX", anio: 1477, titulo: "María de Borgoña se casa con Maximiliano", categoria: "dinastia", personas: ["MARIABORG", "MAXIM1"], descripcion: "El matrimonio vincula la herencia borgoñona con los Habsburgo y cambia el equilibrio político de Europa occidental." },
  { id: "BOSWORTH", anio: 1485, titulo: "Batalla de Bosworth", categoria: "guerra", descripcion: "La derrota y muerte de Ricardo III abre el camino al reinado de Enrique VII Tudor." },
  { id: "GRANADA_1492", anio: 1492, titulo: "Conquista de Granada", categoria: "guerra", descripcion: "La toma de Granada pone fin al último reino islámico peninsular de la Edad Media." },
  { id: "SENLIS_1493", anio: 1493, titulo: "Tratado de Senlis", categoria: "politica", personas: ["MAXIM1", "FEL1CAST"], descripcion: "El acuerdo devuelve Artois y el Franco Condado a la herencia de María de Borgoña, mientras el ducado de Borgoña permanece en manos francesas." },
  { id: "GUERRAS_ITALIA", desde: 1494, hasta: 1559, titulo: "Guerras Italianas", categoria: "guerra", descripcion: "Francia, España, el Imperio y numerosos estados italianos compiten por el control político de la península." },
  { id: "LUTERO_1517", anio: 1517, titulo: "Inicio simbólico de la Reforma luterana", categoria: "religion", descripcion: "La controversia iniciada por Martín Lutero desencadena una transformación religiosa y política de alcance europeo." },
  { id: "WORMS_1521", anio: 1521, titulo: "Dieta de Worms", categoria: "religion", descripcion: "Carlos V convoca la Dieta en la que Lutero es requerido para retractarse de sus escritos." },
  { id: "PAVIA_1525", anio: 1525, titulo: "Batalla de Pavía", categoria: "guerra", personas: ["CARLOS5"], descripcion: "Las fuerzas imperiales derrotan al ejército francés y capturan al rey Francisco I." },
  { id: "SACO_ROMA_1527", anio: 1527, titulo: "Saco de Roma", categoria: "guerra", personas: ["CARLOS5"], descripcion: "Tropas imperiales amotinadas saquean Roma durante las Guerras Italianas." },
  { id: "AUGSBURGO_1555", anio: 1555, titulo: "Paz de Augsburgo", categoria: "religion", personas: ["CARLOS5"], descripcion: "El acuerdo establece una solución política provisional a la división confesional dentro del Sacro Imperio." },
  { id: "ABDICACION_CARLOS", desde: 1555, hasta: 1556, titulo: "Abdicaciones de Carlos V", categoria: "dinastia", personas: ["CARLOS5", "FEL2ESP"], descripcion: "Carlos V reparte progresivamente sus dominios entre la rama española y la rama austríaca de los Habsburgo." },
  { id: "LEPANTO", anio: 1571, titulo: "Batalla de Lepanto", categoria: "guerra", descripcion: "La Liga Santa derrota a la flota otomana en una de las grandes batallas navales del Mediterráneo." },
  { id: "ARMADA_1588", anio: 1588, titulo: "Armada de 1588", categoria: "guerra", personas: ["FEL2ESP"], descripcion: "La expedición naval de Felipe II contra Inglaterra fracasa tras combates, problemas logísticos y temporales adversos." },
  { id: "TREINTA_ANOS", desde: 1618, hasta: 1648, titulo: "Guerra de los Treinta Años", categoria: "guerra", descripcion: "Una guerra inicialmente imperial y confesional se convierte en un conflicto europeo de gran escala." },
  { id: "WESTFALIA", anio: 1648, titulo: "Paz de Westfalia", categoria: "politica", descripcion: "Los tratados de 1648 ponen fin a la Guerra de los Treinta Años y reordenan múltiples relaciones políticas europeas." },
];

export const HISTORIAS = [
  {
    id: "borgona",
    titulo: "Borgoña: el reino que no fue",
    disponible: true,
    subtitulo: "De apanage francés a herencia Habsburgo",
    descripcion: "Un recorrido por cuatro generaciones Valois-Borgoña y el matrimonio que trasladó gran parte de su herencia a los Habsburgo.",
    pasos: [
      {
        anio: 1363,
        persona: "FEL2BORG",
        personas: ["FEL2BORG", "JUAN2FRA"],
        eventoId: "BORGO_1363",
        titulo: "Una nueva Borgoña Valois",
        texto: "Juan II de Francia confía el ducado de Borgoña a su hijo Felipe el Atrevido. Nace así una rama menor de los Valois que, en pocas generaciones, llegará a competir en poder con la propia monarquía francesa.",
      },
      {
        anio: 1369,
        persona: "MARGFLAN",
        personas: ["FEL2BORG", "MARGFLAN"],
        eventoId: "BORGO_1369",
        titulo: "La expansión empieza con un matrimonio",
        texto: "Felipe se casa con Margarita de Flandes. La alianza matrimonial abre la vía hacia Flandes, Artois y el Franco Condado: territorios ricos y estratégicos que convierten a los duques borgoñones en mucho más que señores de Dijon.",
      },
      {
        anio: 1404,
        persona: "JUAN1BORG",
        personas: ["JUAN1BORG", "FEL2BORG", "MARGFLAN"],
        titulo: "Juan Sin Miedo hereda el proyecto",
        texto: "A la muerte de Felipe el Atrevido, Juan Sin Miedo recibe un conglomerado territorial ya poderoso. Su política se entrelaza con la crisis interna francesa y con la rivalidad entre borgoñones y armagnacs.",
      },
      {
        anio: 1419,
        persona: "FEL3BORG",
        personas: ["JUAN1BORG", "FEL3BORG"],
        eventoId: "MONTEREAU",
        titulo: "Montereau cambia el equilibrio",
        texto: "Juan Sin Miedo es asesinado durante una negociación en Montereau. Su hijo Felipe el Bueno hereda el ducado y se aproxima al bando inglés, convirtiendo la enemistad con los Valois franceses en uno de los ejes de la Guerra de los Cien Años.",
      },
      {
        anio: 1430,
        persona: "FEL3BORG",
        personas: ["FEL3BORG", "ISABPORTBORG"],
        eventoId: "TOISON_ORO",
        titulo: "Una corte que quiere parecer una monarquía",
        texto: "Felipe el Bueno funda la Orden del Toisón de Oro. La corte borgoñona desarrolla una cultura política y ceremonial extraordinariamente ambiciosa, acorde con un estado que une territorios dispersos desde Borgoña hasta los Países Bajos.",
      },
      {
        anio: 1435,
        persona: "FEL3BORG",
        personas: ["FEL3BORG", "CARLOS7FRA"],
        eventoId: "ARRAS_1435",
        titulo: "Borgoña cambia de aliado",
        texto: "El Tratado de Arras reconcilia a Felipe el Bueno con Carlos VII. Borgoña abandona la alianza inglesa y obtiene importantes concesiones, mientras la monarquía francesa recupera margen para terminar la Guerra de los Cien Años.",
      },
      {
        anio: 1467,
        persona: "CAR1BORG",
        personas: ["CAR1BORG", "FEL3BORG"],
        eventoId: "BORGO_1467",
        titulo: "Carlos el Temerario y la obsesión territorial",
        texto: "Carlos el Temerario hereda uno de los estados más ricos de Europa. Su gran problema es geográfico: sus posesiones forman dos grandes bloques separados. Su política intenta unirlos y elevar su rango hasta crear, de hecho o de derecho, un reino borgoñón independiente.",
      },
      {
        anio: 1477,
        persona: "CAR1BORG",
        personas: ["CAR1BORG", "MARIABORG", "LUIS11FRA"],
        eventoId: "NANCY_1477",
        titulo: "Nancy: el proyecto se rompe",
        texto: "Carlos muere en la batalla de Nancy sin heredero varón. Luis XI ocupa el ducado de Borgoña y otros territorios franceses, mientras María, hija única de Carlos, debe defender el resto de la herencia de su padre.",
      },
      {
        anio: 1477,
        persona: "MARIABORG",
        personas: ["MARIABORG", "MAXIM1"],
        eventoId: "BODA_MARIA_MAX",
        titulo: "La herencia cambia de dinastía",
        texto: "María de Borgoña se casa con Maximiliano de Habsburgo. El matrimonio salva buena parte de los Países Bajos borgoñones y convierte una crisis sucesoria en el punto de partida de la gran rivalidad entre Francia y los Habsburgo.",
      },
      {
        anio: 1493,
        persona: "MAXIM1",
        personas: ["MAXIM1", "FEL1CAST"],
        eventoId: "SENLIS_1493",
        titulo: "Lo que queda de Borgoña",
        texto: "El Tratado de Senlis devuelve Artois y el Franco Condado a la herencia borgoñona de los Habsburgo. El antiguo ducado de Borgoña, sin embargo, permanece en Francia. El sueño territorial de Carlos ya no puede reconstruirse en su forma original.",
      },
      {
        anio: 1506,
        persona: "CARLOS5",
        personas: ["FEL1CAST", "CARLOS5"],
        titulo: "De Borgoña a Carlos V",
        texto: "Felipe el Hermoso transmite la herencia borgoñona a su hijo Carlos. Para Carlos V, los Países Bajos y la tradición cortesana borgoñona serán una parte esencial de su identidad política. El reino que Carlos el Temerario no consiguió fundar termina convertido en una de las bases del poder Habsburgo.",
      },
    ],
  },
  { id: "emperadores", titulo: "Emperadores", subtitulo: "Del interregno a la hegemonía Habsburgo", disponible: false },
  { id: "habsburgo-capetos", titulo: "Habsburgo y Capetos", subtitulo: "Dos redes dinásticas que moldearon Europa", disponible: false },
  { id: "iberia", titulo: "España y Portugal", subtitulo: "Castilla, Aragón, Portugal y sus uniones", disponible: false },
  { id: "papales", titulo: "Las familias papales", subtitulo: "Roma, nepotismo y estrategia dinástica", disponible: false },
  { id: "condotieros", titulo: "Los condotieros", subtitulo: "Visconti, Sforza y la Italia de los señores de la guerra", disponible: false },
  { id: "cien-anos", titulo: "La Guerra de los 100 Años", subtitulo: "Una disputa de coronas convertida en guerra secular", disponible: false },
  { id: "dos-rosas", titulo: "La Guerra de las Dos Rosas", subtitulo: "Lancaster, York y el ascenso Tudor", disponible: false },
];
