export const EVENTOS_HISTORICOS = [
  { id: "MAGNA_CARTA", anio: 1215, titulo: "Magna Carta", categoria: "politica", descripcion: "Juan de Inglaterra acepta la Magna Carta, un hito en la limitación pactada del poder regio." },
  { id: "CONSTANTINOPLA_1261", anio: 1261, titulo: "Restauración bizantina de Constantinopla", categoria: "politica", descripcion: "Miguel VIII Paleólogo recupera Constantinopla y restaura el Imperio bizantino bajo la dinastía Paleólogo." },
  { id: "VISPERAS_SICILIANAS", anio: 1282, titulo: "Vísperas Sicilianas", categoria: "guerra", descripcion: "La rebelión siciliana rompe el dominio angevino de la isla y abre una larga disputa mediterránea con la Corona de Aragón." },
  { id: "AVINON", desde: 1309, hasta: 1377, titulo: "Papado de Aviñón", categoria: "religion", descripcion: "La residencia pontificia se establece en Aviñón durante gran parte del siglo XIV." },
  { id: "CRISIS_CAPETA_1328", anio: 1328, titulo: "Crisis sucesoria de Francia", categoria: "dinastia", personas: ["FEL6FRA", "EDUARDO3ING", "ISABFRAING"], descripcion: "La extinción de la línea capeta directa abre una disputa sucesoria: Felipe de Valois es coronado como Felipe VI, mientras Eduardo III conserva una reclamación dinástica por su madre Isabel de Francia." },
  { id: "CRECY_1346", anio: 1346, titulo: "Batalla de Crécy", categoria: "guerra", personas: ["EDUARDO3ING", "EDUNEGRO", "FEL6FRA"], descripcion: "La victoria inglesa de Crécy confirma la eficacia de sus ejércitos combinados y da a Eduardo III una posición dominante en la primera fase de la guerra." },
  { id: "POITIERS_1356", anio: 1356, titulo: "Batalla de Poitiers", categoria: "guerra", personas: ["EDUNEGRO", "JUANCHANDOS", "JUAN2FRA"], descripcion: "El ejército del Príncipe Negro derrota a Juan II de Francia y captura al rey, llevando la monarquía francesa a una crisis política y financiera." },
  { id: "BRETIGNY_1360", anio: 1360, titulo: "Tratado de Brétigny", categoria: "politica", personas: ["EDUARDO3ING", "JUAN2FRA", "EDUNEGRO"], descripcion: "El acuerdo reconoce una enorme expansión de los dominios ingleses en Francia a cambio de importantes concesiones dinásticas." },
  { id: "RECONQUISTA_CARLOS5_1369", desde: 1369, hasta: 1380, titulo: "La recuperación de Carlos V", categoria: "guerra", personas: ["CARLOS5FRA", "BERTRANDGUESCLIN", "EDUNEGRO"], descripcion: "Carlos V y Bertrand du Guesclin evitan las grandes batallas campales y recuperan gran parte de los territorios perdidos por Francia." },
  { id: "CIEN_ANOS", desde: 1337, hasta: 1453, titulo: "Guerra de los Cien Años", categoria: "guerra", descripcion: "Conflicto dinástico y territorial prolongado entre las coronas de Inglaterra y Francia." },
  { id: "PESTE_NEGRA", desde: 1347, hasta: 1351, titulo: "Peste Negra en Europa", categoria: "sociedad", descripcion: "La gran epidemia de peste transforma profundamente la demografía, la economía y la sociedad europeas." },
  { id: "BULA_ORO", anio: 1356, titulo: "Bula de Oro", categoria: "politica", descripcion: "Carlos IV fija principios duraderos para la elección del rey de Romanos dentro del Sacro Imperio." },
  { id: "BORGO_1363", anio: 1363, titulo: "Felipe el Atrevido recibe Borgoña", categoria: "dinastia", personas: ["FEL2BORG", "JUAN2FRA"], descripcion: "Juan II de Francia entrega el ducado de Borgoña a su hijo Felipe, origen de la rama Valois-Borgoña." },
  { id: "BORGO_1369", anio: 1369, titulo: "Matrimonio de Felipe y Margarita de Flandes", categoria: "dinastia", personas: ["FEL2BORG", "MARGFLAN"], descripcion: "El matrimonio con Margarita de Flandes prepara la unión de Borgoña con ricos territorios flamencos y borgoñones." },
  { id: "CISMA_OCCIDENTE", desde: 1378, hasta: 1417, titulo: "Cisma de Occidente", categoria: "religion", descripcion: "Distintos obediencias papales compiten por la legitimidad de la Iglesia latina." },
  { id: "ALJUBARROTA", anio: 1385, titulo: "Batalla de Aljubarrota", categoria: "guerra", descripcion: "La victoria portuguesa consolida la dinastía de Avís y la independencia del reino frente a Castilla." },
  { id: "NICOPOLIS", anio: 1396, titulo: "Batalla de Nicópolis", categoria: "guerra", descripcion: "Una gran cruzada europea es derrotada por el Imperio otomano en los Balcanes." },
  { id: "AGINCOURT", anio: 1415, titulo: "Batalla de Agincourt", categoria: "guerra", descripcion: "Enrique V de Inglaterra obtiene una gran victoria sobre el ejército francés durante la Guerra de los Cien Años." },
  { id: "MONTEREAU", anio: 1419, titulo: "Asesinato de Juan Sin Miedo", categoria: "dinastia", personas: ["JUAN1BORG", "FEL3BORG"], descripcion: "Juan Sin Miedo es asesinado en Montereau. Felipe el Bueno hereda Borgoña y se acerca al bando inglés." },
  { id: "TROYES", anio: 1420, titulo: "Tratado de Troyes", categoria: "politica", descripcion: "El tratado reconoce a Enrique V y a sus herederos como sucesores de Carlos VI de Francia." },
  { id: "ORLEANS", anio: 1429, titulo: "Liberación de Orleans", categoria: "guerra", descripcion: "La intervención de Juana de Arco contribuye al giro de la guerra a favor de Carlos VII de Francia." },
  { id: "REIMS_1429", anio: 1429, titulo: "Coronación de Carlos VII en Reims", categoria: "dinastia", personas: ["CARLOS7FRA", "JUANAARCO"], descripcion: "Tras la campaña del Loira, Carlos VII alcanza Reims y es coronado, reforzando decisivamente su legitimidad frente a la monarquía anglo-francesa de Enrique VI." },
  { id: "CAPTURA_JUANA_1430", anio: 1430, titulo: "Captura de Juana de Arco", categoria: "guerra", personas: ["JUANAARCO", "FEL3BORG"], descripcion: "Juana es capturada por fuerzas borgoñonas cerca de Compiègne y termina en manos inglesas; será ejecutada en Rouen en 1431." },
  { id: "TOISON_ORO", anio: 1430, titulo: "Fundación de la Orden del Toisón de Oro", categoria: "dinastia", personas: ["FEL3BORG", "ISABPORTBORG"], descripcion: "Felipe el Bueno funda la Orden del Toisón de Oro en el contexto de su matrimonio con Isabel de Portugal." },
  { id: "ARRAS_1435", anio: 1435, titulo: "Tratado de Arras", categoria: "politica", personas: ["FEL3BORG", "CARLOS7FRA"], descripcion: "Felipe el Bueno se reconcilia con Carlos VII y rompe su alianza con Inglaterra." },
  { id: "FORMIGNY_1450", anio: 1450, titulo: "Batalla de Formigny", categoria: "guerra", personas: ["ARTURO3BRET", "CARLOS7FRA"], descripcion: "La victoria francesa en Normandía acelera la expulsión inglesa del norte de Francia y muestra una monarquía francesa militarmente reorganizada." },
  { id: "CASTILLON_1453", anio: 1453, titulo: "Batalla de Castillon", categoria: "guerra", personas: ["JUANTALBOT", "JEANBUREAU", "CARLOS7FRA"], descripcion: "La artillería francesa derrota al ejército de John Talbot en Castillon. La pérdida de Guyena cierra convencionalmente la Guerra de los Cien Años." },
  { id: "VARNA", anio: 1444, titulo: "Batalla de Varna", categoria: "guerra", descripcion: "La cruzada de Varna termina con una victoria otomana y la muerte del rey Vladislao III." },
  { id: "CONSTANTINOPLA_1453", anio: 1453, titulo: "Caída de Constantinopla", categoria: "guerra", descripcion: "Mehmed II conquista Constantinopla y pone fin al Imperio bizantino." },
  { id: "ROSAS", desde: 1455, hasta: 1487, titulo: "Guerra de las Dos Rosas", categoria: "guerra", descripcion: "Las ramas de Lancaster y York disputan la corona inglesa en una larga sucesión de conflictos dinásticos." },
  { id: "BORGO_1467", anio: 1467, titulo: "Carlos el Temerario hereda Borgoña", categoria: "dinastia", personas: ["CAR1BORG", "FEL3BORG"], descripcion: "Carlos el Temerario sucede a Felipe el Bueno e intenta consolidar un bloque territorial borgoñón entre Francia y el Imperio." },
  { id: "REYES_CATOLICOS", anio: 1469, titulo: "Matrimonio de Isabel de Castilla y Fernando de Aragón", categoria: "dinastia", descripcion: "La unión matrimonial enlaza las dos principales coronas de la península ibérica sin fusionarlas jurídicamente en un único reino." },
  { id: "NANCY_1477", anio: 1477, titulo: "Batalla de Nancy y muerte de Carlos el Temerario", categoria: "guerra", personas: ["CAR1BORG", "MARIABORG"], descripcion: "Carlos muere sin heredero varón. Su hija María recibe una herencia disputada inmediatamente por Luis XI de Francia." },
  { id: "BODA_MARIA_MAX", anio: 1477, titulo: "María de Borgoña se casa con Maximiliano", categoria: "dinastia", personas: ["MARIABORG", "MAXIM1"], descripcion: "El matrimonio vincula la herencia borgoñona con los Habsburgo y cambia el equilibrio político de Europa occidental." },
  { id: "BOSWORTH", anio: 1485, titulo: "Batalla de Bosworth", categoria: "guerra", descripcion: "La derrota y muerte de Ricardo III abre el camino al reinado de Enrique VII Tudor." },
  { id: "GRANADA_1492", anio: 1492, titulo: "Conquista de Granada", categoria: "guerra", descripcion: "La toma de Granada pone fin al último reino islámico peninsular de la Edad Media." },
  { id: "SENLIS_1493", anio: 1493, titulo: "Tratado de Senlis", categoria: "politica", personas: ["MAXIM1", "FEL1CAST"], descripcion: "El acuerdo devuelve Artois y el Franco Condado a la herencia de María de Borgoña, mientras el ducado de Borgoña permanece en manos francesas." },
  { id: "GUERRAS_ITALIA", desde: 1494, hasta: 1559, titulo: "Guerras Italianas", categoria: "guerra", descripcion: "Francia, España, el Imperio y numerosos estados italianos compiten por el control político de la península." },
  { id: "LUTERO_1517", anio: 1517, titulo: "Inicio simbólico de la Reforma luterana", categoria: "religion", descripcion: "La controversia iniciada por Martín Lutero desencadena una transformación religiosa y política de alcance europeo." },
  { id: "WORMS_1521", anio: 1521, titulo: "Dieta de Worms", categoria: "religion", descripcion: "Carlos V convoca la Dieta en la que Lutero es requerido para retractarse de sus escritos." },
  { id: "PAVIA_1525", anio: 1525, titulo: "Batalla de Pavía", categoria: "guerra", personas: ["CARLOS5"], descripcion: "Las fuerzas imperiales derrotan al ejército francés y capturan al rey Francisco I." },
  { id: "SACO_ROMA_1527", anio: 1527, titulo: "Saco de Roma", categoria: "guerra", personas: ["CARLOS5"], descripcion: "Tropas imperiales amotinadas saquean Roma durante las Guerras Italianas." },
  { id: "AUGSBURGO_1555", anio: 1555, titulo: "Paz de Augsburgo", categoria: "religion", personas: ["CARLOS5"], descripcion: "El acuerdo establece una solución política provisional a la división confesional dentro del Sacro Imperio." },
  { id: "ABDICACION_CARLOS", desde: 1555, hasta: 1556, titulo: "Abdicaciones de Carlos V", categoria: "dinastia", personas: ["CARLOS5", "FEL2ESP"], descripcion: "Carlos V reparte progresivamente sus dominios entre la rama española y la rama austríaca de los Habsburgo." },
  { id: "LEPANTO", anio: 1571, titulo: "Batalla de Lepanto", categoria: "guerra", descripcion: "La Liga Santa derrota a la flota otomana en una de las grandes batallas navales del Mediterráneo." },
  { id: "ARMADA_1588", anio: 1588, titulo: "Armada de 1588", categoria: "guerra", personas: ["FEL2ESP"], descripcion: "La expedición naval de Felipe II contra Inglaterra fracasa tras combates, problemas logísticos y temporales adversos." },
  { id: "TREINTA_ANOS", desde: 1618, hasta: 1648, titulo: "Guerra de los Treinta Años", categoria: "guerra", descripcion: "Una guerra inicialmente imperial y confesional se convierte en un conflicto europeo de gran escala." },
  { id: "WESTFALIA", anio: 1648, titulo: "Paz de Westfalia", categoria: "politica", descripcion: "Los tratados de 1648 ponen fin a la Guerra de los Treinta Años y reordenan múltiples relaciones políticas europeas." },

  { id: "COMPANIA_BLANCA_1363", anio: 1363, titulo: "La Compañía Blanca entra en la política italiana", categoria: "guerra", personas: ["HAWKWOOD"], descripcion: "Compañías de veteranos de la Guerra de los Cien Años, entre ellas la asociada a John Hawkwood, convierten la condotta mercenaria en una fuerza decisiva de la política italiana." },
  { id: "BARBIANO_1379", anio: 1379, titulo: "Alberico da Barbiano y la Compañía de San Jorge", categoria: "guerra", personas: ["ALBERICOBARB"], descripcion: "Alberico da Barbiano simboliza la consolidación de compañías de armas dirigidas por capitanes italianos, capaces de competir con las grandes compañías extranjeras." },
  { id: "LAQUILA_1424", anio: 1424, titulo: "L'Aquila: caída de Braccio da Montone", categoria: "guerra", personas: ["BRACCIOMONT", "FRAN1SFOR", "NICCPICC", "MUZIOSFOR"], descripcion: "La guerra de L'Aquila destruye el poder de Braccio da Montone y acelera el ascenso de una nueva generación de capitanes, entre ellos Francesco Sforza y Niccolò Piccinino." },
  { id: "CARMAGNOLA_1432", anio: 1432, titulo: "Venecia ejecuta a Carmagnola", categoria: "politica", personas: ["CARMAGNOLA"], descripcion: "La ejecución de Carmagnola muestra la tensión esencial del sistema: los estados necesitaban grandes capitanes, pero temían que sus intereses privados acabasen imponiéndose a los del empleador." },
  { id: "BODA_SFORZA_VISCONTI_1441", anio: 1441, titulo: "Francesco Sforza se casa con Bianca Maria Visconti", categoria: "dinastia", personas: ["FRAN1SFOR", "BLANMARVISC", "FELMARVISC"], descripcion: "El matrimonio introduce a un condotiero en la sucesión del ducado de Milán y demuestra hasta qué punto la fuerza militar podía transformarse en legitimidad dinástica." },
  { id: "SFORZA_DUQUE_1450", anio: 1450, titulo: "Francesco Sforza, duque de Milán", categoria: "dinastia", personas: ["FRAN1SFOR", "BLANMARVISC"], descripcion: "Francesco Sforza culmina la trayectoria más extraordinaria de un condotiero: de capitán mercenario a fundador de una dinastía ducal." },
  { id: "LODI_1454", anio: 1454, titulo: "Paz de Lodi", categoria: "politica", personas: ["FRAN1SFOR"], descripcion: "La paz entre Milán y Venecia inaugura un equilibrio italiano que reduce el espacio político para los grandes capitanes independientes y favorece ejércitos más controlados por los estados." },
  { id: "SENIGALLIA_1502", anio: 1502, titulo: "La trampa de Senigallia", categoria: "politica", personas: ["CESARBORJA", "VITELLOZZO"], descripcion: "César Borja elimina en Senigallia a varios capitanes que se habían rebelado contra él. El episodio, observado por Maquiavelo, resume el conflicto entre el príncipe territorial y los condotieros autónomos." },
  { id: "AGNADELLO_1509", anio: 1509, titulo: "Batalla de Agnadello", categoria: "guerra", personas: ["BARTALVIANO", "TRIVULZIO"], descripcion: "La derrota veneciana de Agnadello muestra a los condotieros dentro de guerras ya dominadas por grandes coaliciones internacionales y ejércitos de escala mucho mayor." },
  { id: "BANDENERE_1526", anio: 1526, titulo: "Muere Giovanni dalle Bande Nere", categoria: "guerra", personas: ["GIOVBANDENERE"], descripcion: "La muerte de Giovanni de' Medici tras ser herido por artillería se convirtió en un símbolo tardío del mundo de los grandes capitanes de ventura frente a una guerra cada vez más transformada por las armas de fuego." },

  { id: "LEONARDO_MILAN_1482", anio: 1482, titulo: "Leonardo entra al servicio de los Sforza", categoria: "cultura", personas: ["LEONARDODAVINCI", "LUDOVSFOR"], descripcion: "Leonardo se instala en Milán y desarrolla durante años una carrera al servicio de la corte de Ludovico Sforza." },
  { id: "DAMA_ARMINO_1490", anio: 1490, titulo: "La Dama del armiño", categoria: "cultura", personas: ["LEONARDODAVINCI", "CECIGALL", "LUDOVSFOR"], descripcion: "Leonardo retrata a Cecilia Gallerani, amante de Ludovico Sforza. En 1491 Cecilia dará a Ludovico un hijo, Cesare." },
  { id: "BIANCA_SFORZA_1496", anio: 1496, titulo: "Bianca Giovanna Sforza", categoria: "dinastia", personas: ["BIANSFOR", "LUDOVSFOR", "BERNACORR"], descripcion: "Bianca Giovanna Sforza pertenece al círculo milanés en el que se formó la primera gran etapa cortesana de Leonardo. Una hipótesis moderna y minoritaria la ha propuesto como modelo de la Gioconda." },
  { id: "LEONARDO_BORJA_1502", anio: 1502, titulo: "Leonardo al servicio de César Borja", categoria: "politica", personas: ["LEONARDODAVINCI", "CESARBORJA"], descripcion: "Leonardo trabaja como ingeniero militar para César Borja durante sus campañas en Italia central." },
  { id: "GIOCONDA_1503", anio: 1503, titulo: "Comienza la historia de la Gioconda", categoria: "cultura", personas: ["LEONARDODAVINCI", "LISAGHERARDINI", "FRANCESCOGIOCONDO"], descripcion: "La identificación tradicional y hoy dominante relaciona el retrato con Lisa Gherardini, esposa del mercader florentino Francesco del Giocondo." },
  { id: "LEONARDO_MILAN_1506", anio: 1506, titulo: "Leonardo regresa a Milán", categoria: "cultura", personas: ["LEONARDODAVINCI", "CHARLES2AMBOISE"], descripcion: "Leonardo vuelve a Milán bajo la protección del gobernador francés Charles II d'Amboise." },
  { id: "LEONARDO_ROMA_1513", anio: 1513, titulo: "Leonardo en la Roma de los Médici", categoria: "cultura", personas: ["LEONARDODAVINCI", "GIULIANOMEDICI", "PAPA_LEON10"], descripcion: "Leonardo se instala en Roma bajo la protección de Giuliano de' Medici durante el pontificado de León X." },
  { id: "LEONARDO_FRANCIA_1516", anio: 1516, titulo: "Francisco I llama a Leonardo a Francia", categoria: "cultura", personas: ["LEONARDODAVINCI", "FRAN1FRA", "FRANCESCOMELZI"], descripcion: "Leonardo se traslada a Francia acompañado por Francesco Melzi y entra en la órbita de Francisco I." },
  { id: "LEONARDO_MUERTE_1519", anio: 1519, titulo: "Muere Leonardo", categoria: "cultura", personas: ["LEONARDODAVINCI", "FRAN1FRA", "FRANCESCOMELZI"], descripcion: "Leonardo muere en Francia. La Gioconda permaneció con él hasta sus últimos años y acabó incorporándose a la colección real francesa." },
];

export const HISTORIAS = [
  {
    id: "borgona",
    titulo: "Borgoña: el reino que no fue",
    disponible: true,
    subtitulo: "De apanage francés a herencia Habsburgo",
    descripcion: "Un recorrido por cuatro generaciones Valois-Borgoña y el matrimonio que trasladó gran parte de su herencia a los Habsburgo.",
    pasos: [
      {
        anio: 1363,
        persona: "FEL2BORG",
        personas: ["FEL2BORG", "JUAN2FRA"],
        eventoId: "BORGO_1363",
        titulo: "Una nueva Borgoña Valois",
        texto: "Juan II de Francia confía el ducado de Borgoña a su hijo Felipe el Atrevido. Nace así una rama menor de los Valois que, en pocas generaciones, llegará a competir en poder con la propia monarquía francesa.",
      },
      {
        anio: 1369,
        persona: "MARGFLAN",
        personas: ["FEL2BORG", "MARGFLAN"],
        eventoId: "BORGO_1369",
        titulo: "La expansión empieza con un matrimonio",
        texto: "Felipe se casa con Margarita de Flandes. La alianza matrimonial abre la vía hacia Flandes, Artois y el Franco Condado: territorios ricos y estratégicos que convierten a los duques borgoñones en mucho más que señores de Dijon.",
      },
      {
        anio: 1404,
        persona: "JUAN1BORG",
        personas: ["JUAN1BORG", "FEL2BORG", "MARGFLAN"],
        titulo: "Juan Sin Miedo hereda el proyecto",
        texto: "A la muerte de Felipe el Atrevido, Juan Sin Miedo recibe un conglomerado territorial ya poderoso. Su política se entrelaza con la crisis interna francesa y con la rivalidad entre borgoñones y armagnacs.",
      },
      {
        anio: 1419,
        persona: "FEL3BORG",
        personas: ["JUAN1BORG", "FEL3BORG"],
        eventoId: "MONTEREAU",
        titulo: "Montereau cambia el equilibrio",
        texto: "Juan Sin Miedo es asesinado durante una negociación en Montereau. Su hijo Felipe el Bueno hereda el ducado y se aproxima al bando inglés, convirtiendo la enemistad con los Valois franceses en uno de los ejes de la Guerra de los Cien Años.",
      },
      {
        anio: 1430,
        persona: "FEL3BORG",
        personas: ["FEL3BORG", "ISABPORTBORG"],
        eventoId: "TOISON_ORO",
        titulo: "Una corte que quiere parecer una monarquía",
        texto: "Felipe el Bueno funda la Orden del Toisón de Oro. La corte borgoñona desarrolla una cultura política y ceremonial extraordinariamente ambiciosa, acorde con un estado que une territorios dispersos desde Borgoña hasta los Países Bajos.",
      },
      {
        anio: 1435,
        persona: "FEL3BORG",
        personas: ["FEL3BORG", "CARLOS7FRA"],
        eventoId: "ARRAS_1435",
        titulo: "Borgoña cambia de aliado",
        texto: "El Tratado de Arras reconcilia a Felipe el Bueno con Carlos VII. Borgoña abandona la alianza inglesa y obtiene importantes concesiones, mientras la monarquía francesa recupera margen para terminar la Guerra de los Cien Años.",
      },
      {
        anio: 1467,
        persona: "CAR1BORG",
        personas: ["CAR1BORG", "FEL3BORG"],
        eventoId: "BORGO_1467",
        titulo: "Carlos el Temerario y la obsesión territorial",
        texto: "Carlos el Temerario hereda uno de los estados más ricos de Europa. Su gran problema es geográfico: sus posesiones forman dos grandes bloques separados. Su política intenta unirlos y elevar su rango hasta crear, de hecho o de derecho, un reino borgoñón independiente.",
      },
      {
        anio: 1477,
        persona: "CAR1BORG",
        personas: ["CAR1BORG", "MARIABORG", "LUIS11FRA"],
        eventoId: "NANCY_1477",
        titulo: "Nancy: el proyecto se rompe",
        texto: "Carlos muere en la batalla de Nancy sin heredero varón. Luis XI ocupa el ducado de Borgoña y otros territorios franceses, mientras María, hija única de Carlos, debe defender el resto de la herencia de su padre.",
      },
      {
        anio: 1477,
        persona: "MARIABORG",
        personas: ["MARIABORG", "MAXIM1"],
        eventoId: "BODA_MARIA_MAX",
        titulo: "La herencia cambia de dinastía",
        texto: "María de Borgoña se casa con Maximiliano de Habsburgo. El matrimonio salva buena parte de los Países Bajos borgoñones y convierte una crisis sucesoria en el punto de partida de la gran rivalidad entre Francia y los Habsburgo.",
      },
      {
        anio: 1493,
        persona: "MAXIM1",
        personas: ["MAXIM1", "FEL1CAST"],
        eventoId: "SENLIS_1493",
        titulo: "Lo que queda de Borgoña",
        texto: "El Tratado de Senlis devuelve Artois y el Franco Condado a la herencia borgoñona de los Habsburgo. El antiguo ducado de Borgoña, sin embargo, permanece en Francia. El sueño territorial de Carlos ya no puede reconstruirse en su forma original.",
      },
      {
        anio: 1506,
        persona: "CARLOS5",
        personas: ["FEL1CAST", "CARLOS5"],
        titulo: "De Borgoña a Carlos V",
        texto: "Felipe el Hermoso transmite la herencia borgoñona a su hijo Carlos. Para Carlos V, los Países Bajos y la tradición cortesana borgoñona serán una parte esencial de su identidad política. El reino que Carlos el Temerario no consiguió fundar termina convertido en una de las bases del poder Habsburgo.",
      },
    ],
  },
  { id: "emperadores", titulo: "Emperadores", subtitulo: "Del interregno a la hegemonía Habsburgo", disponible: false },
  { id: "habsburgo-capetos", titulo: "Habsburgo y Capetos", subtitulo: "Dos redes dinásticas que moldearon Europa", disponible: false },
  { id: "iberia", titulo: "España y Portugal", subtitulo: "Castilla, Aragón, Portugal y sus uniones", disponible: false },
  { id: "papales", titulo: "Las familias papales", subtitulo: "Roma, nepotismo y estrategia dinástica", disponible: false },
  {
    id: "condotieros",
    titulo: "Los condotieros",
    subtitulo: "De las compañías de ventura al ducado de Milán",
    disponible: true,
    descripcion: "Un recorrido por los capitanes de fortuna que convirtieron la guerra en una profesión, negociaron con repúblicas y príncipes y, en el caso de los Sforza, transformaron el mando militar en poder dinástico.",
    pasos: [
      {
        anio: 1363,
        persona: "HAWKWOOD",
        personas: ["HAWKWOOD"],
        eventoId: "COMPANIA_BLANCA_1363",
        titulo: "La guerra se convierte en un mercado",
        texto: "Tras las grandes campañas de la Guerra de los Cien Años, compañías de veteranos cruzan los Alpes y venden su experiencia a ciudades y príncipes italianos. John Hawkwood, conocido en Italia como Giovanni Acuto, se convierte en uno de los capitanes extranjeros más célebres y en un modelo de condotiero político además de militar.",
      },
      {
        anio: 1379,
        persona: "ALBERICOBARB",
        personas: ["ALBERICOBARB", "HAWKWOOD"],
        eventoId: "BARBIANO_1379",
        titulo: "Los italianos aprenden el oficio",
        texto: "Alberico da Barbiano representa una nueva generación de capitanes italianos. La condotta ya no es solo la contratación de una compañía extranjera: empieza a surgir un sistema de escuelas militares, clientelas y lealtades personales alrededor de grandes jefes de armas.",
      },
      {
        anio: 1416,
        persona: "BRACCIOMONT",
        personas: ["BRACCIOMONT", "MUZIOSFOR"],
        titulo: "Bracceschi contra Sforzeschi",
        texto: "Braccio da Montone y Muzio Attendolo Sforza encarnan dos redes rivales de capitanes. Sus hombres no son simples soldados: aprenden tácticas, heredan contactos y forman auténticas genealogías profesionales que seguirán enfrentándose bajo sus discípulos.",
      },
      {
        anio: 1424,
        persona: "BRACCIOMONT",
        personas: ["BRACCIOMONT", "MUZIOSFOR", "FRAN1SFOR", "NICCPICC"],
        eventoId: "LAQUILA_1424",
        titulo: "1424: cambia una generación",
        texto: "Muzio Attendolo muere ahogado durante la campaña y Braccio cae en la guerra de L'Aquila. El relevo pasa a hombres como Francesco Sforza y Niccolò Piccinino. El sistema sobrevive a sus fundadores porque sus compañías, discípulos y alianzas ya forman parte estable de la política italiana.",
      },
      {
        anio: 1432,
        persona: "CARMAGNOLA",
        personas: ["CARMAGNOLA", "FELMARVISC"],
        eventoId: "CARMAGNOLA_1432",
        titulo: "El empleador también teme a su general",
        texto: "Carmagnola sirve primero a Milán y después a Venecia. Su carrera muestra la gran contradicción de la condotta: un capitán debía ser lo bastante poderoso para ganar guerras, pero cuanto más poderoso era, más peligroso resultaba para quien lo contrataba. Venecia acabó acusándolo de traición y lo ejecutó.",
      },
      {
        anio: 1438,
        persona: "NICCPICC",
        personas: ["NICCPICC", "FRAN1SFOR"],
        titulo: "Piccinino y Sforza: la guerra como carrera",
        texto: "Niccolò Piccinino, heredero militar de Braccio, y Francesco Sforza compiten al servicio de potencias que cambian de aliados con rapidez. La guerra lombarda convierte sus reputaciones, tropas y contratos en recursos políticos tan importantes como un título nobiliario.",
      },
      {
        anio: 1441,
        persona: "FRAN1SFOR",
        personas: ["FRAN1SFOR", "BLANMARVISC", "FELMARVISC"],
        eventoId: "BODA_SFORZA_VISCONTI_1441",
        titulo: "Una boda vale más que una victoria",
        texto: "Francesco Sforza se casa con Bianca Maria Visconti, hija de Filippo Maria. De pronto el capitán de fortuna posee algo que los contratos militares no podían darle por sí solos: una vía dinástica hacia Milán.",
      },
      {
        anio: 1450,
        persona: "FRAN1SFOR",
        personas: ["FRAN1SFOR", "BLANMARVISC"],
        eventoId: "SFORZA_DUQUE_1450",
        titulo: "El condotiero que se convierte en príncipe",
        texto: "En 1450 Francesco Sforza entra en Milán como duque. Es el triunfo máximo de la lógica condotiera: fuerza militar, negociación y matrimonio se combinan para fundar una dinastía que gobernará una de las principales potencias italianas.",
      },
      {
        anio: 1454,
        persona: "FRAN1SFOR",
        personas: ["FRAN1SFOR", "BARTCOLLEONI", "GATTAMELATA"],
        eventoId: "LODI_1454",
        titulo: "El éxito de Sforza cambia las reglas",
        texto: "La Paz de Lodi estabiliza el equilibrio entre los grandes estados italianos. Paradójicamente, el triunfo de Sforza sirve de advertencia: repúblicas y príncipes tienen ahora más razones para impedir que otro general mercenario acumule suficiente poder como para convertirse en soberano.",
      },
      {
        anio: 1474,
        persona: "FEDMONTE",
        personas: ["FEDMONTE", "SIGISMALAT", "BATTISTASFORZA"],
        titulo: "El condotiero renacentista",
        texto: "Federico da Montefeltro combina la profesión militar con el gobierno de Urbino y un mecenazgo cultural extraordinario. Su rivalidad con Sigismondo Pandolfo Malatesta recuerda que el condotiero podía ser simultáneamente general, príncipe, diplomático y constructor de una imagen pública cuidadosamente elaborada.",
      },
      {
        anio: 1502,
        persona: "CESARBORJA",
        personas: ["CESARBORJA", "VITELLOZZO"],
        eventoId: "SENIGALLIA_1502",
        titulo: "Senigallia: el príncipe contra sus capitanes",
        texto: "Vitellozzo Vitelli y otros condotieros temen que César Borja los absorba uno a uno y se rebelan. Borja aparenta reconciliarse con ellos, los atrae a Senigallia y elimina a sus dirigentes. El episodio muestra hasta qué punto el estado territorial busca ya domesticar o destruir la autonomía de los capitanes.",
      },
      {
        anio: 1509,
        persona: "BARTALVIANO",
        personas: ["BARTALVIANO", "TRIVULZIO"],
        eventoId: "AGNADELLO_1509",
        titulo: "Las Guerras Italianas cambian la escala",
        texto: "En Agnadello, Bartolomeo d'Alviano combate al servicio de Venecia frente a un ejército francés en el que también actúan capitanes italianos como Gian Giacomo Trivulzio. Desde 1494 la península es escenario de monarquías extranjeras, grandes contingentes de infantería y artillería: el viejo mercado militar italiano ya no domina por sí solo la guerra.",
      },
      {
        anio: 1526,
        persona: "GIOVBANDENERE",
        personas: ["GIOVBANDENERE", "CATASFOR", "GIOVPOPOLANO"],
        eventoId: "BANDENERE_1526",
        titulo: "Giovanni dalle Bande Nere: un final simbólico",
        texto: "Giovanni de' Medici, hijo de Caterina Sforza y Giovanni il Popolano, conserva el prestigio personal del gran capitán de ventura. Muere en 1526 después de ser herido por artillería. Su figura sirve como cierre simbólico de una época en la que el nombre de un capitán podía pesar casi tanto como el del estado que lo contrataba.",
      },
      {
        anio: 1535,
        persona: "FERRANTEGONZAGA",
        personas: ["FERRANTEGONZAGA", "FRAN2GONZAGA", "GIOVBANDENERE"],
        titulo: "Del capitán de ventura al servidor de una monarquía",
        texto: "Ferrante Gonzaga pertenece todavía al mundo de los grandes comandantes italianos, pero su carrera dentro de la estructura imperial de Carlos V señala otra dirección: el prestigio militar continúa, aunque cada vez más integrado en estados dinásticos, gobernaciones y ejércitos permanentes. El condotiero clásico deja paso al general de una potencia europea.",
      },
    ],
  },
  {
    id: "cien-anos",
    titulo: "La Guerra de los Cien Años",
    subtitulo: "Una disputa dinástica que transformó Francia e Inglaterra",
    disponible: true,
    descripcion: "Un recorrido desde la crisis sucesoria de 1328 hasta Castillon en 1453: reclamaciones de sangre, grandes victorias inglesas, recuperación francesa, guerra civil, Borgoña y el giro de Juana de Arco.",
    pasos: [
      {
        anio: 1328,
        persona: "FEL6FRA",
        personas: ["CARLOS4FRA", "FEL6FRA", "ISABFRAING", "EDUARDO3ING"],
        eventoId: "CRISIS_CAPETA_1328",
        titulo: "1328: una corona sin heredero varón",
        texto: "Carlos IV muere sin un hijo varón superviviente y se extingue la línea directa de los Capetos. La corona pasa a Felipe de Valois, Felipe VI. Pero Eduardo III de Inglaterra es nieto de Felipe IV a través de su madre, Isabel de Francia. La guerra todavía no ha comenzado: primero nace una pregunta genealógica sobre quién puede transmitir un derecho a la corona.",
      },
      {
        anio: 1337,
        persona: "EDUARDO3ING",
        personas: ["EDUARDO3ING", "FEL6FRA"],
        eventoId: "CIEN_ANOS",
        titulo: "1337: la disputa dinástica se convierte en guerra",
        texto: "Aquitania, los homenajes feudales y la política entre Francia, Inglaterra y Escocia convierten la rivalidad sucesoria en un conflicto abierto. Eduardo III eleva su reclamación a la corona francesa y el choque deja de ser una discusión de parentesco: dos monarquías movilizan recursos durante generaciones.",
      },
      {
        anio: 1346,
        persona: "EDUNEGRO",
        personas: ["EDUARDO3ING", "EDUNEGRO", "FEL6FRA"],
        eventoId: "CRECY_1346",
        titulo: "Crécy: el gran golpe inglés",
        texto: "Eduardo III y su hijo Eduardo de Woodstock, el Príncipe Negro, obtienen en Crécy una victoria que altera el prestigio militar de ambos reinos. Calais caerá poco después y se convertirá en una cabeza de puente inglesa duradera en el continente.",
      },
      {
        anio: 1356,
        persona: "JUAN2FRA",
        personas: ["JUAN2FRA", "EDUNEGRO", "JUANCHANDOS"],
        eventoId: "POITIERS_1356",
        titulo: "Poitiers: un rey de Francia prisionero",
        texto: "El Príncipe Negro y John Chandos derrotan al ejército de Juan II. El propio rey francés es capturado. La derrota es militar, pero también dinástica y fiscal: el reino debe gobernar mientras su monarca está en manos inglesas y negociar un rescate gigantesco.",
      },
      {
        anio: 1360,
        persona: "EDUARDO3ING",
        personas: ["EDUARDO3ING", "EDUNEGRO", "JUAN2FRA"],
        eventoId: "BRETIGNY_1360",
        titulo: "Brétigny: Inglaterra parece haber ganado",
        texto: "El tratado concede a Eduardo III una posición territorial extraordinaria en Francia. Pero no será un final. La guerra demuestra aquí una de sus claves: ningún acuerdo consigue resolver a la vez la soberanía territorial, la relación feudal y la reclamación dinástica.",
      },
      {
        anio: 1370,
        persona: "CARLOS5FRA",
        personas: ["CARLOS5FRA", "BERTRANDGUESCLIN", "EDUNEGRO"],
        eventoId: "RECONQUISTA_CARLOS5_1369",
        titulo: "Carlos V cambia la guerra",
        texto: "Carlos V de Francia y su condestable Bertrand du Guesclin evitan repetir las grandes batallas que habían favorecido a los ingleses. Con campañas más pacientes, asedios y desgaste recuperan gran parte de las pérdidas francesas. Cuando Carlos V muere en 1380, el mapa se parece muy poco al de 1360.",
      },
      {
        anio: 1407,
        persona: "CARLOS6FRA",
        personas: ["CARLOS6FRA", "JUAN1BORG", "LUISORLEANS", "FEL3BORG"],
        titulo: "Francia se rompe por dentro",
        texto: "La enfermedad de Carlos VI abre una lucha por controlar el gobierno. Borgoñones y Armagnacs convierten la corte francesa en una guerra civil. El asesinato de Luis de Orleans en 1407 y, más tarde, el de Juan Sin Miedo en 1419 harán posible algo decisivo: que el rey de Inglaterra vuelva a intervenir en una Francia dividida.",
      },
      {
        anio: 1415,
        persona: "ENRIQ5ING",
        personas: ["ENRIQ5ING", "CHARLESDALBRET", "BOUCICAUT", "CARLOS6FRA"],
        eventoId: "AGINCOURT",
        titulo: "Agincourt: Enrique V vuelve a poner Francia contra las cuerdas",
        texto: "Enrique V invade Francia y obtiene en Agincourt una de las victorias más famosas de la guerra. Entre los mandos franceses están el condestable Carlos d'Albret y el mariscal Boucicaut. La derrota llega cuando la monarquía francesa sigue desgarrada por su conflicto interno.",
      },
      {
        anio: 1419,
        persona: "FEL3BORG",
        personas: ["JUAN1BORG", "FEL3BORG", "CARLOS7FRA", "ENRIQ5ING"],
        eventoId: "MONTEREAU",
        titulo: "Montereau: Borgoña se inclina hacia Inglaterra",
        texto: "Juan Sin Miedo es asesinado durante una entrevista con el entorno del delfín Carlos. Su hijo Felipe el Bueno hereda Borgoña y se acerca a Enrique V. La Guerra de los Cien Años deja de ser comprensible si se mira solo como Inglaterra contra Francia: la alianza borgoñona es ahora una pieza central.",
      },
      {
        anio: 1420,
        persona: "ENRIQ5ING",
        personas: ["ENRIQ5ING", "CATALINAVAL", "CARLOS6FRA", "CARLOS7FRA", "FEL3BORG"],
        eventoId: "TROYES",
        titulo: "Troyes: un Plantagenet heredará Francia",
        texto: "El Tratado de Troyes reconoce a Enrique V como heredero de Carlos VI y sella su matrimonio con Catalina de Valois. El delfín Carlos queda desplazado. Durante un instante parece posible una unión dinástica de Inglaterra y Francia bajo los descendientes de Enrique.",
      },
      {
        anio: 1422,
        persona: "ENRIQ6ING",
        personas: ["ENRIQ6ING", "JUANBEDFORD", "CARLOS7FRA", "FEL3BORG"],
        titulo: "1422: dos reyes para una Francia dividida",
        texto: "Enrique V y Carlos VI mueren con pocas semanas de diferencia. El bebé Enrique VI es proclamado rey en el sistema anglo-francés y su tío Bedford gobierna como regente en Francia. Al sur del Loira, el delfín se mantiene como Carlos VII. La disputa sucesoria de 1328 ha producido ahora dos legitimidades rivales.",
      },
      {
        anio: 1429,
        persona: "JUANAARCO",
        personas: ["JUANAARCO", "CARLOS7FRA", "JEANDUNOIS", "LAHIRE", "JUANBEDFORD"],
        eventoId: "ORLEANS",
        titulo: "Orleans: aparece Juana de Arco",
        texto: "Con Orleans sitiada, Juana de Arco llega al campo de Carlos VII. Junto a comandantes como Jean de Dunois y La Hire participa en el levantamiento del sitio y en una rápida campaña por el Loira. El efecto político es tan importante como el militar: la iniciativa cambia de manos.",
      },
      {
        anio: 1429,
        persona: "CARLOS7FRA",
        personas: ["CARLOS7FRA", "JUANAARCO"],
        eventoId: "REIMS_1429",
        titulo: "Reims: la guerra vuelve a ser una cuestión de legitimidad",
        texto: "Juana insiste en conducir a Carlos VII a Reims, el lugar tradicional de coronación de los reyes franceses. La ceremonia convierte al antiguo 'delfín de Bourges' en un rey ungido y visible. La guerra no está ganada, pero la legitimidad de Carlos deja de parecer provisional.",
      },
      {
        anio: 1431,
        persona: "JUANAARCO",
        personas: ["JUANAARCO", "FEL3BORG", "JUANBEDFORD", "CARLOS7FRA"],
        eventoId: "CAPTURA_JUANA_1430",
        titulo: "La muerte de Juana no detiene el cambio",
        texto: "Juana es capturada por los borgoñones en 1430, entregada a los ingleses y ejecutada en Rouen en 1431. Su muerte no revierte el giro político que ayudó a acelerar. Carlos VII dispone ahora de una legitimidad reforzada y de una monarquía que empieza a reconstruir sus recursos.",
      },
      {
        anio: 1435,
        persona: "FEL3BORG",
        personas: ["FEL3BORG", "CARLOS7FRA", "JUANBEDFORD"],
        eventoId: "ARRAS_1435",
        titulo: "Arras: Inglaterra pierde a Borgoña",
        texto: "Felipe el Bueno se reconcilia con Carlos VII. La ruptura de la alianza anglo-borgoñona es un golpe estratégico enorme para Inglaterra. Poco después muere Bedford, el hombre que había sostenido con más eficacia el régimen inglés en Francia.",
      },
      {
        anio: 1450,
        persona: "ARTURO3BRET",
        personas: ["CARLOS7FRA", "ARTURO3BRET", "JEANBUREAU"],
        eventoId: "FORMIGNY_1450",
        titulo: "Una monarquía francesa distinta recupera Normandía",
        texto: "Francia ya no depende únicamente de la nobleza convocada para una campaña. Reformas fiscales, compañías permanentes y una artillería cada vez más importante permiten a Carlos VII sostener la guerra de otra manera. Formigny acelera la recuperación de Normandía.",
      },
      {
        anio: 1453,
        persona: "JUANTALBOT",
        personas: ["JUANTALBOT", "JEANBUREAU", "CARLOS7FRA", "ENRIQ6ING"],
        eventoId: "CASTILLON_1453",
        titulo: "Castillon: el final convencional de 116 años de guerra",
        texto: "John Talbot intenta recuperar la situación inglesa en Guyena y muere en Castillon frente a un ejército francés apoyado por una poderosa artillería organizada por los hermanos Bureau. Inglaterra conserva Calais, pero pierde casi todas sus posesiones francesas. La guerra que empezó por feudos y derechos dinásticos termina dejando una monarquía francesa mucho más fuerte y una Inglaterra que pronto se hundirá en la Guerra de las Dos Rosas.",
      },
    ],
  },
  { id: "dos-rosas", titulo: "La Guerra de las Dos Rosas", subtitulo: "Lancaster, York y el ascenso Tudor", disponible: false },
  {
    id: "gioconda",
    titulo: "En busca de la Gioconda",
    subtitulo: "Un viaje por la vida de Leonardo y las mujeres detrás del enigma",
    disponible: true,
    descripcion: "Seguimos a Leonardo desde la corte de los Sforza hasta Francia. En el camino aparecen retratos femeninos seguros, mujeres que realmente conoció y varias identidades propuestas para la Gioconda, hasta llegar a la identificación aceptada por el Louvre.",
    pasos: [
      {
        anio: 1482,
        persona: "LEONARDODAVINCI",
        personas: ["LEONARDODAVINCI", "LUDOVSFOR"],
        eventoId: "LEONARDO_MILAN_1482",
        titulo: "Milán: Leonardo entra en una corte de imágenes y poder",
        texto: "Leonardo deja Florencia y entra en la órbita de Ludovico Sforza. En Milán no es solo pintor: diseña máquinas, fiestas, fortificaciones y proyectos monumentales. Pero también aprende a convertir el retrato cortesano en algo mucho más vivo. Aquí comienza la pista que nos llevará hacia la Gioconda.",
      },
      {
        anio: 1490,
        persona: "CECIGALL",
        personas: ["LEONARDODAVINCI", "CECIGALL", "LUDOVSFOR"],
        eventoId: "DAMA_ARMINO_1490",
        titulo: "La Dama del armiño: un misterio que sí resolvemos",
        texto: "Cecilia Gallerani, joven culta de la corte y amante de Ludovico Sforza, posa para Leonardo hacia 1490. Su identificación como la Dama del armiño está sólidamente establecida. El retrato es una parada esencial: años antes de la Gioconda, Leonardo ya hace que una mujer parezca sorprendida en medio de un gesto y de una conversación invisible.",
      },
      {
        anio: 1499,
        persona: "ISABELLAESTE",
        personas: ["LEONARDODAVINCI", "ISABELLAESTE", "LUDOVSFOR"],
        titulo: "Mantua: Isabella d'Este quiere un Leonardo",
        texto: "Cuando los franceses derriban el poder de Ludovico, Leonardo abandona Milán. En Mantua retrata sobre papel a Isabella d'Este. El dibujo se conserva y demuestra una relación artística directa entre ambos. Precisamente por esa cercanía y por su enorme prestigio, Isabella ha aparecido en algunas teorías sobre la Gioconda, aunque el retrato del Louvre apunta en otra dirección.",
      },
      {
        anio: 1500,
        persona: "CATASFOR",
        personas: ["LEONARDODAVINCI", "CATASFOR", "CESARBORJA"],
        titulo: "La Italia de Caterina Sforza",
        texto: "Leonardo recorre una Italia convulsa en la que las mismas familias aparecen una y otra vez alrededor del arte y de la guerra. Caterina Sforza, señora de Forlì e hija de Galeazzo Maria, también ha sido propuesta como identidad del retrato. Es una hipótesis sugerente por el entorno histórico, pero no posee la cadena documental que acabaremos encontrando en Florencia.",
      },
      {
        anio: 1502,
        persona: "CESARBORJA",
        personas: ["LEONARDODAVINCI", "CESARBORJA"],
        eventoId: "LEONARDO_BORJA_1502",
        titulo: "Con César Borja: Leonardo dibuja territorios, no rostros",
        texto: "Durante unos meses Leonardo trabaja para César Borja como ingeniero militar. Recorre fortalezas y ciudades, estudia ríos, caminos y defensas y produce algunos de sus mapas más extraordinarios. El episodio recuerda que el hombre que pintará el rostro más famoso de Europa observa con la misma obsesión una cara, una máquina o un paisaje.",
      },
      {
        anio: 1503,
        persona: "LISAGHERARDINI",
        personas: ["LEONARDODAVINCI", "LISAGHERARDINI", "FRANCESCOGIOCONDO"],
        eventoId: "GIOCONDA_1503",
        titulo: "Florencia: aquí aparece la pista decisiva",
        texto: "De regreso en Florencia llegamos a Lisa Gherardini, esposa del mercader Francesco del Giocondo. El nombre de la familia explica 'Gioconda'; la tradición textual y la documentación conocida encajan con el inicio del retrato hacia 1503. Esta es la identificación que hoy mantiene el Louvre y el consenso historiográfico dominante: la mujer del cuadro es Lisa Gherardini.",
      },
      {
        anio: 1504,
        persona: "ISABNAP",
        personas: ["ISABNAP", "COSTANZADAVALOS", "BIANSFOR", "CATASFOR", "ISABELLAESTE", "LISAGHERARDINI"],
        titulo: "¿Entonces por qué existen tantas candidatas?",
        texto: "Porque Leonardo trabajó durante décadas entre cortes llenas de mujeres poderosas y porque dejó obras, dibujos y noticias difíciles de encajar. Isabella de Aragón, Costanza d'Avalos, Bianca Giovanna Sforza, Caterina Sforza e Isabella d'Este han aparecido en distintas propuestas. Algunas conectan bien con una etapa de su vida; ninguna reúne, a día de hoy, el conjunto de indicios que favorece a Lisa Gherardini.",
      },
      {
        anio: 1506,
        persona: "CHARLES2AMBOISE",
        personas: ["LEONARDODAVINCI", "CHARLES2AMBOISE"],
        eventoId: "LEONARDO_MILAN_1506",
        titulo: "Leonardo vuelve a Milán, pero el retrato viaja con él",
        texto: "Leonardo regresa a un Milán controlado por Francia y encuentra un nuevo protector en Charles II d'Amboise. La Gioconda no queda atrás como un encargo entregado y cerrado: Leonardo conserva la pintura y continúa trabajando en ella durante años. El cuadro empieza a convertirse en una obra personal del artista.",
      },
      {
        anio: 1513,
        persona: "GIULIANOMEDICI",
        personas: ["LEONARDODAVINCI", "GIULIANOMEDICI", "PAPA_LEON10"],
        eventoId: "LEONARDO_ROMA_1513",
        titulo: "Roma: una última pista italiana",
        texto: "Leonardo se instala en Roma bajo la protección de Giuliano de' Medici, hermano de León X. Un testimonio posterior hablará de un retrato de una dama florentina realizado a petición de Giuliano. La noticia ha alimentado debates sobre la identidad del cuadro, pero el Louvre la considera compatible con un problema de identificación de las obras vistas por el testigo, no una razón suficiente para desplazar a Lisa.",
      },
      {
        anio: 1516,
        persona: "FRAN1FRA",
        personas: ["LEONARDODAVINCI", "FRAN1FRA", "FRANCESCOMELZI"],
        eventoId: "LEONARDO_FRANCIA_1516",
        titulo: "Francia: el cuadro abandona Italia con Leonardo",
        texto: "Francisco I llama a Leonardo a Francia. El artista cruza los Alpes acompañado por Francesco Melzi y lleva consigo varias pinturas en las que todavía trabaja. Entre ellas está la Gioconda. Su último mecenas ya no encarga el retrato: hereda la presencia del artista y, después, la obra que Leonardo nunca quiso dejar atrás.",
      },
      {
        anio: 1519,
        persona: "LEONARDODAVINCI",
        personas: ["LEONARDODAVINCI", "LISAGHERARDINI", "CECIGALL", "ISABELLAESTE", "FRAN1FRA"],
        eventoId: "LEONARDO_MUERTE_1519",
        titulo: "Final de la búsqueda: una mujer y toda una vida de Leonardo",
        texto: "Leonardo muere en Francia en 1519. El viaje nos ha dejado retratos seguros como Cecilia Gallerani, modelos realmente dibujadas como Isabella d'Este y una constelación de candidatas nacida de las cortes que recorrió. Pero cuando todas las pistas se ordenan, el punto de llegada es claro: el Louvre identifica la Gioconda como el retrato de Lisa Gherardini, esposa de Francesco del Giocondo. El verdadero misterio ya no es tanto quién es, sino por qué Leonardo siguió transformando su retrato durante tantos años.",
      },
    ],
  },
  { id: "revolucion-protestante", titulo: "La Revolución Protestante", subtitulo: "Erasmo, Lutero, Calvino, Enrique VIII, Carlos V y la respuesta de Trento", disponible: false },
];
