// Imágenes de fichas de biografía.
// Ajuste manual del encuadre:
// - edita la propiedad `encuadre` en formato CSS `"50% 20%"`
// - primer valor = eje horizontal, segundo valor = eje vertical
// - la imagen se muestra en un marco fijo con object-fit: cover
// - así puedes centrar la cara sin recortar físicamente el archivo

export const IMAGENES_PERSONAS = {
  CAR1BORG: {
    archivo: "/personas-img/CAR1BORG.webp",
    encuadre: "50% 24%",
    alt: "Retrato de Carlos I de Borgoña, el Temerario",
    tipo: "Retrato contemporáneo",
    obra: "Retrato de Carlos el Temerario",
    autor: "Rogier van der Weyden (atribuido)",
    fecha: "c. 1454",
    institucion: "Gemäldegalerie, Staatliche Museen zu Berlin · inv. 545",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Charles_the_Bold_1460_(cropped).jpg",
    derechos: "Dominio público · PD-Art / PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  CARLOS5: {
    archivo: "/personas-img/CARLOS5.webp",
    encuadre: "50% 20%",
    alt: "Retrato de Carlos V",
    tipo: "Retrato contemporáneo",
    obra: "Portrait of Charles V",
    autor: "Lambert Sustris (atribuido); antes atribuido a Tiziano",
    fecha: "c. 1548",
    institucion: "Alte Pinakothek, Múnich",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Portrait_of_Charles_V,_Holy_Roman_Emperor,_seated_(1500%E2%80%931558),_formerly_attributed_to_Titian_(Alte_Pinakothek,_Munich)_(3x4_cropped).jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  FEL2ESP: {
    archivo: "/personas-img/FEL2ESP.webp",
    encuadre: "52% 18%",
    zoom: 1.9,
    alt: "Retrato de Felipe II de España",
    tipo: "Retrato contemporáneo",
    obra: "Retrato de Felipe II",
    autor: "Sofonisba Anguissola",
    fecha: "1565",
    institucion: "Museo del Prado, Madrid",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Portrait_of_Philip_II_of_Spain_by_Sofonisba_Anguissola_-_002b.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  ALF5ARAG: {
    archivo: "/personas-img/ALF5ARAG.webp",
    encuadre: "50% 18%",
    alt: "Retrato de Alfonso V de Aragón",
    tipo: "Retrato contemporáneo",
    obra: "Ritratto di Alfonso d'Aragona",
    autor: "Escuela napolitana, quizá según Piero della Francesca",
    fecha: "c. 1450-1460",
    institucion: "Musée Jacquemart-André, París",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Scuola_napoletana_forse_da_piero_della_francesca,_ritratto_di_alfonso_d%27aragona,_1450-60_ca._(parigi,_mus%C3%A9e_jacquemart-andr%C3%A9)_03.JPG",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  FED2HOH: {
    archivo: "/personas-img/FED2HOH.webp",
    encuadre: "50% 20%",
    alt: "Representación de Federico II Hohenstaufen con su halcón",
    tipo: "Representación contemporánea",
    obra: "Federico II con su halcón, de De arte venandi cum avibus",
    autor: "Miniaturista anónimo",
    fecha: "finales del siglo XIII",
    institucion: "Biblioteca Apostolica Vaticana",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Frederick_II_and_eagle.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  ISABPORTEMP: {
    archivo: "/personas-img/ISABPORTEMP.webp",
    encuadre: "50% 16%",
    alt: "Retrato de Isabel de Portugal, emperatriz",
    tipo: "Retrato póstumo",
    obra: "La emperatriz Isabel de Portugal",
    autor: "Tiziano",
    fecha: "c. 1548",
    institucion: "Museo del Prado, Madrid",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:La_emperatriz_Isabel_de_Portugal,_por_Tiziano_(cropped).jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  MARIA1ING: {
    archivo: "/personas-img/MARIA1ING.webp",
    encuadre: "50% 16%",
    alt: "Retrato de María I de Inglaterra",
    tipo: "Retrato contemporáneo",
    obra: "Portrait of Mary I",
    autor: "Antonis Mor",
    fecha: "c. 1554",
    institucion: "Museo del Prado, Madrid",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Anthonis_Mor_001_(cropped).jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  FED1HERM: {
    archivo: "/personas-img/FED1HERM.webp",
    encuadre: "50% 18%",
    alt: "Retrato de Federico el Hermoso",
    tipo: "Retrato posterior",
    obra: "Frederick the Fair",
    autor: "Anton Boys",
    fecha: "siglo XVI",
    institucion: "Schloss Ambras / Kunsthistorisches Museum, Viena",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Frederick_III_the_Fair.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  ALB1HAB: {
    archivo: "/personas-img/ALB1HAB.webp",
    encuadre: "50% 16%",
    alt: "Retrato de Alberto I de Habsburgo",
    tipo: "Retrato posterior",
    obra: "Albrecht I",
    autor: "Anton Boys",
    fecha: "siglo XVI",
    institucion: "Schloss Ambras / Kunsthistorisches Museum, Viena",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:AlbrechtI.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  LUIS4: {
    archivo: "/personas-img/LUIS4.webp",
    encuadre: "50% 12%",
    alt: "Retrato de Luis IV de Baviera",
    tipo: "Retrato posterior",
    obra: "Kaiser Ludwig der Bayer",
    autor: "Anónimo alemán",
    fecha: "siglo XIX",
    institucion: "Bayerische Staatsgemäldesammlungen, Múnich",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Deutsch_19._Jahrhundert_-_Kaiser_Ludwig_der_Bayer_-_4329_-_Bavarian_State_Painting_Collections.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  ROD1HAB: {
    archivo: "/personas-img/ROD1HAB.webp",
    encuadre: "50% 14%",
    alt: "Retrato de Rodolfo I de Habsburgo",
    tipo: "Retrato posterior",
    obra: "Rudolph I of Austria",
    autor: "Anton Boys",
    fecha: "siglo XVI",
    institucion: "Schloss Ambras / Kunsthistorisches Museum, Viena",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Rudolph_I_of_Austria.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  MAXIM1: {
    archivo: "/personas-img/MAXIM1.webp",
    encuadre: "50% 15%",
    alt: "Retrato de Maximiliano I",
    tipo: "Retrato contemporáneo",
    obra: "Portrait of Maximilian I",
    autor: "Albrecht Dürer",
    fecha: "1519",
    institucion: "Kunsthistorisches Museum, Viena",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Albrecht_D%C3%BCrer_-_Portrait_of_Maximilian_I_-_Google_Art_Project.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  FED3HAB: {
    archivo: "/personas-img/FED3HAB.webp",
    encuadre: "50% 16%",
    alt: "Retrato de Federico III, emperador",
    tipo: "Retrato posterior",
    obra: "Portrait of Frederick III, Holy Roman Emperor",
    autor: "Hans Burgkmair el Viejo (atribuido)",
    fecha: "finales del siglo XV - comienzos del XVI",
    institucion: "Kunsthistorisches Museum, Viena",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Frederick_III,_Holy_Roman_Emperor_(Burgkmair).jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  LEONORPOR: {
    archivo: "/personas-img/LEONORPOR.webp",
    encuadre: "50% 16%",
    alt: "Retrato de Leonor de Portugal",
    tipo: "Retrato póstumo",
    obra: "Portrait of Eleonore of Portugal",
    autor: "Hans Burgkmair el Viejo (atribuido)",
    fecha: "finales del siglo XV - comienzos del XVI",
    institucion: "Kunsthistorisches Museum, Viena",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Hans_Burgkmair_d._%C3%84._006.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  ALB2HABS: {
    archivo: "/personas-img/ALB2HABS.webp",
    encuadre: "50% 16%",
    alt: "Retrato de Alberto II de Habsburgo",
    tipo: "Retrato posterior",
    obra: "Albert II of Austria",
    autor: "Antoni Boys",
    fecha: "siglo XVI",
    institucion: "Kulturpool / retrato histórico de colección austríaca",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Albert_II_of_Austria.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  LEOP1AUS: {
    archivo: "/personas-img/LEOP1AUS.webp",
    encuadre: "50% 16%",
    alt: "Retrato de Leopoldo I de Austria",
    tipo: "Retrato posterior",
    obra: "Leopold I of Habsburg",
    autor: "Antoni Boys",
    fecha: "siglo XVI",
    institucion: "Kulturpool / retrato histórico de colección austríaca",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Leopold_I_Habsburg.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  MARIABORG: {
    archivo: "/personas-img/MARIABORG.webp",
    encuadre: "54% 18%",
    alt: "Retrato de María de Borgoña",
    tipo: "Retrato contemporáneo",
    obra: "Mary of Burgundy",
    autor: "Escuela neerlandesa o suralemana del siglo XV; posiblemente Michael Pacher",
    fecha: "finales del siglo XV",
    institucion: "Colección histórica reproducida en Wikimedia Commons",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Mary_of_Burgundy_(1458%E2%80%931482),_by_Netherlandish_or_South_German_School_of_the_late_15th_Century.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  LEONAUST: {
    archivo: "/personas-img/LEONAUST.webp",
    encuadre: "50% 14%",
    alt: "Retrato de Leonor de Austria",
    tipo: "Retrato contemporáneo",
    obra: "Portrait of Eleanor of Austria, Archduchess of Austria",
    autor: "Joos van Cleve",
    fecha: "siglo XVI",
    institucion: "Colección histórica reproducida en Wikimedia Commons",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Joos_van_Cleve_003.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  FEL1CAST: {
    archivo: "/personas-img/FEL1CAST.webp",
    encuadre: "50% 15%",
    alt: "Retrato de Felipe el Hermoso",
    tipo: "Retrato contemporáneo",
    obra: "Philipp der Schöne (1478-1506)",
    autor: "Juan de Flandes (atribuido)",
    fecha: "hacia 1500",
    institucion: "Kunsthistorisches Museum Wien, Gemäldegalerie",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Juan_de_Flandes,_Kunsthistorisches_Museum_Wien,_Gem%C3%A4ldegalerie_-_Philipp_der_Sch%C3%B6ne_(1478-1506)_-_GG_3872.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  FERN1EMP: {
    archivo: "/personas-img/FERN1EMP.webp",
    encuadre: "50% 8%",
    alt: "Retrato de Fernando I de Habsburgo",
    tipo: "Retrato contemporáneo",
    obra: "Emperor Ferdinand I",
    autor: "Hans Bocksberger el Viejo",
    fecha: "siglo XVI",
    institucion: "Colección histórica reproducida en Wikimedia Commons",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Hans_Bocksberger_der_Aeltere_001.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  JUANA1CAST: {
    archivo: "/personas-img/JUANA1CAST.webp",
    encuadre: "50% 14%",
    alt: "Retrato de Juana I de Castilla",
    tipo: "Retrato contemporáneo",
    obra: "Portrait of Joan the Mad",
    autor: "Juan de Flandes",
    fecha: "hacia 1496-1500",
    institucion: "Colección histórica reproducida en Wikimedia Commons",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Juan_de_Flandes_003.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
};

export default IMAGENES_PERSONAS;
