// Metadatos editoriales de las imágenes mostradas en la biografía.
// Las claves corresponden al ID de PERSONAS. Si un ID no aparece aquí,
// su ficha biográfica se muestra sin imagen ni espacio reservado.

export const IMAGENES_PERSONAS = {
  CAR1BORG: {
    archivo: "/personas-img/CAR1BORG.webp",
    alt: "Retrato contemporáneo de Carlos el Temerario",
    tipo: "Retrato contemporáneo",
    obra: "Retrato de Carlos el Temerario",
    autor: "Rogier van der Weyden",
    fecha: "c. 1454",
    institucion: "Gemäldegalerie, Staatliche Museen zu Berlin · inv. 545",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Charles_the_Bold_1460_(cropped).jpg",
    derechos: "Dominio público · PD-Art / PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  CARLOS5: {
    archivo: "/personas-img/CARLOS5.webp",
    alt: "Retrato contemporáneo de Carlos V (I de España)",
    tipo: "Retrato contemporáneo",
    obra: "Retrato de Carlos V",
    autor: "Lambert Sustris (atribución actual; antes atribuido a Tiziano)",
    fecha: "c. 1548",
    institucion: "Alte Pinakothek, Múnich",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Portrait_of_Charles_V,_Holy_Roman_Emperor,_seated_(1500%E2%80%931558),_formerly_attributed_to_Titian_(Alte_Pinakothek,_Munich)_(3x4_cropped).jpg",
    derechos: "Dominio público · PD-Art / PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  FEL2ESP: {
    archivo: "/personas-img/FEL2ESP.webp",
    alt: "Retrato contemporáneo de Felipe II de España",
    tipo: "Retrato contemporáneo",
    obra: "Retrato de Felipe II",
    autor: "Sofonisba Anguissola",
    fecha: "1565",
    institucion: "Museo del Prado, Madrid · P001036",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Portrait_of_Philip_II_of_Spain_by_Sofonisba_Anguissola_-_002b.jpg",
    derechos: "Dominio público · PD-Art / PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  ALF5ARAG: {
    archivo: "/personas-img/ALF5ARAG.webp",
    alt: "Retrato contemporáneo de Alfonso V de Aragón",
    tipo: "Retrato contemporáneo",
    obra: "Retrato de Alfonso de Aragón",
    autor: "Escuela napolitana, quizá según Piero della Francesca",
    fecha: "c. 1450–1460",
    institucion: "Musée Jacquemart-André, París",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Scuola_napoletana_forse_da_piero_della_francesca,_ritratto_di_alfonso_d%27aragona,_1450-60_ca._(parigi,_mus%C3%A9e_jacquemart-andr%C3%A9)_03.JPG",
    derechos: "Obra en dominio público · reproducción fotográfica en Commons",
    derechosUrl: "https://commons.wikimedia.org/wiki/File:Scuola_napoletana_forse_da_piero_della_francesca,_ritratto_di_alfonso_d%27aragona,_1450-60_ca._(parigi,_mus%C3%A9e_jacquemart-andr%C3%A9)_03.JPG#Licensing",
  },

  FED2HOH: {
    archivo: "/personas-img/FED2HOH.webp",
    alt: "Representación de Federico II Hohenstaufen con su halcón",
    tipo: "Representación medieval",
    obra: "Federico II con su halcón, en De arte venandi cum avibus",
    autor: "Miniaturista anónimo",
    fecha: "finales del siglo XIII",
    institucion: "Biblioteca Apostolica Vaticana · Pal. lat. 1071, fol. 1",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Frederick_II_and_eagle.jpg",
    derechos: "Dominio público",
    derechosUrl: "https://commons.wikimedia.org/wiki/File:Frederick_II_and_eagle.jpg#Licensing",
  },

  ISABPORTEMP: {
    archivo: "/personas-img/ISABPORTEMP.webp",
    alt: "Retrato póstumo de Isabel de Portugal, emperatriz",
    tipo: "Retrato póstumo",
    obra: "Retrato de la emperatriz Isabel de Portugal",
    autor: "Tiziano",
    fecha: "1548",
    institucion: "Museo del Prado, Madrid",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:La_emperatriz_Isabel_de_Portugal,_por_Tiziano_(cropped).jpg",
    derechos: "Dominio público · PD-Art / PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  MARIATUDOR: {
    archivo: "/personas-img/MARIATUDOR.webp",
    alt: "Retrato contemporáneo de María Tudor",
    tipo: "Retrato contemporáneo",
    obra: "Retrato de María Tudor",
    autor: "Antonis Mor",
    fecha: "1554",
    institucion: "Museo del Prado, Madrid",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Anthonis_Mor_001_(cropped).jpg",
    derechos: "Dominio público · PD-Art / PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  FED1HERM: {
    archivo: "/personas-img/FED1HERM.webp",
    alt: "Representación posterior de Federico de Habsburgo, el Hermoso",
    tipo: "Representación posterior",
    obra: "Federico el Hermoso",
    autor: "Anton Boys",
    fecha: "siglo XVI",
    institucion: "Serie de retratos habsbúrgicos de Anton Boys",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Frederick_III_the_Fair.jpg",
    derechos: "Dominio público",
    derechosUrl: "https://commons.wikimedia.org/wiki/File:Frederick_III_the_Fair.jpg#Licensing",
  },

  ALB1HAB: {
    archivo: "/personas-img/ALB1HAB.webp",
    alt: "Representación posterior de Alberto I de Habsburgo",
    tipo: "Representación posterior",
    obra: "Alberto I",
    autor: "Anton Boys",
    fecha: "siglo XVI",
    institucion: "Serie de retratos habsbúrgicos de Anton Boys",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:AlbrechtI.jpg",
    derechos: "Dominio público",
    derechosUrl: "https://commons.wikimedia.org/wiki/File:AlbrechtI.jpg#Licensing",
  },

  LUIS4: {
    archivo: "/personas-img/LUIS4.webp",
    alt: "Representación posterior de Luis IV de Baviera",
    tipo: "Representación posterior",
    obra: "Kaiser Ludwig der Bayer",
    autor: "Anónimo alemán",
    fecha: "c. 1800",
    institucion: "Bayerische Staatsgemäldesammlungen, Múnich",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Deutsch_19._Jahrhundert_-_Kaiser_Ludwig_der_Bayer_-_4329_-_Bavarian_State_Painting_Collections.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  ROD1HAB: {
    archivo: "/personas-img/ROD1HAB.webp",
    alt: "Representación posterior de Rodolfo I de Habsburgo",
    tipo: "Representación posterior",
    obra: "Rodolfo I de Austria",
    autor: "Anton Boys",
    fecha: "siglo XVI",
    institucion: "Serie de retratos habsbúrgicos de Anton Boys",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Rudolph_I_of_Austria.jpg",
    derechos: "Dominio público",
    derechosUrl: "https://commons.wikimedia.org/wiki/File:Rudolph_I_of_Austria.jpg#Licensing",
  },

  MAXIM1: {
    archivo: "/personas-img/MAXIM1.webp",
    alt: "Retrato contemporáneo de Maximiliano I",
    tipo: "Retrato contemporáneo",
    obra: "Retrato del emperador Maximiliano I",
    autor: "Albrecht Dürer",
    fecha: "1519",
    institucion: "Kunsthistorisches Museum, Viena",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Albrecht_D%C3%BCrer_-_Portrait_of_Maximilian_I_-_Google_Art_Project.jpg",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  FED3HAB: {
    archivo: "/personas-img/FED3HAB.webp",
    alt: "Retrato posterior de Federico III basado en un original perdido de 1468",
    tipo: "Retrato posterior",
    obra: "Retrato de Federico III",
    autor: "Atribuido a Hans Burgkmair el Viejo",
    fecha: "finales del siglo XV – comienzos del XVI",
    institucion: "Según un original perdido de 1468",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Frederick_III,_Holy_Roman_Emperor_(Burgkmair).jpg",
    derechos: "Dominio público · PD-Art / PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },

  LEONORPOR: {
    archivo: "/personas-img/LEONORPOR.webp",
    alt: "Retrato póstumo de Leonor de Portugal basado en un original perdido de 1468",
    tipo: "Retrato póstumo",
    obra: "Retrato de Leonor de Portugal",
    autor: "Atribuido a Hans Burgkmair el Viejo",
    fecha: "finales del siglo XV – comienzos del XVI",
    institucion: "Según un original perdido de 1468",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Hans_Burgkmair_d._%C3%84._006.jpg",
    derechos: "Dominio público · PD-Art / PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
  },
};

export default IMAGENES_PERSONAS;
