// Metadatos de imágenes para fichas de biografía / detalle.
// Añade aquí nuevas entradas usando como clave el id de la persona en personas.jsx.

const imagenesPersonas = {
  CAR1BORG: {
    src: "/personas-img/CAR1BORG.webp",
    alt: "Retrato de Carlos I el Calvo",
    pie: "Carlos I el Calvo. Miniatura medieval.",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Vivien_Bible_Charles_the_Bald.jpg",
    autor: "Taller de la Biblia de Vivien",
    obra: "Carlos el Calvo en la Biblia de Vivien",
    fecha: "c. 845",
    institucion: "Bibliothèque nationale de France",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Representación contemporánea",
  },

  CARLOS5: {
    src: "/personas-img/CARLOS5.webp",
    alt: "Retrato de Carlos V (I de España)",
    pie: "Carlos V (I de España). Retrato atribuido a Lambert Sustris, antes atribuido a Tiziano, c. 1548.",
    fuente: "Wikimedia Commons",
    fuenteUrl:
      "https://commons.wikimedia.org/wiki/File:Portrait_of_Charles_V,_Holy_Roman_Emperor,_seated_(1500%E2%80%931558),_formerly_attributed_to_Titian_(Alte_Pinakothek,_Munich)_(3x4_cropped).jpg",
    autor: "Lambert Sustris (atribuido); antes atribuido a Tiziano",
    obra: "Portrait of Charles V",
    fecha: "c. 1548",
    institucion: "Alte Pinakothek, Múnich",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Retrato contemporáneo",
  },

  FEL2ESP: {
    src: "/personas-img/FEL2ESP.webp",
    alt: "Retrato de Felipe II de España",
    pie: "Felipe II de España. Sofonisba Anguissola, 1565.",
    fuente: "Wikimedia Commons",
    fuenteUrl:
      "https://commons.wikimedia.org/wiki/File:Portrait_of_Philip_II_of_Spain_by_Sofonisba_Anguissola_-_002b.jpg",
    autor: "Sofonisba Anguissola",
    obra: "Retrato de Felipe II",
    fecha: "1565",
    institucion: "Museo del Prado, Madrid",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Retrato contemporáneo",
  },

  ALF5ARAG: {
    src: "/personas-img/ALF5ARAG.webp",
    alt: "Retrato de Alfonso V de Aragón",
    pie: "Alfonso V de Aragón. Escuela napolitana, quizá según Piero della Francesca, c. 1450-1460.",
    fuente: "Wikimedia Commons",
    fuenteUrl:
      "https://commons.wikimedia.org/wiki/File:Scuola_napoletana_forse_da_piero_della_francesca,_ritratto_di_alfonso_d%27aragona,_1450-60_ca._(parigi,_mus%C3%A9e_jacquemart-andr%C3%A9)_03.JPG",
    autor: "Escuela napolitana, quizá según Piero della Francesca",
    obra: "Ritratto di Alfonso d'Aragona",
    fecha: "c. 1450-1460",
    institucion: "Musée Jacquemart-André, París",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Retrato contemporáneo",
  },

  FED2HOH: {
    src: "/personas-img/FED2HOH.webp",
    alt: "Representación de Federico II Hohenstaufen con su halcón",
    pie: "Federico II Hohenstaufen con su halcón. Miniatura de finales del siglo XIII.",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Frederick_II_and_eagle.jpg",
    autor: "Miniaturista anónimo",
    obra: "Federico II con su halcón, de De arte venandi cum avibus",
    fecha: "finales del siglo XIII",
    institucion: "Biblioteca Apostolica Vaticana, ms. Pal. lat. 1071, fol. 1",
    derechos: "Dominio público",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Representación contemporánea",
  },

  ISABPORTEMP: {
    src: "/personas-img/ISABPORTEMP.webp",
    alt: "Retrato de Isabel de Portugal, emperatriz",
    pie: "Isabel de Portugal. Tiziano, c. 1548.",
    fuente: "Wikimedia Commons",
    fuenteUrl:
      "https://commons.wikimedia.org/wiki/File:La_emperatriz_Isabel_de_Portugal,_por_Tiziano_(cropped).jpg",
    autor: "Tiziano",
    obra: "Retrato de la emperatriz Isabel de Portugal",
    fecha: "c. 1548",
    institucion: "Museo del Prado, Madrid",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Retrato póstumo",
  },

  MARIATUDOR: {
    src: "/personas-img/MARIATUDOR.webp",
    alt: "Retrato de María Tudor",
    pie: "María Tudor. Antonis Mor, c. 1554.",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Anthonis_Mor_001_(cropped).jpg",
    autor: "Antonis Mor",
    obra: "Portrait of Mary Tudor",
    fecha: "c. 1554",
    institucion: "Museo del Prado, Madrid",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Retrato contemporáneo",
  },

  FED1HERM: {
    src: "/personas-img/FED1HERM.webp",
    alt: "Retrato de Federico de Habsburgo, el Hermoso",
    pie: "Federico de Habsburgo, «el Hermoso». Anton Boys, siglo XVI.",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Frederick_III_the_Fair.jpg",
    autor: "Anton Boys",
    obra: "Frederick III the Fair",
    fecha: "siglo XVI",
    institucion: "Schloss Ambras / Kunsthistorisches Museum, Viena",
    derechos: "Dominio público",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Retrato posterior",
  },

  ALB1HAB: {
    src: "/personas-img/ALB1HAB.webp",
    alt: "Retrato de Alberto I de Habsburgo",
    pie: "Alberto I de Habsburgo. Anton Boys, siglo XVI.",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:AlbrechtI.jpg",
    autor: "Anton Boys",
    obra: "Albrecht I",
    fecha: "siglo XVI",
    institucion: "Schloss Ambras / Kunsthistorisches Museum, Viena",
    derechos: "Dominio público",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Retrato posterior",
  },

  LUIS4: {
    src: "/personas-img/LUIS4.webp",
    alt: "Retrato de Luis IV de Baviera",
    pie: "Luis IV de Baviera. Pintor alemán anónimo, c. 1800.",
    fuente: "Wikimedia Commons",
    fuenteUrl:
      "https://commons.wikimedia.org/wiki/File:Deutsch_19._Jahrhundert_-_Kaiser_Ludwig_der_Bayer_-_4329_-_Bavarian_State_Painting_Collections.jpg",
    autor: "Anónimo alemán",
    obra: "Kaiser Ludwig der Bayer",
    fecha: "c. 1800",
    institucion: "Bavarian State Painting Collections, Múnich",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Retrato posterior",
  },

  ROD1HAB: {
    src: "/personas-img/ROD1HAB.webp",
    alt: "Retrato de Rodolfo I de Habsburgo",
    pie: "Rodolfo I de Habsburgo. Anton Boys, siglo XVI.",
    fuente: "Wikimedia Commons",
    fuenteUrl: "https://commons.wikimedia.org/wiki/File:Rudolph_I_of_Austria.jpg",
    autor: "Anton Boys",
    obra: "Rudolph I of Austria",
    fecha: "siglo XVI",
    institucion: "Schloss Ambras / Kunsthistorisches Museum, Viena",
    derechos: "Dominio público",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Retrato posterior",
  },

  MAXIM1: {
    src: "/personas-img/MAXIM1.webp",
    alt: "Retrato de Maximiliano I",
    pie: "Maximiliano I. Albrecht Dürer, 1519.",
    fuente: "Wikimedia Commons",
    fuenteUrl:
      "https://commons.wikimedia.org/wiki/File:Albrecht_D%C3%BCrer_-_Portrait_of_Maximilian_I_-_Google_Art_Project.jpg",
    autor: "Albrecht Dürer",
    obra: "Portrait of Maximilian I",
    fecha: "1519",
    institucion: "Kunsthistorisches Museum, Viena",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Retrato contemporáneo",
  },

  FED3HAB: {
    src: "/personas-img/FED3HAB.webp",
    alt: "Retrato de Federico III",
    pie: "Federico III. Atribuido a Hans Burgkmair el Viejo, finales del siglo XV o comienzos del XVI, a partir de un original perdido de 1468.",
    fuente: "Wikimedia Commons",
    fuenteUrl:
      "https://commons.wikimedia.org/wiki/File:Frederick_III,_Holy_Roman_Emperor_(Burgkmair).jpg",
    autor: "Hans Burgkmair el Viejo (atribuido)",
    obra: "Portrait of Frederick III, Holy Roman Emperor",
    fecha: "finales del siglo XV - comienzos del XVI",
    institucion: "Kunsthistorisches Museum, Viena",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Retrato posterior",
  },

  LEONORPOR: {
    src: "/personas-img/LEONORPOR.webp",
    alt: "Retrato de Leonor de Portugal",
    pie: "Leonor de Portugal. Atribuido a Hans Burgkmair el Viejo, finales del siglo XV o comienzos del XVI, a partir de un original perdido de 1468.",
    fuente: "Wikimedia Commons",
    fuenteUrl:
      "https://commons.wikimedia.org/wiki/File:Hans_Burgkmair_d._%C3%84._006.jpg",
    autor: "Hans Burgkmair el Viejo (atribuido)",
    obra: "Portrait of Eleonore of Portugal",
    fecha: "finales del siglo XV - comienzos del XVI",
    institucion: "Kunsthistorisches Museum, Viena",
    derechos: "Dominio público · PDM 1.0",
    derechosUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    tipo: "Retrato póstumo",
  },
};

export default imagenesPersonas;
